### ISSUE TITLE
bug: TypeError: Cannot read property 'client' of null

### ISSUE THREAD

**Issue by Mariam1449** [appium/appium-inspector#1023]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![678](https://github.com/appium/appium-inspector/assets/125437854/ab476b3b-495f-4c1b-bd60-735043341d22)

### Expected Behavior

Show the result.

### Operating System

Windows

### Appium Inspector Version

don't know

### Appium Version

v1.22.3

### Further Information

Provide me a solution.

**Comment by eglitise** [comment]
Closing due to no response
