### ISSUE TITLE
bug: Element position are offset in iPad in landscape mode

### ISSUE THREAD

**Issue by Reeta-L** [appium/appium-inspector#1025]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to automate an internal app on iPad. I am using appium 2 and xcuitest driver 4.18.4. Using appium inspector the elements are highlighted offset. And tap by coordinates also does not work.
See below screenshot the settings button is not highlighted correctly.
![Picture1](https://github.com/appium/appium-inspector/assets/141804385/08f078b8-4c2e-42f5-b610-3cc8879e8e77)
 I even try on the home screen, and the buttons are highlighted incorrectly. I suppose there is a problem with landscape mode on iPad.

### Expected Behavior

The settings button should be highlighted correctly and tap by coordinates should also work.

### Operating System

Windows

### Appium Inspector Version

23.8.1

### Appium Version

 2.0.0-beta.56

### Further Information

Operating system: Windows 10, 
Appium server on: macOS Monterery (12.5.1)
Appium server version (output of appium --version): 2.0.0-beta.56
Appium driver(s) and their version(s): xcuitest 4.18.4
Appium plugin(s) and their version(s):
Node.js version (output of node --version): v19.6.0
npm version (output of npm --version): 9.4.0
Last component(s) version which did not exhibit the problem: n/a
Platform and version under test: iPad 16.3.1
Real device or emulator/simulator: Real device - iPad (10th generation)

Steps:

1. Connect iPad in landscape mode.
2. Try to capture buttons on homescreen using appium inspector.
3. The buttons are offset highlighted
![pic1](https://github.com/appium/appium-inspector/assets/141804385/e6aff0fc-e54a-4a4d-80ff-53291e75fec5)
The buttons are offset
Appium Logs : 
[appium3.log](https://github.com/appium/appium-inspector/files/12310020/appium3.log)
![Picture1](https://github.com/appium/appium-inspector/assets/141804385/23c16cc4-56db-4895-8ed0-3545ac23da39)
![Picture2](https://github.com/appium/appium-inspector/assets/141804385/96be7ecf-68d8-43af-bc14-63b9c2edc398)
Linked appium issue https://github.com/appium/appium/issues/18968

**Comment by eglitise** [comment]
I can confirm this issue is reproducible only for landscape orientation - however, since the coordinates are returned by XCTest, there isn't really anything that can be done from the Inspector side. The coordinate transformations seemed fairly complex, so any extra transformations done in the Inspector would likely need to be app-specific, which is not feasible.
