### ISSUE TITLE
bug: proceeds to the page source view while the new session creation got failed

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium-inspector#1026]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Even when a new session creation gets failed (so, an error popup message appears), the main view proceeds to the page source view, then keep sowing below the attached view.

<img width="1095" alt="Screenshot 2023-08-10 at 10 38 01 AM" src="https://github.com/appium/appium-inspector/assets/5511591/6825490a-600d-4790-9cde-037368705171">showing

### Expected Behavior

We should go back to the capabilities etc section.

### Operating System

Mac

### Appium Inspector Version

2023.8.1

### Appium Version

any (e.g. 2 base, 1.22.3 base)

**Comment by KazuCocoa** [comment]
I'll take a look later if still none checks

**Comment by eglitise** [comment]
I think this behavior depends on why the session failed. If it's e.g. Appium 2 with missing `automationName` capability, it won't open the inspector view. But if it's something like the target mobile device not being connected, then yes, I've seen that this can happen.
