### ISSUE TITLE
feature request: Allow interactions for invisible elements 

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/appium-inspector#1027]
### Current Behavior

xcuitest driver is known for not returning precise values for the visibility attribute. It is not something we can change or fix - this is just how it always worked. See, for example https://discuss.appium.io/t/can-i-interact-with-elements-that-are-not-visible/39948 

### Suggested Solution

Allow interaction with invisible elements in the inspector. I don't know why it was disabled initially. I also don't see any problems in sending commands to such elements. In the worst case we'd get an exception, which would exactly mimic an automated approach. There is no point in "protecting" users from something they could do anyway.

**Comment by mykola-mokhnach** [comment]
cc @eglitise

**Comment by eglitise** [comment]
The Inspector already allows interacting with elements with the property `visible: false`. For example, in the iOS Settings, I can select a setting that's offscreen (which has `visible: false`), click on it, and it will still be opened.
Are some specific situations where this does not apply? I have not encountered these myself.

**Comment by mykola-mokhnach** [comment]
I have just checked the recent version and it's working as expected. Sorry for the confusion.
