### ISSUE TITLE
bug: failing image loading in appium inspector only and working fine with test scripts

### ISSUE THREAD

**Issue by krishtoautomate** [appium/appium-inspector#1038]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

failing image loading in appium inspector only and working fine with test scripts

connected through selenium Grid 4 using relay feature

**capabilities used:**
`{
  "appium:udid": "R5CR10T9PLE",
  "platformName": "Android",
  "appium:automationName": "uiautomator2",
  "appium:autoLaunch": true,
  "appium:noReset": false,
  "appium:fullReset": false,
  "appium:newCommandTimeout": 60,
  "appium:appPackage": "com.android.vending",
  "appium:appActivity": "com.android.vending.AssetBrowserActivity",
  "appium:language": "en",
  "appium:locale": "CA"
}`

<img width="789" alt="image" src="https://github.com/appium/appium-inspector/assets/20734341/5af003de-18bf-45da-9abb-32157a46e6d7">

<img width="432" alt="image" src="https://github.com/appium/appium-inspector/assets/20734341/aaa94517-60c4-491e-b4bb-edd842de7f52">

<img width="511" alt="image" src="https://github.com/appium/appium-inspector/assets/20734341/381c5ea4-42bc-487e-8e7d-4acacb149ce2">

### Expected Behavior

appium inspector also should run as automation scripts without any issues.

### Operating System

Mac

### Appium Inspector Version

2023.8.1

### Appium Version

2.0.1

### Further Information

toml:
`        [server]
        host = "172.21.34.235"
        url = "http://172.21.34.235:5552"
        port = 5552

        [events]
        publish = "tcp://172.21.34.239:4442"
        subscribe = "tcp://172.21.34.239:4443"

        [node]
        detect-drivers = false
        max-sessions = 1
        session-timeout = 180

        [relay]
        url = "http://172.21.34.235:4782"
        service-host = "172.21.34.235"
        service-port = 4782
        status-endpoint = "/status"

        configs = [
            "1", "{\"platformName\": \"ANDROID\", \"appium:udid\": \"R5CR10T9PLE\", \"appium:deviceName\": \"SM-G998W\",\"appium:automationName\": \"UIAutomator2\", \"appium:systemPort\":\"8301\", \"appium:platformVersion\": \"13\"}"
        ]
`

yml:
`server:
  port: 4782
  keep-alive-timeout: 80
  session-override: true
  use-drivers:
    - UIAutomator2 #uiautomator2 #XCUITest
  default-capabilities:
    appium:systemPort: 8301
    appium:udid: "R5CR10T9PLE"
    appium:deviceName: "SM-G998W"
    appium:platformName: "ANDROID"
    appium:platformVersion: "13"
`

**Comment by eglitise** [comment]
Could you please provide the full Appium server log? It seems strange that the failure line is related to MJPEG server capabilities, even though your capability set does not include them.

**Comment by krishtoautomate** [comment]
fixed. thanks for the info.

checked debug logs and observed that config file is not being parsed.
