### ISSUE TITLE
Unexpected errors: Path setting for Android Virtual Device failed even after setting path based on Shell

### ISSUE THREAD

**Issue by Pavel2Bambuch** [appium/appium-inspector#1047]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I m getting output of errors while I am trying to log in on Virtual Android device, even after setting up all credentials based on PowerShell gathered datas.
And even when I have setted up almostly all possibe credentials, then my ouput is "client of null", which I don't clearly understand why is it that.
Screen of output.
![Error](https://github.com/appium/appium-inspector/assets/134922549/891fd542-01fd-44e4-90ec-80c81d557d7b)

### Expected Behavior

Succesfully log in and inspect elements on virtaul device application for further works.

### Operating System

Windows

### Appium Inspector Version

8.1.0

### Appium Version

v2.0.1

### Further Information

[logfile.txt](https://github.com/appium/appium-inspector/files/12392525/logfile.txt)
From logs you can easilly read all datas needed to check out activities of virtual device.

![apk path](https://github.com/appium/appium-inspector/assets/134922549/dc8d39b4-e590-446e-803b-4a27a62aa75e)
Apk path gained from PowerShell which should have be always to base.apk

![JSON for Appium Inspector](https://github.com/appium/appium-inspector/assets/134922549/08dfc72f-65d3-4aa3-8410-0f46eec9c5f9)
Right side for settled JSON credentials.

Client null? What Client should have I add more? Should have I add address of Virtual device even if it is running on the same local IP address and server?

**Comment by KazuCocoa** [comment]
The `app` capability refers to the Appium server local file path. So you might need to specify your host machine's path for it
e.g. https://github.com/appium/appium-uiautomator2-driver#app

**Comment by Pavel2Bambuch** [comment]
![IP of android virtual device](https://github.com/appium/appium-inspector/assets/134922549/22a148a7-fadc-4837-bd68-2acdf407b3cc)
You mean IP address for virtual device?
Or it seems like I am not understanding what it is mean by this. :/ 
Or for package I want to use should have I use this **package:/data/app/~~2_IK3JDOWSvNkkIMequcFw==/szif.gtfoto-dWUj4QNgNzl5W2r_mUaYKQ==/** instead of going directly for apk?

**Comment by Pavel2Bambuch** [comment]
If you want me to pull out .APK file from virtual machine to local device I did it. But I am not sure how will I be able to test elements within this .apk file without using directly a device. :/

**Comment by KazuCocoa** [comment]
I mean if your apk is `C:\path\to\your.apk`, then the `appium:app` should be `C:\path\to\your.apk`. Your given one was the device's internal path, it is not expected path.

**Comment by KazuCocoa** [comment]
> If neither of the app, appPackage or browserName capabilities are provided then the driver starts from the Dashboard and expects the test knows what to do next. Do not provide both app and browserName capabilities at once.

If you wanted to use preinstalled apk, you do not need to set `app`

**Comment by Pavel2Bambuch** [comment]
![Screen](https://github.com/appium/appium-inspector/assets/134922549/d4a5ae82-0d94-4bc7-8c6f-47657705b7d5)
Ok, thanks to you. I got it. Now I will jsut need to learn how to manage the app. :) 
Sry for your time. :)

**Comment by eglitise** [comment]
As @KazuCocoa said, if you want to use a preinstalled app, it may be easier to use the `appPackage` and `appActivity` capabilities, and you can remove the `app` capability. However, `app` is better for cases where you aren't sure if the app is installed - and then you can remove `appPackage` and `appActivity`.
Also, the issue you originally encountered with `Cannot read property 'client' of null` is resolved in Appium Inspector 2023.8.2 - you would only see the first error about the incorrect app path.
