### ISSUE TITLE
Do I really need to set up all application activities to be able to inspect them

### ISSUE THREAD

**Issue by Pavel2Bambuch** [appium/appium-inspector#1048]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Actually when I am trying application which I am running within Android Studio, do I really need to download that application as .apk to windows folder and after I do and I set up all credentials needed for starting of connection.....
Do I really need to test activity after activity separatelly?
That's mean it will deny me from testing further elements and loops within application?

Or have I been mistaken?
Is there any guide how to set it up and use correctly since for me it seems, I am suppossed to change activity all the time.
Unless when I go start activity, than I will do some start checks and end up in not loaded up background of app like this:

![Snímek obrazovky 2023-08-21 102731](https://github.com/appium/appium-inspector/assets/134922549/a6b54c29-a7b3-49cd-a175-069be895227f)

### Expected Behavior

It will allow me using the application and get all inspected elements  which I would have need.

### Operating System

Windows

### Appium Inspector Version

8.1.0

### Appium Version

v2.0.1

### Further Information

Need guide. :)

**Comment by eglitise** [comment]
I mentioned this in #1047 just now, but if you already have the application installed, you can just use its `appPackage` and `appActivity` capabilities to launch it through the Inspector. You do not need to download the .apk and use the `app` capability.
And the `appActivity` can just be its initial launch activity - the UiAutomator2 driver is not locked to your app. You can even create a session entirely without `appPackage`, `appActivity`, and `app`; the session will then open on the current screen of your phone, and if you then manually open your app and press the Refresh button in the Inspector, you will see your app source.
For future questions, [please use the Appium forum](https://discuss.appium.io).

**Comment by Pavel2Bambuch** [comment]
Ok, thanks for answ. on all of my dumbs questions.... :) Have a nice day sir. For a future I will go look more on a forum if there will be a need. :)
