### ISSUE TITLE
feature request: use mobile:source command instead of `/source` somehow

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium-inspector#1062]
### Current Behavior

This issue is to leave the basic idea of https://github.com/appium/appium-inspector/pull/298.

In the Appium XCUITest driver, the endpoint of `/source` could take a longer time. It keeps the loading indicator infinite (kind of).

We have provided `mobile:source` command with `excludedAttributes` key/value to exclude expensive attributes in order to get the response as fast as possible instead of giving `snapshotMaxDepth`. `snapshotMaxDepth` limits the number of elements to get to make the response fast but it does not help so much if a user wanted to have nested elements.

So, https://github.com/appium/appium-inspector/pull/298 tries to call the `mobile:source` instead of `/source` to help like this situation

### Suggested Solution

calls `mobile:source` instead of `/source`

**Comment by mykola-mokhnach** [comment]
The most "expensive" attribute is the "visible" one. I would really love to get rid of it completely, but this is going to be a big breaking change.

**Comment by KazuCocoa** [comment]
From https://github.com/appium/appium-inspector/pull/298#issuecomment-1692155112

> what about a `sourceOptions` setting which has values that are the same as parameters to `mobile: source`. If the `sourceOptions` setting is set, then `mobile: source` will be called instead of the default `getPageSource` behaviour whenever the user does call `getPageSource`

---

My PR is outdated, so let me close that pr.

**Comment by eglitise** [comment]
I also think that having a `sourceOptions` setting is probably the best approach here. The advanced options dropdown could be a good location for this.

**Comment by jlipps** [comment]
Yeah, a driver-side setting means this 'feature' is available in both the appium server and the inspector merely via a capability, which seems easier initially than building stuff into the UI

**Comment by KazuCocoa** [comment]
We currently have settings, `pageSourceExcludedAttributes`, to control the source's response. iOS 17 requires XCUITest driver version that already includes the change (xcuitest driver 5.2.0), so basically we can guide users to use this `pageSourceExcludedAttributes` settings for the general `source` endpoint with newer XCUITest driver
