### ISSUE TITLE
bug: cannot start with iOS platformVersion 17.0

### ISSUE THREAD

**Issue by minorling** [appium/appium-inspector#1066]
### Is this an issue specifically with Appium Inspector?

- [x] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

my capability same as below and can start normally with iOS 15.0 without issue but iOS 17.0 which always show timeout:
{
  "platformName": "iOS",
  "platformVersion": "15.0",
  "deviceName": "iPhone 11 Pro Max",
  "app": "/Users/App/test.app"
}
and I've download xcode-beta for the iOS 17.0's simulator which can install the test APP normally, but it just cannot be opened in appium-inspector, my appium version is 2.1.3, appium-inspector version 2023.8.4
is there any suggestion for this issue? thanks.

### Expected Behavior

Should able to execute with iOS 17.0

### Operating System

Mac

### Appium Inspector Version

2023.8.4

### Appium Version

2.1.3

**Comment by eglitise** [comment]
Are you sure that is your full capability set? Appium 2 requires the `automationName` capability, which you have not listed here. Without it, the Inspector should not open the app regardless of your iOS version.
Personally, I do not use the `platformVersion` capability, and instead specify the device `udid`. But just now I did try setting `"platformVersion": "17.0"` for a real iOS 17 device, and it worked just fine.
I would suggest you to add your simulator's `udid` as a capability, and try again. If this does not work, please post your full Appium server log.

**Comment by KazuCocoa** [comment]
Yes, the full appium log may help to see possible reasons

**Comment by minorling** [comment]
sorry, the correct full capability set is below, and try to add udid still time out, put the appium server log attached, please help to check further, thank you.
{
  "platformName": "iOS",
  "appium:platformVersion": "17.0",
  "appium:deviceName": "iPhone 11 Pro Max",
  "appium:app": "/Users/Shared/App/test.app",
  "appium:automationName": "XCUITest",
  "appium:udid": "8538D9E4-50B9-45D3-B7C7-13EFA8BA7D42"
}
[appium_log.txt](https://github.com/appium/appium-inspector/files/12459603/appium_log.txt)

**Comment by eglitise** [comment]
Thanks for the log. Looks like the simulator is being created with Xcode 14.3.1, which doesn't support iOS 17. You may need to uninstall Xcode 14.3.1, and keep only your Xcode 15 Beta for this to work.

**Comment by minorling** [comment]
@eglitise thank you so much, I success run the inspector after remove Xcode 14.3.1, and reinstall the command line tool for xcode 15, after below steps, it works fine normally now, so much thanks!!!!
