### ISSUE TITLE
Please support the wsa of win11

### ISSUE THREAD

**Issue by aogg** [appium/appium-inspector#1081]
### Current Behavior

![image](https://github.com/appium/appium-inspector/assets/8998031/7d00216a-54c1-40a2-a7d0-60d3bb010f52)

### Suggested Solution

Resolution and buttons can be clicked

**Comment by aogg** [comment]
App in the picture is not a bad full-screen experience. It needs to be optimized.

**Comment by jlipps** [comment]
It's not clear to me what's being requested here. What doesn't work that you'd like to work?

**Comment by eglitise** [comment]
Closing due to no response
