### ISSUE TITLE
bug: Timings appear blank for id appium can see, and even recommends.

### ISSUE THREAD

**Issue by Jtech42** [appium/appium-inspector#1083]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This screenshot shows an android element running its get timing function. Despite being recommended by appium inspector and clearly read from the dom by appium for the inspector to recommend it, the resource-id shows blank time to get the element, and returns not found in the inspector view?

<img width="517" alt="Screenshot 2023-09-05 at 8 53 07 PM" src="https://github.com/appium/appium-inspector/assets/7834096/e3de7d49-55cf-49de-87a0-04ced8fa6259">

### Expected Behavior

The timing should appear next to the id in this case.

### Operating System

Mac

### Appium Inspector Version

2023.4.3

### Appium Version

1.22.3

**Comment by jlipps** [comment]
@Jtech42 you're using a version of the inspector 4 months out of date. Can you try with the latest?

**Comment by eglitise** [comment]
Closing due to no response
