### ISSUE TITLE
need to update request library

### ISSUE THREAD

**Issue by jlipps** [appium/appium-inspector#109]
request-promise is built on request which has been defunct for some time. should probably move to Got or something similar. there's a nice [migration guide](https://github.com/sindresorhus/got/blob/main/documentation/migration-guides/request.md) from request to Got that could be useful.

**Comment by jlipps** [comment]
this is basically done except for the auto-updater (which might not even be working) and the crowdin sync

**Comment by eglitise** [comment]
Done in #1177
