### ISSUE TITLE
Can't locate element in appium inspector

### ISSUE THREAD

**Issue by HanaIroha** [appium/appium-inspector#1092]
First of all, sorry for my bad English.
Some app recently updated and i can't locate the input element in appium inspector anymore. When i click on that element it just locate an android.widget.LinearLayout and nothing inside. Is there any fix for this? Thanks so much!

**Comment by KazuCocoa** [comment]
Do you have example screenshots and the full appium server log?

**Comment by HanaIroha** [comment]
> Do you have example screenshots and the full appium server log?

can you teach me how to get full appium server log, sir. I run appium through cmd. Can i just coppy everything in that cmd windown?

**Comment by KazuCocoa** [comment]
`--log` option could help https://appium.io/docs/en/2.0/cli/args/
