### ISSUE TITLE
feature request: Screenshots of elements

### ISSUE THREAD

**Issue by wazzeps** [appium/appium-inspector#1096]
### Current Behavior

We have the ability to [save screenshots of entire screens](https://github.com/appium/appium-inspector/pull/1021).

### Suggested Solution

It would be nice to be able to save screenshots of individual elements to later use in tests to compare them.

**Comment by itkhanz** [comment]
Adding to it, When we are in [Element Interaction Mode](https://appium.github.io/appium-inspector/latest/session-inspector/screenshot/#interaction-mode), `hovering over the screenshot will highlight any detected elements. Clicking on any highlighter will then select the corresponding element in the application source, and show its details in the selected element panel.`

In the element panel, we can see the element bounds, perhaps these coordinates can be used to capture the screenshot of selected element. Another approach would be to crop the full screenshot using these bounds to save element screenshot.

@eglitise  what do you think?

**Comment by eglitise** [comment]
@itkhanz I believe Appium already provides support for taking an element screenshot ([presumably based on the W3C standard command](https://w3c.github.io/webdriver/#take-element-screenshot)), so I don't think any of those workarounds would be necessary.

**Comment by itkhanz** [comment]
> @itkhanz I believe Appium already provides support for taking an element screenshot ([presumably based on the W3C standard command](https://w3c.github.io/webdriver/#take-element-screenshot)), so I don't think any of those workarounds would be necessary.

yes I am aware of this command but was not sure what is the barrier for its implementation within Appium Inspector and thought it was not possible to call this command from Appium Inspector. I am not myself very familiar with internals of Appium Inspector so unable to implement this feature.

**Comment by jlipps** [comment]
It would most naturally be a button in the found element interaction pane, I guess.
