### ISSUE TITLE
feature request: Swipe and touch actions could be done without switching methods

### ISSUE THREAD

**Issue by alvarolaserna** [appium/appium-inspector#1103]
### Current Behavior

Right now if you want to tap by coordinate or swipe by coordinates you have to switch between those two options. It works fine, but it is quite annoying to be switching between one another while interacting with the device

### Suggested Solution

It is possible to merge those two together, and use onMouseDown/onMouseUp instead of onClick from app/renderer/components/Inspector/Screenshot.js . With just a bit of refactoring the UI would be much more user friendly and the inspector can act as if it was a "remote device control software" while using mjpeg server.

### Additional Information

I would be willing to create a PR and work as developer in this project if you like this suggestion.

**Comment by jlipps** [comment]
I think this is a good idea. Now that we have the gestures editor for building up complex gestures one mouse click at a time, it makes sense for swipe/tap to work in a kind of remote control mode.

What do you think @eglitise?

PRs certainly welcome @alvarolaserna!

**Comment by alvarolaserna** [comment]
> I think this is a good idea. Now that we have the gestures editor for building up complex gestures one mouse click at a time, it makes sense for swipe/tap to work in a kind of remote control mode.
> 
> What do you think @eglitise?
> 
> PRs certainly welcome @alvarolaserna!

Awesome, I will create a PR then with the suggestions.

**Comment by alvarolaserna** [comment]
> I think this is a good idea. Now that we have the gestures editor for building up complex gestures one mouse click at a time, it makes sense for swipe/tap to work in a kind of remote control mode.
> 
> What do you think @eglitise?
> 
> PRs certainly welcome @alvarolaserna!

Could you add me to the project so that I can create a PR in the repo? I have it already ready to be pushed. Thanks!

**Comment by eglitise** [comment]
I'm a bit confused how the solution would work. I assume something like, tap would stay unchanged, but swipe functionality would change to a click-hold-drag-release action? If so, that does seem reasonable.
@alvarolaserna you can fork the repo and create a PR through that, it's how I always do it.

**Comment by alvarolaserna** [comment]
> I'm a bit confused how the solution would work. I assume something like, tap would stay unchanged, but swipe functionality would change to a click-hold-drag-release action? If so, that does seem reasonable. @alvarolaserna you can fork the repo and create a PR through that, it's how I always do it.

Yes, thats the idea `click-hold-drag-release`. Okay, I will do that and will create a PR then like that.

There is only one issue, translations will have to be changed, but not sure if I should also modify all the files for the translations in this PR, because the text will change from being "Tap by coordinates" to "Tap/Swipe by coordinates" so that's going to change a lot of files...

**Comment by eglitise** [comment]
Translation-wise only the English file needs to be changed. Strings for other languages are sourced from Crowdin, and there are automated scripts that will handle the synchronization.

**Comment by alvarolaserna** [comment]
> Translation-wise only the English file needs to be changed. Strings for other languages are sourced from Crowdin, and there are automated scripts that will handle the synchronization.

could you check my pull request? there I added the issue with the translations. #1104

**Comment by eglitise** [comment]
Implemented in #1104
