### ISSUE TITLE
feature request: add basic usage documentation

### ISSUE THREAD

**Issue by grndvl1** [appium/appium-inspector#1105]
### Current Behavior

No idea how to use the tool and what to add to start a session.  Documentation is lacking for someone who has no clue on programming.  Needs to be easy for QA people who may not be super technical

### Suggested Solution

Add documentation to creating a connection to see an emulator or a connected device

**Comment by jlipps** [comment]
@grndvl1 the tool is designed as an aid for developing Appium scripts, not as a replacement for writing/running them. You might get some mileage out of the explanations and quickstarts in the Appium docs, which could help fill in some gaps and get you running an Appium server successfully before using the Inspector.

Agree that there could be more comprehensive docs for the Inspector that don't assume existing knowledge, but that's not something at least I'll be able to do in the foreseeable future.

You could also take an Appium course, many of them introduce the inspector along the way.

**Comment by rushian** [comment]
I made a post that shows the installation from the cell phone emulator to the script running with robot framework, using appium server 2
https://upqa.wordpress.com/2023/09/29/tutorial-appium-robot-framework-2

**Comment by eglitise** [comment]
Documentation has now been added, and can be accessed at https://appium.github.io/appium-inspector/.
