### ISSUE TITLE
bug: app alert opens automatically

### ISSUE THREAD

**Issue by ankitjain082** [appium/appium-inspector#1108]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am getting a issue related to unexpected pop up on iPAD while inspecting element using Appium Inspector, mention the detail below

Scenario :- There is button All action item for record and when we click on it the a Pop up is open with details, also there is button to Add “New Action Item” so when we click on this button then new popup is open over the “All action item” pop up and when we click on background screen then “Alert” is open with 2 button i.e. Stay and Leave.

Manual Execution : We are able to verify this scenario without any issue.

Appium Inspector : When we redirect to Add new action item and refresh the page through Appium inspector then Alert is coming automatically, even we click on stay button and try identify locator through search option then pop up is coming automatically again. It’s blocker for us.
Initially I thought this issue related to appium inspector so we ran the script using eclipse but got the same issue however Alert is not coming automatically at the time of manual execution.

New Action Item is “XCUIElementTypeNavigationBar” element.

Please let me know if anyone having solution for the same.

### Expected Behavior

When clicks on "New Action Item" button to open the popup then alert should not open automatically. 

### Operating System

Mac

### Appium Inspector Version

2023.7.1

### Appium Version

1.22.3

**Comment by eglitise** [comment]
The Inspector does not do any sort of interaction with the app UI upon hitting refresh, so this sounds like an issue with the app.
* Try upgrading to Appium 2. Appium 1 is not supported anymore
* If the issue persists with Appium, 2, please add screenshots and the full Appium server log

**Comment by eglitise** [comment]
Closing due to no response
