### ISSUE TITLE
On creating a new JSON script and saving it, then viewing in saved capabilities Appium inspector crashes

### ISSUE THREAD

**Issue by MohsinSEQA** [appium/appium-inspector#1116]
On creating a new JSON script and saving it, then viewing in saved capabilities Appium inspector crashes

**Comment by jlipps** [comment]
Can you please provide a screen capture or more detailed repro please? What do you mean by "JSON script" for example? What JSON are you inputting? Etc.

**Comment by eglitise** [comment]
Closing due to no response
