### ISSUE TITLE
bug: Difference between accuracy of clickable options for webview between create session and attach session.

### ISSUE THREAD

**Issue by jerry7991** [appium/appium-inspector#1120]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. Create an Appium Session and switch to the Webview context.
2.  You can see in the screenshot image I can click the input box.
![Screenshot 2023-10-05 at 4 11 47 PM](https://github.com/appium/appium-inspector/assets/72571521/3fa19c27-80c3-4b01-a1fe-02b97dd71901)
3. Attach the session with the same capabilities instead of creating a session.
4. Switch to the Webview Context, the image should be accurate as in the create session scenario. Not able to click exactly on `mobile or email` input box.
![Screenshot 2023-10-05 at 4 13 59 PM](https://github.com/appium/appium-inspector/assets/72571521/adab32c5-72e7-4488-907f-87a37e5804ee)

### Expected Behavior

1. In the case of the attached session, the Screenshot should have the click option the same as in the case of the attached session.

### Operating System

Mac

### Appium Inspector Version

1.17

### Appium Version

1.17.0

**Comment by eglitise** [comment]
Closing due to no response
