### ISSUE TITLE
feature request: use Options for Python template

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium-inspector#1145]
### Current Behavior

https://github.com/appium/appium-inspector/blob/e32284f91548f30755971a4bf0680ff31554eafe/app/renderer/lib/client-frameworks/python.js#L34 uses old style

### Suggested Solution

Use new Options style https://github.com/appium/python-client?tab=readme-ov-file#usage

**Comment by eglitise** [comment]
The Options usage examples are driver-specific - would the common `AppiumOptions` still work?

**Comment by KazuCocoa** [comment]
Yes, it should work
