### ISSUE TITLE
"CouldNotConnect" when I tried to connect the appium server with appium inspector

### ISSUE THREAD

**Issue by iloveleejunghyun** [appium/appium-inspector#117]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ v] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
Hello, I tried to change appium inspector to a web based application which doesn't be included in the electron framework. When I tried click "startSession" button in the Chrome, it runs properly until the program tried to connect the appium server with Web2Driver. It got an err "CouldNotConnect".

The appium server showed like this:
    [HTTP] --> OPTIONS /wd/hub/session
    [HTTP] {}
    [HTTP] No route found for /wd/hub/session
    [HTTP] <-- OPTIONS /wd/hub/session 404 1 ms - 211
    [HTTP] 

The console of Chrome showed:
    Access to fetch at 'http://127.0.0.1:4723/wd/hub/session' from origin 'http://localhost:3000' has been blocked by CORS policy: 
    Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the 
    requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with 
    CORS disabled.
    POST http://127.0.0.1:4723/wd/hub/session net::ERR_FAILED

I'm sure that the same parameters were sent to the Web2Driver.remote(serverOpts, desiredCapabilities) function. While the electron based appium inspector could properly connect with the appium server,  the web based appium inspector didn't.
serverOpts:
    hostname = 127.0.0.1
    port = 4723
    protocol = http
    path = undefined
    connectionRetryCount = 0

desiredCapabilities:
    platformName = Android
    appium:ensureWebviewsHashPages = true
    appium:newCommandTimeout = 0
    appium:connectHardwareKeybord = true

The web2driver's version is 2.0.0.

## Environment

- I am running Appium Desktop version _<1.21.0>_.
- I am on (pick one):
    - [ ] Mac
    - [ v] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
This limitation is documented: https://github.com/appium/appium-inspector/#connecting-to-a-local-server-from-the-browser-inspector-cors
