### ISSUE TITLE
Could not connect to Appium server URL 'http://0.0.0.0:4723/'

### ISSUE THREAD

**Issue by GermanMedinaNeria** [appium/appium-inspector#1184]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Appium Inspector Throws this message
Could not connect to Appium server URL 'http://0.0.0.0:4723/'.
Appium Inspector was installed separated from the server

![imagen](https://github.com/appium/appium-inspector/assets/83734291/e68fbf63-0ad8-484c-a494-b80978c7f7c5)

### Expected Behavior

The overall procecedures suggest to click on INSPECTOR MOVED (MAGNIFYING GLASS BUTTON ON APPIUM SERVER) to switch to appium Inspector; but, this click direct to link

https://github.com/appium/appium-inspector

Again, Again , and after completed succeddfully installed Appium Inspector 

Any suggestion ..
Thanks in advanced !!

### Operating System

Windows

### Appium Inspector Version

App Version 2023.10.4

### Appium Version

Appium-Server-GUI-windows-1.22.3-4

### Further Information

  
![imagen](https://github.com/appium/appium-inspector/assets/83734291/5023c521-3884-4fd4-960d-69df13f0d433)
![imagen](https://github.com/appium/appium-inspector/assets/83734291/97517dc3-7d20-4c6b-8652-93cb4435197c)
![imagen](https://github.com/appium/appium-inspector/assets/83734291/aacaa200-813e-43ee-964a-a2e41ebf293b)

**Comment by eglitise** [comment]
Appium Server GUI is no longer supported - this is also clearly stated on its download page. Please use the command-line version of Appium for launching the server.
