### ISSUE TITLE
bug: appium desktop inspector not considering some elements on the left panel in Android

### ISSUE THREAD

**Issue by igorgiumellizup** [appium/appium-inspector#119]
## Appium or Appium Desktop?

Appium Desktop v 1.21.0
- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Hello. I noticed some inconsistencies with Appium Desktop Inspector on [this Android app](https://github.com/ZupIT/beagle-tests/tree/feat/android_tests_multiple_versions/appium/app-android). First of all, in Android Studio's inspector, the  FrameLayout element considers correctly all app content, ignoring status bar and footer:

> ![image](https://user-images.githubusercontent.com/73198010/131742547-cbf5b0b1-0398-44f8-b801-0e2e47bc5ecf.png)

However, moving to Appium's inspector gives me another result. The last elements are not included in the left panel preview, as shown here:

> ![image](https://user-images.githubusercontent.com/73198010/131742749-292ad2d8-b1d5-4a58-b542-df9ad5381992.png)

The excluded app elements are children of the main FrameLayout, but they are only selected in the left panel preview when we click exactly on them:

> ![image](https://user-images.githubusercontent.com/73198010/131742909-bb2a289f-7263-46b1-bbf7-1fa447d00f51.png)

## Environment

- I am running Appium Desktop version 1.21.0
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
@igorgiumellizup would you mind also sharing the full source xml of the app at this screen?

**Comment by igorgiumellizup** [comment]
> @igorgiumellizup would you mind also sharing the full source xml of the app at this screen?

Hello, I tried Appium Inspector and it gave me the same result:

> ![image](https://user-images.githubusercontent.com/73198010/131844067-f2c680fb-0f4d-47b1-a75a-f7410f7c5381.png)

The full source xml is here: 
[xml_source.txt](https://github.com/appium/appium-inspector/files/7098911/xml_source.txt)

If you want to reproduce it locally, do the following:
1 - Download the project https://github.com/ZupIT/beagle-tests
2 - Start the server located in folder bff-server
3 - Compile the android app in folder appium/app-android and start it
4 - On the app, type http://10.0.2.2:8080/image. You'll get the same screen
