### ISSUE TITLE
feature request: Duplicate Saved capability sets name

### ISSUE THREAD

**Issue by Dor-bl** [appium/appium-inspector#1196]
### Current Behavior

Currently when saving caps set with same name no message is shown
![image](https://github.com/appium/appium-inspector/assets/59066376/8ffa6a91-333d-4da2-b61c-172618d21fcb)

### Suggested Solution

I believe we should avoid having the same capability set names

**Comment by ath0mas** [comment]
@eglitise I looked into it yesterday but not used to React and antd.
So finding duplicate name and throw Error in async `saveSession` is pretty easy, but Modal is still closed. Any suggestions on how to report this error, inside form, live disabling OK button, or onOK click but with error dialog and not closing the Modal, ... ?

**Comment by sudharsan-selvaraj** [comment]
@eglitise i have created a PR with the changes. Looking forward for your review.
