### ISSUE TITLE
bug: <When I open the appium inspector, it crashes>

### ISSUE THREAD

**Issue by LWLJX** [appium/appium-inspector#1207]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I open the appium inspector, it crashes

### Expected Behavior

I can open and use the appium inspector normally

### Operating System

Mac

### Appium Inspector Version

2023.11.1

### Appium Version

2.0.1

### Further Information

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Appium Inspector [57896]
Path:                  /private/var/folders/*/Appium Inspector.app/Contents/MacOS/Appium Inspector
Identifier:            io.appium.inspector
Version:               2023.11.1 (2023.11.1.20231113.1)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-11-17 10:57:23.2889 +0800
OS Version:            macOS 13.3 (22E252)
Report Version:        12
Bridge OS Version:     7.4 (20P4252)
Anonymous UUID:        F8E3DB33-6F39-5F04-D609-514CC62B668A

Sleep/Wake UUID:       3988DCD3-CF2D-4C99-8AD3-1C0D6D4889CC

Time Awake Since Boot: 7100 seconds
Time Since Wake:       1574 seconds

System Integrity Protection: disabled

Crashed Thread:        7  Chrome_IOThread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [57896]

Thread 0:: CrBrowserMain Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	    0x7ff8179d05b2 mach_msg2_trap + 10
1   libsystem_kernel.dylib        	    0x7ff8179de8a8 mach_msg2_internal + 457
2   libsystem_kernel.dylib        	    0x7ff8179d75e4 mach_msg_overwrite + 692
3   libsystem_kernel.dylib        	    0x7ff8179d089a mach_msg + 19
4   CoreFoundation                	    0x7ff817aeb1af __CFRunLoopServiceMachPort + 145
5   CoreFoundation                	    0x7ff817ae9c30 __CFRunLoopRun + 1365
6   CoreFoundation                	    0x7ff817ae9071 CFRunLoopRunSpecific + 560
7   HIToolbox                     	    0x7ff821551fcd RunCurrentEventLoopInMode + 292
8   HIToolbox                     	    0x7ff821551dde ReceiveNextEventCommon + 657
9   HIToolbox                     	    0x7ff821551b38 _BlockUntilNextEventMatchingListInModeWithFilter + 64
10  AppKit                        	    0x7ff81ab7b7a0 _DPSNextEvent + 858
11  AppKit                        	    0x7ff81ab7a64a -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1214
12  AppKit                        	    0x7ff81ab6ccb8 -[NSApplication run] + 586
13  Electron Framework            	       0x1118f0536 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10148934
14  Electron Framework            	       0x1118ef18b v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10143899
15  Electron Framework            	       0x1118b925f v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 9922927
16  Electron Framework            	       0x11188b8bc v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 9736140
17  Electron Framework            	       0x11120e191 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 2930849
18  Electron Framework            	       0x11120f912 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 2936866
19  Electron Framework            	       0x11120b814 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 2920228
20  Electron Framework            	       0x11065fec7 electron::fuses::IsCookieEncryptionEnabled() + 5725207
21  Electron Framework            	       0x11065f9c8 electron::fuses::IsCookieEncryptionEnabled() + 5723928
22  Electron Framework            	       0x11065eb16 electron::fuses::IsCookieEncryptionEnabled() + 5720166
23  Electron Framework            	       0x11065ec02 electron::fuses::IsCookieEncryptionEnabled() + 5720402
24  Electron Framework            	       0x10ff35ae6 ElectronMain + 134
25  Appium Inspector              	       0x1001157e6 0x100114000 + 6118
26  dyld                          	    0x7ff8176b541f start + 1903

Thread 1:
0   libsystem_pthread.dylib       	    0x7ff817a0abb0 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	    0x7ff817a0abb0 start_wqthread + 0

Thread 3:: ThreadPoolServiceThread
0   libsystem_kernel.dylib        	    0x7ff8179d9e16 kevent64 + 10
1   Electron Framework            	       0x111902584 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10222740
2   Electron Framework            	       0x1118b925f v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 9922927
3   Electron Framework            	       0x11188b8bc v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 9736140
4   Electron Framework            	       0x1118d5c78 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10040200
5   Electron Framework            	       0x1118c313d v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 9963597
6   Electron Framework            	       0x1118d5e77 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10040711
7   Electron Framework            	       0x1118eab88 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10125976
8   libsystem_pthread.dylib       	    0x7ff817a0f1d3 _pthread_start + 125
9   libsystem_pthread.dylib       	    0x7ff817a0abd3 thread_start + 15

Thread 4:: ThreadPoolForegroundWorker
0   libsystem_kernel.dylib        	    0x7ff8179d05b2 mach_msg2_trap + 10
1   libsystem_kernel.dylib        	    0x7ff8179de72d mach_msg2_internal + 78
2   libsystem_kernel.dylib        	    0x7ff8179d75e4 mach_msg_overwrite + 692
3   libsystem_kernel.dylib        	    0x7ff8179d089a mach_msg + 19
4   Electron Framework            	       0x1118f3b67 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10162807
5   Electron Framework            	       0x1118cd14e v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10004574
6   Electron Framework            	       0x1118cd967 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10006647
7   Electron Framework            	       0x1118cd65d v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10005869
8   Electron Framework            	       0x1118eab88 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10125976
9   libsystem_pthread.dylib       	    0x7ff817a0f1d3 _pthread_start + 125
10  libsystem_pthread.dylib       	    0x7ff817a0abd3 thread_start + 15

Thread 5:: ThreadPoolBackgroundWorker
0   libsystem_kernel.dylib        	    0x7ff8179d05b2 mach_msg2_trap + 10
1   libsystem_kernel.dylib        	    0x7ff8179de72d mach_msg2_internal + 78
2   libsystem_kernel.dylib        	    0x7ff8179d75e4 mach_msg_overwrite + 692
3   libsystem_kernel.dylib        	    0x7ff8179d089a mach_msg + 19
4   Electron Framework            	       0x1118f3b67 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10162807
5   Electron Framework            	       0x1118cd14e v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10004574
6   Electron Framework            	       0x1118cd967 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10006647
7   Electron Framework            	       0x1118cd5fd v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10005773
8   Electron Framework            	       0x1118eab88 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10125976
9   libsystem_pthread.dylib       	    0x7ff817a0f1d3 _pthread_start + 125
10  libsystem_pthread.dylib       	    0x7ff817a0abd3 thread_start + 15

Thread 6:: ThreadPoolForegroundWorker
0   libsystem_kernel.dylib        	    0x7ff8179d05b2 mach_msg2_trap + 10
1   libsystem_kernel.dylib        	    0x7ff8179de72d mach_msg2_internal + 78
2   libsystem_kernel.dylib        	    0x7ff8179d75e4 mach_msg_overwrite + 692
3   libsystem_kernel.dylib        	    0x7ff8179d089a mach_msg + 19
4   Electron Framework            	       0x1118f3b67 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10162807
5   Electron Framework            	       0x1118cd14e v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10004574
6   Electron Framework            	       0x1118cd967 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10006647
7   Electron Framework            	       0x1118cd65d v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10005869
8   Electron Framework            	       0x1118eab88 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10125976
9   libsystem_pthread.dylib       	    0x7ff817a0f1d3 _pthread_start + 125
10  libsystem_pthread.dylib       	    0x7ff817a0abd3 thread_start + 15

Thread 7 Crashed:: Chrome_IOThread
0   Electron Framework            	       0x11186add9 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 9602281
1   Electron Framework            	       0x11435970a v8::internal::compiler::GetI32WasmCallDescriptorForSimd(v8::internal::Zone*, v8::internal::compiler::CallDescriptor*) + 2324538
2   Electron Framework            	       0x1112e3ab1 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 3805633
3   Electron Framework            	       0x114358963 v8::internal::compiler::GetI32WasmCallDescriptorForSimd(v8::internal::Zone*, v8::internal::compiler::CallDescriptor*) + 2321043
4   Electron Framework            	       0x11435a713 v8::internal::compiler::GetI32WasmCallDescriptorForSimd(v8::internal::Zone*, v8::internal::compiler::CallDescriptor*) + 2328643
5   Electron Framework            	       0x11435ace7 v8::internal::compiler::GetI32WasmCallDescriptorForSimd(v8::internal::Zone*, v8::internal::compiler::CallDescriptor*) + 2330135
6   Electron Framework            	       0x1111f5c93 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 2831267
7   Electron Framework            	       0x111bf9310 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 13330976
8   Electron Framework            	       0x111a47364 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 11553396
9   Electron Framework            	       0x111bfd8db v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 13348843
10  Electron Framework            	       0x111bfec96 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 13353894
11  Electron Framework            	       0x111a42c3a v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 11535178
12  Electron Framework            	       0x111a614bc v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 11660236
13  Electron Framework            	       0x11067e62b electron::fuses::IsCookieEncryptionEnabled() + 5849979
14  Electron Framework            	       0x11067da20 electron::fuses::IsCookieEncryptionEnabled() + 5846896
15  Electron Framework            	       0x1106789f8 electron::fuses::IsCookieEncryptionEnabled() + 5826376
16  Electron Framework            	       0x110670f91 electron::fuses::IsCookieEncryptionEnabled() + 5795041
17  Electron Framework            	       0x110683961 electron::fuses::IsCookieEncryptionEnabled() + 5871281
18  Electron Framework            	       0x111902756 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10223206
19  Electron Framework            	       0x1118b925f v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 9922927
20  Electron Framework            	       0x11188b8bc v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 9736140
21  Electron Framework            	       0x1118d5c78 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10040200
22  Electron Framework            	       0x1112105af v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 2940095
23  Electron Framework            	       0x1118d5e77 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10040711
24  Electron Framework            	       0x1118eab88 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10125976
25  libsystem_pthread.dylib       	    0x7ff817a0f1d3 _pthread_start + 125
26  libsystem_pthread.dylib       	    0x7ff817a0abd3 thread_start + 15

Thread 8:: MemoryInfra
0   libsystem_kernel.dylib        	    0x7ff8179d05b2 mach_msg2_trap + 10
1   libsystem_kernel.dylib        	    0x7ff8179de72d mach_msg2_internal + 78
2   libsystem_kernel.dylib        	    0x7ff8179d75e4 mach_msg_overwrite + 692
3   libsystem_kernel.dylib        	    0x7ff8179d089a mach_msg + 19
4   Electron Framework            	       0x1118f3b67 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10162807
5   Electron Framework            	       0x1118f39ee v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10162430
6   Electron Framework            	       0x11186f6a7 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 9620919
7   Electron Framework            	       0x1118b925f v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 9922927
8   Electron Framework            	       0x11188b8bc v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 9736140
9   Electron Framework            	       0x1118d5c78 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10040200
10  Electron Framework            	       0x1118d5e77 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10040711
11  Electron Framework            	       0x1118eab88 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10125976
12  libsystem_pthread.dylib       	    0x7ff817a0f1d3 _pthread_start + 125
13  libsystem_pthread.dylib       	    0x7ff817a0abd3 thread_start + 15

**Comment by LWLJX** [comment]
mac version: 13.3

**Comment by eglitise** [comment]
Thanks for the report. Seems to be the same crash as in #1127.

Does it crash right after opening?
Does it still crash after restarting your Mac?
Is your Mac using an Intel or Apple processor?

**Comment by LWLJX** [comment]
Every time I open it, it crashes；
my Mac using an Intel processor

**Comment by eglitise** [comment]
I wonder if the error is related to macOS 13.3 in particular. There is a similar crash report [on the Apple community](https://discussions.apple.com/thread/254818733) as well.
Would it be possible for you to update to a newer macOS version (e.g. 13.6) and then try again?
