### ISSUE TITLE
feature request: Add searched element to popup window

### ISSUE THREAD

**Issue by Dor-bl** [appium/appium-inspector#1241]
### Current Behavior

Currently when searching for an element, in case the element is not found the user see a general message saying: "Could not find any elements"

### Suggested Solution

the popup should include the element we searched for as well.
i.e. Could not find any elements matching the below criteria: {Element selector value}"
<img width="818" alt="image" src="https://github.com/appium/appium-inspector/assets/59066376/a80d6410-9478-46e8-ad38-215100e2d808">

### Additional Information

This will help users when they are working closely with dev teams to add unique identifiers to their app, so they can show them what is missing for what value of selector used.

**Comment by VineethG-Protean** [comment]
![image](https://github.com/appium/appium-inspector/assets/161560711/79cd94b4-a136-473b-b381-8b95f1fdbd86)
Something like this?

**Comment by Dor-bl** [comment]
I believe so.
Maybe also include the selector type

**Comment by sudharsan-selvaraj** [comment]
@Dor-bl How about this one? Any thoughts? If it looks good, i shall raise a PR with the changes.

<img width="668" alt="Screenshot 2024-06-04 at 7 00 51 AM" src="https://github.com/appium/appium-inspector/assets/20136913/7684784b-dce3-4e7d-af3a-47350461a4dc">

**Comment by Dor-bl** [comment]
LGTM 🍻

**Comment by sudharsan-selvaraj** [comment]
@Dor-bl Cool. Opened a PR with the changes.
