### ISSUE TITLE
bug: <Not able to capture individual elements on the home screen of iOS17 device with xCode 15 and appium2>

### ISSUE THREAD

**Issue by himanshupal121** [appium/appium-inspector#1244]
### Is this an issue specifically with Appium Inspector?

- [ ] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Not able to capture the individual elements on the iOS 17 device ( using iPhone 14) using appium inspector.
It always capture/ highlight the entire home screen as one element.
I am using below configurations-
Appium2( appium inspector -2023.11.1)
XCode 15
Please see the below snapshot
![Screenshot 2023-12-11 134155](https://github.com/appium/appium-inspector/assets/118197160/1c32a553-c6db-480f-99c2-70db05dac294)

Also, appium inspector was able to highlight the elements we navigate through app source. Please see the below snapshot:
![HighlightSearch](https://github.com/appium/appium-inspector/assets/118197160/a3e5c9ec-cb46-4ae7-9eb0-283b1f896df0)

Attaching the source file: 
[app-source-2023-12-11T08_20_19.txt](https://github.com/appium/appium-inspector/files/13634279/app-source-2023-12-11T08_20_19.txt)
 

### Expected Behavior

We should be able to capture individual elements as well on the home screen.

### Operating System

Mac

### Appium Inspector Version

23.11.1

### Appium Version

2.0.1

**Comment by eglitise** [comment]
If you can highlight them through the app source, then there really isn't a problem here. Hovering over the screenshot means hovering over multiple elements, so there is no clear answer on which one should be highlighted. In this case the highlighted element is likely one of the root elements.
However, you can work around this problem using the toggle switch above the screenshot. It will show all the individual highlighters, which will then allow you to select your desired element.

**Comment by himanshupal121** [comment]
@eglitise ,  thanks for your response. 
The toggle switch can be helpful in case of appium inspector. But the application on which I am working using the appium api under the hood. I have seen the same behavior in my app as well i.e, on hovering it shows the entire screen as one single element.
Toggle switch work around can't be of much help in my scenario. How can I deal with this situation ?

**Comment by jlipps** [comment]
If users can't differentiate between elements in your app, then that's an app problem, not an appium problem.

**Comment by himanshupal121** [comment]
@jlipps - sorry if you miss understood my query, Appium inspector itself is not able to tap on any of the application available on the home screen as it always considers it as one single element. If its able to penetrate the home screen, it will be able to tap on any app, which is not happening. But one we open any app its able to locate the elements properly. Please see the below snap:

![otherappsnap](https://github.com/appium/appium-inspector/assets/118197160/fe995657-98b7-414c-ac9d-ec52ab7de703)

Appium inspector is indefinitely slow to load the device itself, which makes me unable to locate the elements on the home screen of the device.

**Comment by eglitise** [comment]
@himanshupal121 your original screenshots clearly show several `XCUIElementTypeIcon` elements - are those not the application icons?
Personally I have not had any issue with finding and tapping on application icons on the iOS home screen; they are all present in the app source, which means they are also accessible to Appium. Whether I can hover over them in the application screenshot is entirely irrelevant at that point.
