### ISSUE TITLE
feature request: Include `hittable` attribute for iOS inspection

### ISSUE THREAD

**Issue by Dor-bl** [appium/appium-inspector#1265]
### Current Behavior

Currently, when inspecting elements on iOS we can't see the attribute value of `hittable`: 
https://developer.apple.com/documentation/xctest/xcuielement/1500561-hittable
<img width="499" alt="image" src="https://github.com/appium/appium-inspector/assets/59066376/dbdb1ea3-b3ca-4ae2-9d36-7188b25e6a3a">

### Suggested Solution

Since this is an important attribute, in my opinion, we should consider adding it to the attributes list on the inspector.

**Comment by eglitise** [comment]
The Inspector does not define its own list of attributes that are visible in the GUI; it just shows whatever the driver returns. Does your driver return `hittable` when you query the available element attributes through your automation code?

**Comment by eglitise** [comment]
Closing as not an issue
