### ISSUE TITLE
feature request: click refresh button and screen shows very slowly

### ISSUE THREAD

**Issue by SayWeeeXuZhongyuan** [appium/appium-inspector#1293]
### Current Behavior

env:
    iOS: 15.8
    device: iPhone 7 Plus
    Appium-inspector: 2023.12.2
    macOS: Venture 13.3.1
click "refresh" button, and the screen shows very slowly and almost need wait for 40 seconds each time
![image](https://github.com/appium/appium-inspector/assets/150754251/f9416f94-c17f-4b21-82ed-e11863933c6e)

### Suggested Solution

show faster when click "refresh"  button

**Comment by eglitise** [comment]
Could you please provide the Appium log, and ideally also the source XML of the application screen that takes too long to load, by retrieving it using Appium itself (_not_ the Inspector)? I ask this because the Inspector may apply additional parsing to the source XML, so I would like to check if this is the case here.

**Comment by SayWeeeXuZhongyuan** [comment]
> Could you please provide the Appium log, and ideally also the source XML of the application screen that takes too long to load, by retrieving it using Appium itself (_not_ the Inspector)? I ask this because the Inspector may apply additional parsing to the source XML, so I would like to check if this is the case here.

[appium.log](https://github.com/appium/appium-inspector/files/13936834/appium.log)

[app-source-2024-01-15T08_51_16.122Z.xml.zip](https://github.com/appium/appium-inspector/files/13936865/app-source-2024-01-15T08_51_16.122Z.xml.zip)

@eglitise  this is appium log and source xml, please check at your convenient, thank you!

**Comment by eglitise** [comment]
@SayWeeeXuZhongyuan thanks. Are you sure the log file is correct? I don't see any requests there for taking the app screenshot. Maybe this is the log for https://github.com/appium/appium/issues/19651 ?

**Comment by KazuCocoa** [comment]
Yes, it looks like the attached logs are not for this issue

**Comment by SayWeeeXuZhongyuan** [comment]
> @SayWeeeXuZhongyuan thanks. Are you sure the log file is correct? I don't see any requests there for taking the app screenshot. Maybe this is the log for [appium/appium#19651](https://github.com/appium/appium/issues/19651) ?

sorry, this is appium log, but I don't know where can get Appium-inspector log, which directory please?

**Comment by eglitise** [comment]
The log should be from the Appium server that you are connecting to when creating the Inspector session. The Inspector itself does not have a separate logfile.

**Comment by SayWeeeXuZhongyuan** [comment]
![image](https://github.com/appium/appium-inspector/assets/150754251/4bc61afb-8c5e-4896-bb5b-9bd80482d994)
when create session, it failed this time, but for most of time, it works well.
and why connect 8100 port , the connection was refused?
thanks!

**Comment by eglitise** [comment]
Please do not mix different issues. This one does not seem to be related to the Inspector, but rather xcodebuild. Try to ensure that WDA is fully built and running before attempting to use the Inspector.

**Comment by eglitise** [comment]
Closing due to no response
