### ISSUE TITLE
Error when running inspector by attaching an existing session ID

### ISSUE THREAD

**Issue by allen-fang** [appium/appium-inspector#131]
In `Session.js`, if the inspector is started with an `attachSessId`, the caps are set to `null` (`newSession(null, attachSessId)(dispatch, getState);`). This causes an error when launching the inspector.

**Comment by jlipps** [comment]
hi @allen-fang can you share any more information about what the error is? I do see that caps are set to null in this case but I don't see an obvious connection to an error

**Comment by eglitise** [comment]
Closing due to no response. I also can't reproduce this on 2023.4.3.
