### ISSUE TITLE
Appium inspector doesn't see running sessions

### ISSUE THREAD

**Issue by wasder** [appium/appium-inspector#132]
## Appium or Appium Desktop?

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I can't attach to a running session in Appium Inspector (1st screen), though I can in Appium Desktop (2nd screen)
![image](https://user-images.githubusercontent.com/2205216/132680230-df049356-e562-4954-89cd-b6710004a9d7.png)
![image](https://user-images.githubusercontent.com/2205216/132680247-169f1163-5b2a-4f72-8675-7a9809966896.png)

## Environment

- I am running Appium Desktop version Appium-Inspector-mac-2021.8.5.dmg
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
What do you see in the browser console?

**Comment by wasder** [comment]
Console in appium inspector? How do I open it?

**Comment by jlipps** [comment]
right click anywhere, click "Inspect", then choose the console log instead of the source tree.

**Comment by wasder** [comment]
Seems like the problem with non-standart port
`GET http://127.0.0.1:6000/wd/hub/sessions net::ERR_UNSAFE_PORT`
![image](https://user-images.githubusercontent.com/2205216/133079031-8e223970-0dad-4540-a9aa-fcb4dc4e6a7c.png)

**Comment by jlipps** [comment]
Looks like this is a Chrome feature: https://superuser.com/questions/188058/which-ports-are-considered-unsafe-by-chrome. I'm not sure we can do anything about it. Can you run on a port that's not a reserved port for Chrome?

**Comment by wasder** [comment]
Sure, thank you!
