### ISSUE TITLE
feature request: Upgrade electron

### ISSUE THREAD

**Issue by NyCodeGHG** [appium/appium-inspector#1321]
### Current Behavior

appium-inspector currently uses electon 13, which reached it's End of Life more than 2 years ago.

### Suggested Solution

Upgrade electron

### Additional Information

https://endoflife.date/electron

**Comment by eglitise** [comment]
Thanks. Yes, this is a known issue, though unfortunately not easy to resolve. Most likely a prerequisite step would be to upgrade the Parcel build tool (whose version is also outdated).
