### ISSUE TITLE
XPath as a locator coming in recorded script

### ISSUE THREAD

**Issue by bawarim** [appium/appium-inspector#1342]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When recording operation using appium inspector recorder then only XPath is coming as a locator strategy. 
![image](https://github.com/appium/appium-inspector/assets/46487726/cbd29b0d-3449-4410-86de-95acdd598617)

### Expected Behavior

There should be an option of having different locator to be configured while recording. And same should be generated in recorded script. 

### Operating System

Windows

### Appium Inspector Version

2023.12.2

**Comment by bawarim** [comment]
The elements has unique IDs available, but sill it uses the XPath. 

![image](https://github.com/appium/appium-inspector/assets/46487726/b1895175-fd74-4c8a-b490-0fe5028f4279)

![image](https://github.com/appium/appium-inspector/assets/46487726/3a9a81a6-a631-4235-911b-a4711bd657be)

**Comment by eglitise** [comment]
Assuming this is an Android hybrid app, this makes sense, as the `id` locator strategy [is not part of the W3C spec](https://www.w3.org/TR/webdriver2/#locator-strategies). Chrome runs in W3C mode by default, so it will only work with the available W3C strategies, of which the only one here is `xpath`.
However, you can disable Chrome's W3C mode, and the recorder will then be able to use other strategies. You can do this by starting the Inspector session with the `"appium:chromeOptions": {"w3c": false}` capability.
Check the [UiAutomator2 web context capabilities](https://github.com/appium/appium-uiautomator2-driver#web-context) for more info.
