### ISSUE TITLE
Could not find a driver for automationName ‘Windows’`

### ISSUE THREAD

**Issue by wmortume** [appium/appium-inspector#1355]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have the latest `appium-windows-driver` and `WinAppDriver` drivers installed but when I try to use the inspector it’s complaining that it can’t find `appium-windows-driver` which is located in the `../.appium/..` directory.
![image](https://github.com/appium/appium-inspector/assets/36937310/dbc5e608-ed52-42e8-8048-f99a2d6c75df)

### Expected Behavior

I expect the inspector to detect the driver and start a session so I can inspect windows elements.

### Operating System

Windows

### Appium Inspector Version

2024.2.2

### Appium Version

2.5.1

**Comment by KazuCocoa** [comment]
Could you include the beginning of the appium server log as well?

e.g. from "Welcome to...."
```
[Appium] Welcome to Appium v2.0.0 (REV 552db40622bb7a82d9c6d67d2d6bcf3694b47e30)
[Appium] Attempting to load driver fake...
[debug] [Appium] Requiring driver at /Users/kazu/GitHub/appium/packages/fake-driver
[Appium] Attempting to load driver windows...
```

**Comment by wmortume** [comment]
> Could you include the beginning of the appium server log as well?
> 
> e.g. from "Welcome to...."
> 
> ```
> [Appium] Welcome to Appium v2.0.0 (REV 552db40622bb7a82d9c6d67d2d6bcf3694b47e30)
> [Appium] Attempting to load driver fake...
> [debug] [Appium] Requiring driver at /Users/kazu/GitHub/appium/packages/fake-driver
> [Appium] Attempting to load driver windows...
> ```
@KazuCocoa Here's the whole log.
![image](https://github.com/appium/appium-inspector/assets/36937310/14f28db0-7783-4f9d-948f-1b440a3aa956)

**Comment by KazuCocoa** [comment]
it looks like the appium windows driver installation failed. Maybe node build was wrong.
What version of node/npm does the env have?
If not, nodejs v20, 18, 16 (LTS), could you try them out?

**Comment by wmortume** [comment]
@KazuCocoa After downgrading from v21.6.2 to v20.11.1 I get a different error telling me winappdriver server is not listening within timeout.
![image](https://github.com/appium/appium-inspector/assets/36937310/78c51ac8-873f-4eb7-ade0-21d771ab518d)

**Comment by eglitise** [comment]
Are you perhaps setting `Remote Path` to `/wd/hub`? (the error message is blocking the fields)
In your screenshots you are launching the server without any arguments, so `Remote Path` can be left as the default `/`. Same with the port.

**Comment by wmortume** [comment]
@eglitise The remote path was left blank. Removing the port still gives me the same error message.

**Comment by eglitise** [comment]
Does the same error appear if you start the session without the Inspector (using another Appium client)? If not, can you please share the full Appium server log?

**Comment by KazuCocoa** [comment]
I haven't checked well yet but wondered if it was the winappdriver's something

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-windows-driver/issues/206
Perhaps the inspector does not fully well for appium-windows-driver, but full log may help to see a few.

**Comment by eglitise** [comment]
Closing due to no response
