### ISSUE TITLE
bug: improve translateRecursively performance

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium-inspector#1359]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The result is ok, but I saw `translateRecursively`'s slowness when a page source had huge nodes.
For example, a webview context recursively calculated `translateRecursively` 3653 times, then it took `76786` ms entirely.

I roughly calculated this time with:

```
  const startAt = new Date();
  console.log(`=======> translateRecursively`);
  try {
    return firstChild ? translateRecursively(firstChild) : {};
  } finally {
    const endAt = new Date();
    //     =======> done: 3653. duration 76786 ms
    console.log(`=======> done: ${recursiveCount}. duration ${endAt - startAt} ms`);
```

I wondered if we could improve this performance.

I have modified `getSourceUpdate` forcefully with https://gist.github.com/KazuCocoa/07b427765da523e2a488329ba36639d3

### Expected Behavior

not sure if we could improve this performance for now. I haven't dug into this possibility anything yet. I have just detected the long-taken method.

### Operating System

Mac

### Appium Inspector Version

2024.2.2

**Comment by eglitise** [comment]
I think one way to improve this would be to only calculate the optimal xpath/class chain/predicate upon selecting an element. It's really not necessary to do this for every single node alongside loading the page source. Calculated locators can then be cached until the page source changes.

**Comment by KazuCocoa** [comment]
Actually, after replacing out `getOptimalXPath` with a dummy value, the time changed to 20ms with the same source, so mostly `getOptimalXPath` caused that. `getOptimalClassChain` and `getOptimalPredicateString` did not decrease the time so much. Some ms only.

**Comment by eglitise** [comment]
Great, at least we know the main culprit :) for consistency it would still be best to extract all 3 methods.

**Comment by eglitise** [comment]
Yeah I agree, moving all these calculations to the selected element panel would be the best solution.
Those PRs likely did affect the calculation time, but the resulting xpaths are indeed a lot better, so the logic should still be kept.

**Comment by jlipps** [comment]
One thought: if we can detect that the size of the DOM is very large, we could choose not to run the xpath suggestion logic, and replace it with a button in the element panel that says "(Slowly) Find Optimal XPath". Then the user would click it and get a spinner until the xpath is determined. At least this would keep the UX snappy until the point where they actually want to get the optimal xpath.

**Comment by eglitise** [comment]
IMO the best way would be to start calculating the optimal paths as soon as the user selects the element, but show a spinner for each until they are ready. Once any are done, they are stored/cached so that recalculation (at least for the strategies where the search finished) is not repeated if the element is deselected and then reselected. Optimal path storage/cache is then cleared upon page source reload.

**Comment by jlipps** [comment]
Yeah, I like this idea! So long as the calculation doesn't block the UI thread so people can still do stuff with the app, and I guess if another element is selected we can cancel the first process. Maybe this is a case for webworkers?
