### ISSUE TITLE
[Session] Failed to get Session ID when start the session

### ISSUE THREAD

**Issue by Hira073** [appium/appium-inspector#1364]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When start session in appium inspector then mobile app launched successfully but appium inspector failed to load and send error message Session ID is unknow

### Expected Behavior

when start a session it should launch the app in inspector and mobile together 

{
  "appium:platformName": "Android",
  "appium:platformVersion": "12",
  "appium:automationName": "UIAutomator2",
  "appium:deviceName": "RZCT417S6SX",
  "appium:appPackage": "com.wakecap.app.test",
  "appium:appActivity": "com.wakecap.app.MainActivity"
}

Appium server is 2.5
and appium inspector is also latest

### Operating System

Windows

### Appium Inspector Version

2024.2.2

### Appium Version

v2.5.1

**Comment by eglitise** [comment]
Coincidentally I also had this exact problem yesterday. I don't think it's an inspector-specific isue and it would probably also reappear when starting a session through any other client. What I could suggest is to try restarting both the device and the Appium server, then start the session again - this fixed the problem for me.

**Comment by Hira073** [comment]
@eglitise thanks alot it solved

**Comment by Sahil29Rana** [comment]
> Coincidentally I also had this exact problem yesterday. I don't think it's an inspector-specific isue and it would probably also reappear when starting a session through any other client. What I could suggest is to try restarting both the device and the Appium server, then start the session again - this fixed the problem for me.

Still facing this one??
