### ISSUE TITLE
FEATURE-REQUEST : copy to clipboard by click on a value

### ISSUE THREAD

**Issue by StephanB75** [appium/appium-inspector#137]
- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The feature request

it would be nice if a single click on a value of an element (i.e. ID) does automatically copy it to clipboard.
Currently i have to select it manually and copy it. Sometimes linebreaks are incuded which makes it more "complicated" to use the copied value.

## Environment

- I am running Appium Inspector version<2021.8.5>
- I am on (pick one):
    - [X] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
Yeah here's what I think we can do here: for the selector and attribute values, we can hyperlink (with no decoration) the value, and clicking it will copy to the clipboard.
