### ISSUE TITLE
Unable to open application on mac

### ISSUE THREAD

**Issue by hcx1002** [appium/appium-inspector#1372]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="372" alt="截屏2024-02-29 13 57 23" src="https://github.com/appium/appium-inspector/assets/72607620/fd2869b6-4337-4037-8a4f-80f6e1894b45">

### Expected Behavior

My mac os version is on 14.2.1. The latest version of the installation package is used.

### Operating System

Mac

### Appium Inspector Version

2024.2.2

### Appium Version

2.5.1

**Comment by KazuCocoa** [comment]
It is expected as the macOS's security feature. Please check https://appium.github.io/appium-inspector/latest/quickstart/installation/#macos
