### ISSUE TITLE
FEATURE-REQUEST : starting of appium server from inspector

### ISSUE THREAD

**Issue by StephanB75** [appium/appium-inspector#138]
- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The feature request :

Would it be possible to add a section where i can add the path to appium and the start params, so that the inspector
can automatically start the server when i create a session?
(also closing the server when stopping the session).

This would raise the useability, because currently i have to start the server manually infront and quitting it afterwards.

## Environment

- I am running Appium Inspector version _<2021.8.5>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
This is not something that's a goal of the inspector. It assumes you have a running Appium server. Anything more would make it impossible for the Inspector to be a web app (and this is one of the reasons we broke out the Inspector from Appium Desktop)
