### ISSUE TITLE
bug: Inspector does not open. 

### ISSUE THREAD

**Issue by Sheilinha99** [appium/appium-inspector#1406]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I click the inspector button it opens this page here: https://github.com/appium/appium-inspector
<img width="469" alt="erroApium2" src="https://github.com/appium/appium-inspector/assets/165932711/220cc852-340c-4b92-afef-407f06bfdda0">

### Expected Behavior

Does not open the expected screen.,It should open the spector screen below
<img width="431" alt="ErroAppium" src="https://github.com/appium/appium-inspector/assets/165932711/8d3c3369-a482-4f55-8ea9-77321125aa0c">

### Operating System

Windows

### Appium Inspector Version

v1.22.3 is the same number?

### Appium Version

v1.22.3

### Further Information

no plus information

**Comment by eglitise** [comment]
You are using Appium Desktop, which is a different program. Appium Desktop is deprecated and should be replaced with Appium Inspector. [Please download the Inspector from this repo](https://github.com/appium/appium-inspector/releases).

**Comment by eglitise** [comment]
Also, Appium Inspector requires a separate install of the Appium server. [Check the Appium documentation for how to do that](http://appium.io/docs/en/latest/quickstart/).
