### ISSUE TITLE
Report do instalador windows 

### ISSUE THREAD

**Issue by hiagoagil** [appium/appium-inspector#1411]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Report

### Expected Behavior

Report

### Operating System

Windows

### Appium Inspector Version

Report

### Further Information

Report

**Comment by eglitise** [comment]
I'm sorry, but I do not understand what your issue is - please provide the requested information (in English).

**Comment by eglitise** [comment]
Closing due to no response
