### ISSUE TITLE
bug: When pressing Refresh Source & Screenshot real device becomes unresponsive and times out.

### ISSUE THREAD

**Issue by dcboycm** [appium/appium-inspector#1433]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Navigate to the specific screen of my mobile application; tap on the Refresh Source & Screenshot to browser the mobile DOM hierarchy; Appium Inspector hangs and the real device becomes unresponsive. 

### Expected Behavior

Navigate to the specific screen of my mobile application; tap on the Refresh Source & Screenshot to browser the mobile DOM hierarchy; Appium Inspector returns DOM hierarchy of elements. 

### Operating System

Mac

### Appium Inspector Version

2024.3.4

### Appium Version

2.4.1

**Comment by jlipps** [comment]
Please attach your appium server log

**Comment by eglitise** [comment]
Closing due to no response

**Comment by dcboycm** [comment]
@jlipps Sorry for the delay, I've attached the logs for this issue.

[Appium logs.txt](https://github.com/appium/appium-inspector/files/15177538/Appium.logs.txt)

**Comment by eglitise** [comment]
This log is for Appium 1.21, which is no longer supported, and is not fully compatible with iOS 16 either. Please use Appium 2.

**Comment by dcboycm** [comment]
Sorry about that. I'm using the latest version of Appium Inspector, is there a capability for that needs to be set to use Appium 2 versus Appium 1.21?

**Comment by dcboycm** [comment]
I think I figured it out; Attached updated logs while experiencing the same issue.
[Appium logs (1).txt](https://github.com/appium/appium-inspector/files/15189013/Appium.logs.1.txt)

**Comment by eglitise** [comment]
Sorry, but this log is still for Appium 1, as shown by one of the first lines there:
```
[Appium] Appium v1.21.0 creating new XCUITestDriver (v3.44.0) session
```
Assuming that you are using BrowserStack, [please refer to their documentation](https://www.browserstack.com/docs/app-automate/appium/set-up-tests/set-appium-version) on specifying the Appium version.

**Comment by dcboycm** [comment]
Ok, got the capability set correctly and have attached the logs.

`[AppiumDriver@d2e7] [AppiumDriver@d2e7] Appium v2.0.1 creating new XCUITestDriver (v4.32.23) session`

[Appium logs (2).txt](https://github.com/appium/appium-inspector/files/15193795/Appium.logs.2.txt)

**Comment by eglitise** [comment]
This seems to be the same error as in https://github.com/appium/appium/issues/19544. Try the solutions mentioned there: setting `"appium:settings[pageSourceExcludedAttributes]": ["visible"]` or decreasing `"appium:settings[snapshotMaxDepth]"`.

**Comment by eglitise** [comment]
It sounds like that specific screen just has a lot of elements. You can perhaps try to also add the `accessible` attribute to the value of `pageSourceExcludedAttributes`.
