### ISSUE TITLE
installation issue: on mac Apple M1 chip

### ISSUE THREAD

**Issue by kajal-zuddl** [appium/appium-inspector#1473]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Both brew installation command 'brew install --cask appium-inspector' and github release link [link](https://github.com/appium/appium-inspector/releases) downloading [arm 64.dmg ](https://github.com/appium/appium-inspector/releases/download/v2024.3.4/Appium-Inspector-2024.3.4-mac-arm64.dmg) gives installation error

<img width="315" alt="Screenshot 2024-05-27 at 10 47 22 PM" src="https://github.com/appium/appium-inspector/assets/132268212/0196fead-c012-4949-bc7f-24558738b17f">

### Expected Behavior

Installation was working correctly a week ago as mentioned in the appium-inspector installation website.

### Operating System

Mac

### Appium Inspector Version

3.4

**Comment by eglitise** [comment]
This is expected. [Please refer to the installation instructions in the Inspector documentation](https://appium.github.io/appium-inspector/latest/quickstart/installation/#macos).
Also we do not officially publish the Homebrew version (or at least, I'm not aware of it being officially supported).

**Comment by Paritosh-Saini** [comment]
I am facing the similar issue.

Earlier the pop-up used to have an option to open the software. But as you can see in the screenshot, currently there is no such option.

I have installed the software via package.

But the issue still persists.
