### ISSUE TITLE
[ERROR] Failed to create session. 

### ISSUE THREAD

**Issue by yavgel** [appium/appium-inspector#148]
`Failed to create session. The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource`

Tested on Mac OS

![image](https://user-images.githubusercontent.com/8123409/134785064-9a2996ad-17de-462c-acc9-1582f3011f8a.png)

```
[HTTP] Waiting until the server is closed
[HTTP] Received server close event
[Appium] Welcome to Appium v1.22.0
[Appium] Non-default server args:
[Appium]   relaxedSecurityEnabled: true
[Appium]   allowInsecure: {
[Appium]   }
[Appium]   denyInsecure: {
[Appium]   }
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /session
[HTTP] {"capabilities":{"alwaysMatch":{"platformName":"Android","appium:platformVersion":"11.0","appium:deviceName":"Pixel 3a XL API 30","appium:automationName":"UiAutomator2","appium:app":"https://unity.rekki.com/android-apks/rekki-demo-release-20.29.31.apk","appium:autoGrantPermissions":true,"appium:avd":"Pixel_3a_XL_API_30","appium:fullReset":true,"appium:enforceAppInstall":true,"appium:ensureWebviewsHavePages":true,"appium:newCommandTimeout":0,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"Android","appium:platformVersion":"11.0","appium:deviceName":"Pixel 3a XL API 30","appium:automationName":"UiAutomator2","appium:app":"https://unity.rekki.com/android-apks/rekki-demo-release-20.29.31.apk","appium:autoGrantPermissions":true,"appium:avd":"Pixel_3a_XL_API_30","appium:fullReset":true,"appium:enforceAppInstall":true,"appium:ensureWebviewsHavePages":true,"appium:newCommandTimeout":0,"appium:connectHardwareKeyboard":true}}
[HTTP] No route found for /session
[HTTP] <-- POST /session 404 6 ms - 211
[HTTP] 
```

![image](https://user-images.githubusercontent.com/8123409/134785080-8454127a-b7e4-4e87-9773-2699040a9e95.png)

![image](https://user-images.githubusercontent.com/8123409/134785094-cc610ae2-9ecb-482c-80a1-6e117b992850.png)

**Comment by KazuCocoa** [comment]
Please try to add `/wd/hub` as Remote Path.
Appium 2.0 will drop the prefix, so this inspector also expects `/` (no-/wd/hub) by default by design for now.

**Comment by yavgel** [comment]
> Please try to add `/wd/hub` as Remote Path.
> Appium 2.0 will drop the prefix, so this inspector also expects `/` (no-/wd/hub) by default by design for now.

thank you a lot - it helped!

**Comment by terik461** [comment]
New issue after adding `/wd/hub`

Error
Failed to create session. An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20222ms.
