### ISSUE TITLE
 Accessibility overlay automatically turned off while appium inspector running

### ISSUE THREAD

**Issue by Aijar-Groups** [appium/appium-inspector#1481]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 Accessibility overlay automatically turned off while appium inspector running

### Expected Behavior

Not turned off

### Operating System

Linux

### Appium Inspector Version

Appium-Inspector-2024.3.4-linux-x86_64.AppImage

### Appium Version

2.5.4

### Further Information

 Accessibility overlay automatically turned off while appium inspector running

**Comment by eglitise** [comment]
Please provide more information on what is your platform under test and what do you mean by 'accessibility overlay'.

**Comment by eglitise** [comment]
Closing due to no response
