### ISSUE TITLE
Popup are visible but main screen is showing as blank. 

### ISSUE THREAD

**Issue by aishwaryasangale** [appium/appium-inspector#1482]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have launch the Android in emulator in the latest version of the Android stuido. Start the Appium Inspctor GUI, then the Andorid emulator successfully launched with the application, start the appium inspector but in appium inspector I am able to see only the permission pop up, I have aaccepted the popup in android studio, and refresh again it in appium inspector but screen is blank in appium inspector and visible in andorid studio. I have try with the 
1.  [Appium-Inspector-2024.3.4-win-x64.exe](https://github.com/appium/appium-inspector/releases/download/v2024.3.4/Appium-Inspector-2024.3.4-win-x64.exe)
2. [Appium-Inspector-windows-2024.3.1-x64.exe](https://github.com/appium/appium-inspector/releases/download/v2024.3.1/Appium-Inspector-windows-2024.3.1-x64.exe)

### Expected Behavior

When we will refreshed the scrren in android studio emualtor it should get reflet in the appium inspector.

PFA

![image](https://github.com/appium/appium-inspector/assets/84981445/2a575150-9667-4865-a07a-e3c2fd4fe9d7)

### Operating System

Windows

### Appium Inspector Version

https://github.com/appium/appium-inspector/releases/download/v2024.3.4/Appium-Inspector-2024.3.4-win-x64.exe

### Appium Version

2.5.4

### Further Information

![img_20240531](https://github.com/appium/appium-inspector/assets/84981445/a1b170e5-c902-4983-ae92-a0e1cdf5f5db)

**Comment by jlipps** [comment]
this is not an inspector issue. it's either an app security feature, or an appium driver issue, but most likely it's an app security feature. the inspector merely displays the screenshot that android sends.
