### ISSUE TITLE
appium inspector with error

### ISSUE THREAD

**Issue by lucascoln** [appium/appium-inspector#149]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

![image](https://user-images.githubusercontent.com/38281976/134802461-a0693b23-e42a-4fc4-80e8-a9dc86e2f790.png)

cannot access to my phone . 
my setting is :
![image](https://user-images.githubusercontent.com/38281976/134802489-579d02e4-2f42-482b-bd1e-d6e5831a2670.png)

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
The error was the app under test failed to generate screenshot.
Please try out the latest appium version as the target appium server.
