### ISSUE TITLE
 sessions 304 error

### ISSUE THREAD

**Issue by Shaz-1997** [appium/appium-inspector#1509]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Screenshot (1051)](https://github.com/appium/appium-inspector/assets/121928888/65866546-5b73-409a-9bee-5282fd1f3221)

### Expected Behavior

Appium inspector should load the app and show all the design elements 

### Operating System

Windows

### Appium Inspector Version

2024.3.4

### Appium Version

2.10.3

**Comment by eglitise** [comment]
Please provide your Appium server log.
Also, if your title is referring to HTTP 304 requests in the Appium log, that behavior is expected, and it is done to prevent the session from timing out.

**Comment by Shaz-1997** [comment]
hi,
Sorry for not viewing your mail
