### ISSUE TITLE
bug: <Android: Real device> initial screen is freeze 

### ISSUE THREAD

**Issue by umerhamdan10** [appium/appium-inspector#1528]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I launch the app on my actual smartphone, the first screen freezes (Screenshot attached)

It functions perfectly on a virtual device.

Appium version: 2.11.1

App Version: 2024.6.1
Electron: 13.6.9
Node.js: 14.16.0 

<img width="1085" alt="Screenshot 2024-07-09 at 12 37 58" src="https://github.com/appium/appium-inspector/assets/43927146/791e042e-a683-409b-97b4-f66697ca626b">

<img width="1085" alt="Screenshot 2024-07-09 at 12 46 08" src="https://github.com/appium/appium-inspector/assets/43927146/8276d8d0-252a-4d07-a05f-eca7c0276acb">

### Expected Behavior

Inspect elements and see the screen 

### Operating System

Mac

### Appium Inspector Version

2024.6.1

### Appium Version

2.11.1

### Further Information

I deleted the appium-inspector and installed the new version 

Try all these steps but didn't solve the issue 
https://github.com/appium/appium-inspector/issues/1386

**Comment by eglitise** [comment]
Please check if the solution described in #1364 helps here.

**Comment by eglitise** [comment]
Closing due to no response
