### ISSUE TITLE
Not able to change the default web application URL

### ISSUE THREAD

**Issue by Bapugit** [appium/appium-inspector#1547]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,
I am using Appium inspector to capture locators for Mobile Web and naive Apps, I have selected Sauce as a Cloud providers.
I was able to test and capture the locators for Native Mobile App without any issues.
However, I am having issues with Mobile Web application.

I used below JSON representation for desired capabilities, I could start the session with my Sauce credentials ,  after that a default web application([appium.io/docs](http://appium.io/docs)) is being popped-up in screen shot panel, but I am not able to change/edit that URL  to my desired web application. Pls help me how can I change that to my desired application and capture the locators. I followed the guidelines as per your documentation. 
I contacted the Sauce Labs, they suspected that it would be an issue from Appium Inspector.

{
"appium:automationName": "UiAutomator2",
"appium:platformVersion": "12.0",
"platformName": "Android",
"browserName": "Chrome",
"appium:deviceName": "Android GoogleAPI Emulator",
"sauce:options": {
"build": "Test",
"name": "WDIOTest",
"appiumVersion": "2.0.0"
}
}

https://github.com/user-attachments/assets/29ad46ea-8bcf-4cd5-8400-21964a24f8a9

### Expected Behavior

I should able to edit/change the default application URL for the web application

### Operating System

Windows

### Appium Inspector Version

2023.10.4

### Appium Version

"appiumVersion": "2.0.0"

**Comment by KazuCocoa** [comment]
What URL did you send via the command tabs? https://appium.github.io/appium-inspector/latest/session-inspector/commands/ Asking it in https://discuss.appium.io/ might also help.

**Comment by eglitise** [comment]
The behavior in the Session Inspector is expected - since the app is opened in web context, only webview contents are shown, therefore native app components (such as the URL bar) will not be accessible.
You may try switching the context at the top of the application to native, if possible - that will expose the URL bar elements.

**Comment by Bapugit** [comment]
Thanks a lot, changing to the NATIVE_APP on top helped me to change the default URL.
