### ISSUE TITLE
Unable to start appium session using Appium nspector even after upgrading or installing appium v2.5

### ISSUE THREAD

**Issue by itsVimalkumaR** [appium/appium-inspector#1569]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Screenshot 2024-07-25 163047](https://github.com/user-attachments/assets/f85b3508-725c-407c-b502-587735b63ab8)

### Expected Behavior

![Screenshot 2024-07-25 163047](https://github.com/user-attachments/assets/f85b3508-725c-407c-b502-587735b63ab8) in the popup should not be appeared.

### Operating System

Windows

### Appium Inspector Version

2024.6.1

**Comment by eglitise** [comment]
Have you followed the instructions shown in the error message?

**Comment by itsVimalkumaR** [comment]
> Have you followed the instructions shown in the error message?

Yes, I followed the instructions.

**Comment by eglitise** [comment]
I would appreciate if you could also share your findings (such as the start of the Appium server log and screenshots of your Inspector server details). You can clearly see in the error message that the URL `https://http://127.0.0.1:4723/wd/hub` is not valid, meaning there is an issue in your configuration.
Refer to the [Quickstart documentation](https://appium.github.io/appium-inspector/latest/quickstart/starting-a-session/#adding-server-details) to properly configure your session details.

**Comment by eglitise** [comment]
Closing due to no response
