### ISSUE TITLE
Mac Version does not run - Apple Cannot Check for Malicious Software

### ISSUE THREAD

**Issue by trogdor259** [appium/appium-inspector#1570]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I download the dmg file for Mac OS, I tried to launch the inspector. It gives the error in the screenshot.
![Screenshot 2024-07-25 at 10 03 34 AM](https://github.com/user-attachments/assets/d2da020e-26f6-46bf-aac9-36365886cca6)

### Expected Behavior

The application should run on the Apple with no issues.

### Operating System

Mac

### Appium Inspector Version

2024.6.1

### Appium Version

2.11.2

**Comment by eglitise** [comment]
[Please refer to the installation instructions](https://appium.github.io/appium-inspector/latest/quickstart/installation/#macos).
