### ISSUE TITLE
bug: unable to get all locators which in list - ios in appium inspector

### ISSUE THREAD

**Issue by happyusha** [appium/appium-inspector#1573]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when fetching locators which is in list , only showing few - in _ios

### Expected Behavior

when fetching locators which is in list ,should showing all - in _ios

### Operating System

Mac

### Appium Inspector Version

1.22.3

### Appium Version

2.5.1

**Comment by eglitise** [comment]
> Appium Inspector Version 1.22.3

You are using Appium Server GUI, which is no longer supported. Please download Appium Inspector from this repository.
If the issue is still reproducible with Appium Inspector, please provide more details to explain what you mean.
