### ISSUE TITLE
Inspector screen got freeze and Showing searchin mode

### ISSUE THREAD

**Issue by ersinha** [appium/appium-inspector#1576]
![Screenshot 2024-07-30 172912](https://github.com/user-attachments/assets/b6697fc2-a90b-4da4-8f8c-0bb20121e4a9)

When I Start Session my app gets lounch in emulator but my Inspector don't show current page of app. Showing me searching and App Source section it is throwing gather initial app source. 
After refreasing also it like same.

**Comment by Ghost-2k** [comment]
im getting white screen

**Comment by eglitise** [comment]
Please share your full Appium server log.

**Comment by eglitise** [comment]
Closing due to no response

**Comment by ersinha** [comment]
after some time this issue is resolved

**Comment by ethanlizeedker** [comment]
nana
