### ISSUE TITLE
feature request: Improved functionality on the "Attach to Session" tab

### ISSUE THREAD

**Issue by fleytman** [appium/appium-inspector#1585]
### Current Behavior

1. The latest session will be at the end of the session list.
2. It's hard to tell one session from another unless you look at the server logs to see the Session ID.
3. Sessions might not show up in the dropdown list unless you click the refresh icon.

<img width="1061" alt="image" src="https://github.com/user-attachments/assets/067402df-6149-4b6f-8d1e-979a7631f5b5">

### Suggested Solution

1. Show the last session at the top of the list and make it pre-selected
2. Add a timestamp to sessions
3. When you click on the list, automatically press refresh

**Comment by eglitise** [comment]
I'm not fully sure about pre-selecting the latest session in case there are multiple available sessions, but the other points all definitely make sense!

**Comment by fleytman** [comment]
I would be very happy if it would be possible to put the last session at least at the top of the list. Why it's important in my case, when I debug autotests, I intentionally disable deleting the appium session so that I can connect in the appium inspector and see why the locator wasn't found. Because of this, I can have more than 10 requests in the list and each time I have to scroll down the list.
I agree that it may not be convenient for everyone. Perhaps sorting and whether to include pre-select should be done as an option.

**Comment by eglitise** [comment]
To clarify - I definitely agree with sorting sessions by most recent, just not auto-selecting the most recent one, if more than one was found 🙂
