### ISSUE TITLE
feature request: add full text search

### ISSUE THREAD

**Issue by fleytman** [appium/appium-inspector#1593]
### Current Behavior

The button with a magnifier allows you to search using a locator. However, it may not work well in the following situations:
1. If the app screen has been updated and the locators have been changed.
2. If you need to quickly check for a specific word on the page.

### Suggested Solution

Add full text search with hotkey command+f

**Comment by eglitise** [comment]
If you mean searching through the app source, there is already a request for this in #1004. There's even a PR in #1494 🙂

**Comment by fleytman** [comment]
What is presented in the PR will solve my problem.
