### ISSUE TITLE
无法启动会话，报各种各样的错误

### ISSUE THREAD

**Issue by Estralle-12** [appium/appium-inspector#1594]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

报错：Failed to create session. An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\android-sdk_r24.4.1-window\\platform-tools\\adb.exe -P 5037 -s lvhqskyx9lrsuggu shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' exited with code 255'; Command output: Exception occurred while executing 'delete': java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2329) at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1473) at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1465) at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1436) at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:528) at android.content.ContentProvider.call(ContentProvider.java:2533) at android.content.ContentProvider$Transport.call(ContentProvider.java:530) at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:408) at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:282) at

### Expected Behavior

直接启动成功

### Operating System

Windows

### Appium Inspector Version

2024.6.1

### Appium Version

1.22.2

### Further Information

疯狂报错 无法解决

**Comment by eglitise** [comment]
> Appium Version 1.22.2

We do not support Appium 1 anymore. Please upgrade to Appium 2.

> Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

Please refer to https://github.com/appium/appium/issues/13802

Closing as this is not an Inspector-specific issue, for an unsupported Appium version.
