### ISSUE TITLE
bug: Unable to access elements in Appium

### ISSUE THREAD

**Issue by Skisperd** [appium/appium-inspector#1603]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Captura de Tela 2024-08-13 às 11 50 42](https://github.com/user-attachments/assets/a98244ca-dc7c-49b4-8fb5-c6069b7e5308)
I'm facing an issue where, despite all components being updated and configured correctly, I can't access specific elements when testing with Appium. Even after following the recommendations and configuring the environment as per the official guide, the issue persists.

### Expected Behavior

Elements should be accessible and interactable without errors during automated testing execution.

### Operating System

Mac

### Appium Inspector Version

24.6.1

### Appium Version

2.11.3

### Further Information

➜  ~ appium-doctor
WARN AppiumDoctor [Deprecated] Please use appium-doctor installed with "npm install @appium/doctor --location=global"
info AppiumDoctor Appium Doctor v.1.16.2
info AppiumDoctor ### Diagnostic for necessary dependencies starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  ✔ Node version is 20.16.0
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ Xcode Command Line Tools are installed in: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ DevToolsSecurity is enabled.
info AppiumDoctor  ✔ The Authorization DB is set up properly.
info AppiumDoctor  ✔ Carthage was found at: /usr/local/bin/carthage. Installed version is: 0.39.1
info AppiumDoctor  ✔ HOME is set to: /Users/tfdias
info AppiumDoctor  ✔ ANDROID_HOME is set to: /Users/tfdias/Library/Android/sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: /Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home

**Comment by eglitise** [comment]
You have already created an issue about this in https://github.com/appium/appium/issues/20454. Closing this as duplicate.
