### ISSUE TITLE
bug: saved capabilities set not working (not saving)

### ISSUE THREAD

**Issue by igorgiumellizup** [appium/appium-inspector#161]
## Appium or Appium Desktop?

Appium Inspector

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

This is a very annoying one. Open Appium Inspector, create a profile of capabilities and save it under "Saved  Capabilities Set 2". Now, I'm facing two types of problems:

1 - When editing the values of a profile, saving, and launching by pressing "Start Session", the values are not saved 
> <img width="1280" alt="problem1" src="https://user-images.githubusercontent.com/73198010/134906107-586ec89f-f0d6-4e1b-baad-283b16dd45bb.png">

2 - When creating two profiles, the values of the second profile always reverts to the values of the first one, no matter how many times we edit and save it.

The only way around is to erased all profiles and create a new one with the correct values. 

## Environment

- I am running Appium Desktop version:
> App Version: 2021.8.5
> Electron: 13.2.2
> Node.js: 14.16.0
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
> 1 - When editing the values of a profile, saving, and launching by pressing "Start Session", the values are not saved

Start Session doesn't save the set, only "Save" does that. Do you think "Start Session" should also save?

> 2 - When creating two profiles, the values of the second profile always reverts to the values of the first one, no matter how many times we edit and save it.

I'm not sure what this means. Are you saying that if you select Set #2, then click "Start Session", it actually uses Set #1?

**Comment by igorgiumellizup** [comment]
> Start Session doesn't save the set, only "Save" does that. Do you think "Start Session" should also save?

```When editing the values of a profile, saving, and launching...```

I edit and save it. Then I start the session.

> I'm not sure what this means. Are you saying that if you select Set #2, then click "Start Session", it actually uses Set #1?

Exactly! 

I can make a video reproducing the problem if you can't simulate it.

**Comment by jlipps** [comment]
OK, strange. will look into it.

**Comment by Jiyvn** [comment]
@igorgiumellizup @jlipps I am able to save capability set in `DesiredCapatibility` tab using `Save As`. Maybe it's a workaround until next release.

**Comment by MHMH370** [comment]
The lasted version can't saved capability sets on macos.  I tried appium-desktop and appium imspector version.
what can i do sonthing to fix?

**Comment by emaan-c** [comment]
Hey @igorgiumellizup, I'm trying to reproduce this bug so I could potentially fix it. And I was wondering if you can give me more info about it. Everything seems to be working properly on my end, I think you may just need to use the latest version of Appium Desktop/Inspector!

**Comment by igorgiumellizup** [comment]
@emaan-c and all
I couldn't reproduce the problema in version v2022.5.4 so I'm closing this issue.
