### ISSUE TITLE
Issue in Connecting to Perfecto Cloud

### ISSUE THREAD

**Issue by sanjeevavreddy** [appium/appium-inspector#164]
Windows inspector throws below error while connecting to Perfecto Cloud.

Not able to add any prefix to "securityToken" capability, because its built in to the inspector.

Can you please do the changes.

Error
Invalid or unsupported WebDriver capabilities found ("securityToken"). Ensure to only use valid W3C WebDriver capabilities (see https://w3c.github.io/webdriver/#capabilities).If you run your tests on a remote vendor, like Sauce Labs or BrowserStack, make sure that you put them into vendor specific capabilities, e.g. "sauce:options" or "browserstack:options". Please reach out to to your vendor support team if you have further question
![Screenshot (1)](https://user-images.githubusercontent.com/31237363/135212700-57694d8e-c07e-43dc-8018-be16c17f84c4.png)
s.

**Comment by KazuCocoa** [comment]
We've already mentioned them in https://github.com/appium/appium-inspector/issues/128
Please wait for their action. (You may be able to ask their support team)

Close due to the duplication.
