### ISSUE TITLE
feature request: Fullscreen and Element Screenshot Capturing

### ISSUE THREAD

**Issue by itkhanz** [appium/appium-inspector#1643]
### Current Behavior

At the moment, only way to capture screenshot via Appium is to run an automated test script via Appium client bindings that captures the screenshot at given point of execution. This approach is quite cumbersome which requires user to first write an automated test script to navigate through all the screens to arrive at point where screenshot capture is needed.  

I am therefore suggesting to add a feature that allows user to capture a screenshot of selected WebElement within Appium Inspector as well as having the option to capture full screen screenshot. 

This approach makes it easier for users to capture screenshots of app for visual testing baseline reference images.

### Suggested Solution

- In the selected element window, add an option to take screenshot of this WebElement.
- In commands section, add an option to take a full screen screenshot of screen that is currently opened.

After screenshot is captured, user should be prompted with a window to provide a path to save screenshot and image format.

Default image format and save path can also be setup so user can then retrieve the captured screenshots from that path.

**Comment by eglitise** [comment]
Unless I am misunderstanding here, the Inspector already allows saving a screenshot of the current screen. [Please refer to the documentation.](https://appium.github.io/appium-inspector/latest/session-inspector/screenshot/#download-screenshot)
Regarding element screenshots, this has already been requested in #1096.

**Comment by itkhanz** [comment]
Thank you for pointing to the docs. You are right, saving full screen screenshot is already available, and the element screenshot is already requested in other issue.
