### ISSUE TITLE
Default remote path should be "/wd/hub"

### ISSUE THREAD

**Issue by NirBY** [appium/appium-inspector#165]
## Appium Inspector V2021.9.1
Inspector's default server is appium V1
Therefore, Default remote path should be "/wd/hub"

Works fine with old inspector.
**Getting Error**:

> Error
>Failed to create session. The requested resource could not be found, or a request was received using an HTTP method that is >not supported by the mapped resource

After running it also seems that prefix "appium:" is added to each property, added print screen.

Also try changing server IP from 127.0.0.1 to 0.0.0.0. no luck there.

## The problem

**Server Side Log**:

> [HTTP] No route found for /session
> [HTTP] <-- POST /session 404 1 ms - 211
> [HTTP] 
> [HTTP] --> GET /sessions
> [HTTP] {}
> [HTTP] No route found for /sessions
> [HTTP] <-- GET /sessions 404 2 ms - 211
> [HTTP] 
> [HTTP] --> GET /sessions
> [HTTP] {}
> [HTTP] No route found for /sessions
> [HTTP] <-- GET /sessions 404 1 ms - 211
> [HTTP] 
> [HTTP] --> POST /session
> [HTTP] {"capabilities":{"alwaysMatch":{"platformName":"iOS","appium:platformVersion":"14.8","appium:deviceName":"iPhone8","appium:app":"_adHoc.ipa","appium:udid":"2cc4db","appium:automationName":"XCUITest","appium:xcodeOrgId":"<>","appium:xcodeSigningId":"iPhone Developer","appium:showIOSLog":false,"appium:showXcodeLog":false,"appium:updatedWDABundleId":"<>","appium:useNewWDA":false,"appium:wdaStartupRetries":3,"appium:wdaStartupRetryInterval":2000,"appium:maxTypingFrequency":100,"appium:CommandTimeout":0,"appium:newCommandTimeout":"300","appium:noReset":true,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"iOS","appium:platformVersion":"14.8","appium:deviceName":"iPhone8","appium:app":"_adHoc.ipa","appium:udid":"2cc4d","appium:automationName":"XCUITest","appium:xcodeOrgId":"<>",...
> [HTTP] No route found for /session
> [HTTP] <-- POST /session 404 1 ms - 211
> [HTTP] 

![Desired Capabilities - before run](https://user-images.githubusercontent.com/9214815/135408834-b39a8955-96d3-41a7-8977-b059d356117b.png)

![Desired Capabilities - after run](https://user-images.githubusercontent.com/9214815/135409543-bc72e729-497b-48a2-a44c-3c90ecad788e.png)

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _V2021.9.1_.
- I am on (pick one):
    - [V] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by DmitryMishtal** [comment]
I belive remote path should be /wd/hub

**Comment by jlipps** [comment]
@DmitryMishtal is probably right. You need to use the appropriate path for the Appium server you're running. Appium 1.x servers use /wd/hub as the path, and Appium 2.x servers use / as the path. The Inspector has been updated to work with Appium 2.x by default.

**Comment by PaulosSouza** [comment]
@DmitryMishtal is right. I got that error as well, so, when I changed my path to /wd/hub, appium server recognized the inspector

**Comment by NirBY** [comment]
Yes, it works. Change issue subject.

**Comment by jlipps** [comment]
We're going to keep the default path at "/" since Appium 2.0 is almost released and this Inspector is designed primarily to be Appium 2 compatible.

**Comment by TomasHubelbauer** [comment]
I just ran into this. Could this issue be pinned until Appium 2.0 is released?

**Comment by dinesha87** [comment]
I'm also getting the same issue. I tried with both app and desktop version of new appium inspector but no luck. Every-time i'm getting timeout error.

**Environments**

- macOS-11.6

- appium server GUI - v1.22.0

- appium inspector - 2021.9.2

![image](https://user-images.githubusercontent.com/56371935/140863111-beb4f4bc-99d9-4481-bdfd-56c3acf24a5e.png)


![image](https://user-images.githubusercontent.com/56371935/140863639-7ad71d00-91d7-44a0-8c9b-c0e88485a82d.png)

[appium-server-logs.txt](https://github.com/appium/appium-inspector/files/7502025/appium-server-logs.txt)

**Comment by jlipps** [comment]
@dinesha87 that is a different error and not related to the inspector. please open a new issue at appium/appium with your full details if you want us to take a look.

**Comment by bwomsm1** [comment]
Hi @jlipps , 
I am getting the error when running Appium from CLI.
(I try testing Appium 2.0.0)

How I can resolve this from cli?

**Comment by tking16** [comment]
This doesn't work for me, bear in mind I've added `-pa /wd/hub --allow-cors` when running appium. I get the original error weather I put `/wd/hub` in the remote path or not.

**Comment by Akj13213** [comment]
<img width="946" alt="image" src="https://user-images.githubusercontent.com/109217918/207873734-ea078cd5-2a48-43bd-8100-4b603d5e16d1.png">

Remote path should be : "/wd/hub" as mention in above image.

**Comment by goldbock** [comment]
> <img alt="image" width="946" src="https://user-images.githubusercontent.com/109217918/207873734-ea078cd5-2a48-43bd-8100-4b603d5e16d1.png">
> 
> Remote path should be : "/wd/hub" as mention in above image.

@Akj13213 You have "/wd/hub/" in the image not "/wd/hub"

**Comment by Akj13213** [comment]
@goldbock I'm able to start a session without "/". It doesn't matter whether you use it or not, "/" after  "hub" or "4723".
![image](https://user-images.githubusercontent.com/109217918/213207000-25ee9b63-84a6-4e46-ba2e-bb64401e6da3.png)

**Comment by clin045** [comment]
I am on Appium 2.1.3 and the default path still does not work:
```
[Appium] Welcome to Appium v2.1.3 (REV 251a098fbf1c02ca95f53b4806e5b6da8d5e4a80)
[Appium] Attempting to load driver uiautomator2...
[debug] [Appium] Requiring driver at /Users/clin/.appium/node_modules/appium-uiautomator2-driver
[Appium] Appium REST http interface listener started on http://0.0.0.0:4723
[Appium] You can provide the following URLs in your client code to connect to this server:
[Appium] 	http://127.0.0.1:4723/ (only accessible from the same host)
[Appium] 	http://192.168.0.101:4723/
[Appium] 	http://10.2.0.2:4723/
[Appium] Available drivers:
[Appium]   - uiautomator2@2.29.11 (automationName 'UiAutomator2')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
[HTTP] --> OPTIONS /session
[HTTP] {}
[debug] [HTTP] No route found for /session
[HTTP] <-- OPTIONS /session 404 19 ms - 211
```

**Comment by eglitise** [comment]
@clin045 are you seeing this log when attempting to use the Inspector? I just tried it, and the first request it sends is `GET /sessions`, not `OPTIONS /session`. Not actually sure where you're getting the `OPTIONS` method from, because the Inspector does not use it anywhere.

**Comment by clin045** [comment]
@eglitise I am using the hosted app at https://inspector.appiumpro.com/. It seems like on launch it sends an `OPTIONS` request to `/sessions`, and on subsequent "Start Session" button click is sends an `OPTIONS` request to `/session`.

**Comment by eglitise** [comment]
@clin045 in order to get the web version to connect to your Appium server, you need to start the server with the `--allow-cors` flag. Check [the README](https://github.com/appium/appium-inspector#connecting-to-a-local-server-from-the-browser-inspector-cors) for more details.
