### ISSUE TITLE
打不开，且很容易退出

### ISSUE THREAD

**Issue by heliqingshidasheng** [appium/appium-inspector#1657]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

一直打不开，而且很容易退出

### Expected Behavior

一直打不开，而且很容易退出
![微信图片_20240905165414](https://github.com/user-attachments/assets/75de868b-52c5-450d-a120-f04294aacd33)

### Operating System

Windows

### Appium Inspector Version

Appium-Inspector-2024.8.2-win-x64.exe

### Appium Version

Appium-Server-GUI-windows-1.22.3-4.exe

**Comment by eglitise** [comment]
> Appium-Server-GUI-windows-1.22.3-4.exe

Appium Server GUI is no longer supported. Please upgrade to Appium 2.
If your problem is still reproducible with Appium 2, please create a new issue and provide details in English.

**Comment by heliqingshidasheng** [comment]
> Appium 2

![微信图片_20240905175753](https://github.com/user-attachments/assets/9a9321e4-120f-4762-b397-5dbc1aa54fef)

Appium 2 下载下来是这样 不是windows 程序码? 改怎么使用？

**Comment by eglitise** [comment]
Appium is a command-line tool downloaded through `npm`. [Please refer to the documentation for an overview and setup instructions](http://appium.io/docs/zh/latest/intro/).
