### ISSUE TITLE
Element in screenshot is not highlighted when clicking the element id in search locator modal

### ISSUE THREAD

**Issue by 0x22ff0c** [appium/appium-inspector#167]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

The exact element in the screenshot shown beside the App Source tab is not highlighted when I click the element id  in the search modal.

Set capabilities:
{
  "appium:automationName": "UIAutomator2",
  "platformName": "Android",
  "appium:platformVersion": "11",
  "appium:deviceName": "Emulator 11"
}

Kindly see screenshot:
![image](https://user-images.githubusercontent.com/45059789/135740345-0a3a5646-c818-4684-abef-861c0b23cf80.png)

## Environment

- I am running Appium Desktop version _2021.9.1.
- I am on (pick one):
    - [x] Mac
    - [x] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
this has been fixed in the latest release
