### ISSUE TITLE
Sending multiple locators in recorded actions

### ISSUE THREAD

**Issue by ayushanurag2002** [appium/appium-inspector#1674]
### Current Behavior

Currently only one optimal locator is being sent for recording.

### Suggested Solution

Can we send multiple locators in the recorded actions object so that if one locator fails another locator can be used for the same script.

**Comment by eglitise** [comment]
I think this should be left up to the user. The Inspector's recorded code tries to use a locator strategy that is _expected_ to be the fastest, but it will not always be the most applicable one for that scenario. Providing multiple locators in the recorded code to mitigate this would only unnecessarily increase the size of the code, as well as decrease performance and readability.
Remember that recorded code is always only a starting point, regardless of the automation framework. If one locator fails, you should check the element details in the Inspector, see if any of the other recommended locators work better, and adjust them if necessary.
