### ISSUE TITLE
bug: Screenshot Panel coordinates are incorrect when session is started in landscape mode or the inspector window is resized

### ISSUE THREAD

**Issue by mateusz-plociennik** [appium/appium-inspector#1680]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- When the session is started with the **DUT in landscape mode**, after the screenshot is displayed, the **screenshot panel is automatically resized**, causing the coordinates of elements to become inaccurate. The highlights and interaction areas no longer align with their actual positions on the device screen. This misalignment happens immediately after the panel is resized automatically.
- In **portrait mode**, the issue does not occur until the **Appium Inspector window** is manually resized. After resizing, the coordinates in the screenshot panel become incorrect, making UI element inspection and interaction unreliable.
- Using the **Refresh Source & Screenshot** button resolves the issue in both modes. After manually refreshing, the coordinates are corrected and interactions work as expected.

<img width="1512" alt="Screenshot 2024-09-13 at 07 03 57" src="https://github.com/user-attachments/assets/768a47bb-ad4a-433d-8c93-9fce30744b6f">

### Expected Behavior

- The screenshot panel should display accurate coordinates for UI elements, regardless of whether the DUT is in portrait or landscape mode. Any window resizing (manual or automatic) should not break the coordinate mapping.
- Whether the screenshot is in portrait or landscape, and regardless of any resizing events, the coordinates and highlighted areas should always match the actual positions on the device screen without needing to manually refresh.

### Operating System

Mac

### Appium Inspector Version

2024.8.2

### Appium Version

2.11.3

**Comment by eglitise** [comment]
Thanks for the report, I've also encountered this many times and agree that it should be fixed.
