### ISSUE TITLE
bug: Mouse movements not captured during screenshot refresh in Coordinates Mode

### ISSUE THREAD

**Issue by mateusz-plociennik** [appium/appium-inspector#1682]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In 'Coordinates Mode' of the 'Screenshot Panel', if the application is busy fetching a new screenshot or page source, mouse movements are not captured. If you move the mouse while the screenshot is being refreshed, the click action will be executed based on the old mouse position when the screenshot is finally ready.

https://github.com/user-attachments/assets/8b3f25cd-7818-417f-a4dd-4e033085a8d3

### Expected Behavior

Mouse movements should be accurately captured and reflected in 'Coordinates Mode', even if the application is fetching a new screenshot or page source. The tap or swipe action should correspond to the current mouse position at the time of the action, not the old position.

### Operating System

Mac

### Appium Inspector Version

2024.8.2

### Appium Version

2.11.3

**Comment by eglitise** [comment]
This is probably caused by the spinner element being layered over the screenshot and intercepting onMouseOver events. Likely the same reason why clicking twice at the same position without moving the mouse throws an error.
