### ISSUE TITLE
bug: Screenshot Panel is stealing mouse events from Commands Tab popups

### ISSUE THREAD

**Issue by mateusz-plociennik** [appium/appium-inspector#1691]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When Commands Tab popup is displayed over Screenshot Panel in Coordinates Mode, it is impossible to interact with the popup.
<img width="444" alt="Screenshot 2024-09-17 at 10 58 38" src="https://github.com/user-attachments/assets/c7a4adfb-9caf-4c42-a81f-3a5a52262f30">

### Expected Behavior

I can interact with the Commands Tab popups without any issues.

### Operating System

Mac

### Appium Inspector Version

2024.8.2

### Appium Version

2.11.3

**Comment by mateusz-plociennik** [comment]
I think you need to select Coordinates Mode, see the attached video:
https://github.com/user-attachments/assets/9fa4f822-e313-4dcb-a8d0-b62948262659

**Comment by eglitise** [comment]
Thanks, I can reproduce this after selecting Coordinates Mode.
