### ISSUE TITLE
bug: AppiumInspector doesn't load view for my app on real device

### ISSUE THREAD

**Issue by ps1logi** [appium/appium-inspector#1705]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Start Appium
Run Appium Inspector
App open on real mobile
Observation: I m observing Spinner on appium inspector 

### Expected Behavior

Appium as to load the app screen 

### Operating System

Mac

### Appium Inspector Version

2024.3.4

### Appium Version

2.11.2

### Further Information

[appium-logs_20-Sep-24.txt](https://github.com/user-attachments/files/17073268/appium-logs_20-Sep-24.txt)
<img width="1108" alt="Screenshot 2024-09-20 at 3 17 49 PM" src="https://github.com/user-attachments/assets/78932b37-a2ab-4ddb-a5fc-08e48b3c701f">

**Comment by ps1logi** [comment]
This issue is seen when I run with iOS. I don't see this issue in Android.

**Comment by eglitise** [comment]
> [671033fc][WD Proxy] Got response with status 200: {"value":{"build":{"upgradedAt":"1712051062392","version":"8.3.1","time":"Sep 20 2024 15:02:35","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"},"os":{"testmanagerdVersion":65535,"name":"iOS","sdkVersion":"18.0","version":"17.7"},"device":"iphone","ios":{"ip":"172.23.231.101"},"message":"WebDriverAgent is ready to accept commands","state":"success","ready":true},"sessionId":null}

I can see that you are using iOS 18 with WDA 8.3.1. Please upgrade to XCUITest driver 7.24.15 or later and rebuild WDA. [Refer to the XCUITest documentation for compatibility](https://appium.github.io/appium-xcuitest-driver/latest/installation/requirements/#xcodeios-version-support).
In general it is good practice to check if new major iOS versions require updating your XCUITest/WDA versions.
