### ISSUE TITLE
bug: Appium inspector obtaining wrong Class Chain for UI element

### ISSUE THREAD

**Issue by amoghu02** [appium/appium-inspector#1710]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When an element having a label common with another element is selected using the `Select Elements` button in inspector, The Class Chain obtained by inspector is wrong and leads to the other element with same label., However the xpath is correct. When pressing `Tap` on this element it clicks on the other element. I can verify the Xpath is correct by using the `Search for element` option and then clicking on `Tap`. This clicks on the correct element. 
![Screenshot 2024-09-23 at 5 40 50 PM](https://github.com/user-attachments/assets/420bbe90-1d25-4abb-b55c-3419e84c5652)
On Changing `2` to `1` in ```**/XCUIElementTypeButton[`label == "More"`][2]``` the correct element can be tapped using the `Search for elements option.` This means the Class Chain is actually supposed to be ```**/XCUIElementTypeButton[`label == "More"`][1]``` instead of ```**/XCUIElementTypeButton[`label == "More"`][2]```

### Expected Behavior

The correct Class Chain is expected to be obtained.

### Operating System

Mac

### Appium Inspector Version

2024.8.2

### Appium Version

2.11.4

**Comment by eglitise** [comment]
I cannot reproduce this. Class chain indices start at 1, just like for xpaths, so both strategies would require the same index to find the same element. This is also how it behaves in my testing.
Is it possible that your page source/screenshot has changed since it was last retrieved?

**Comment by eglitise** [comment]
Closing due to no response
