### ISSUE TITLE
bug: <title>Failed to create session. Unexpected end of JSON input

### ISSUE THREAD

**Issue by peidachang** [appium/appium-inspector#1713]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

start Session err:Failed to create session. Unexpected end of JSON input

json:
{
  "platformName": "Android",
  "appium:automationName": "UiAutomator2",
  "appium:deviceName": "192.168.2.110:5555",
  "appium:appPackage": "com.tencent.mm",
  "appium:appActivity": ".ui.LauncherUI",
  "appium:unicodeKeyboard": true,
  "appium:resetKeyboard": true,
  "appium:noReset": true,
  "appium:newCommandTimeout": 10000
}

### Expected Behavior

Start a session for an Android application

### Operating System

Mac

### Appium Inspector Version

App Version: 2024.9.1

### Appium Version

Appium v2.11.0 and 2.11.4

### Further Information

The Appium server does not output any error log information

**Comment by eglitise** [comment]
* Can you reproduce this issue on earlier Inspector versions?
* Please provide a screenshot of the Inspector window that includes this error message

**Comment by eglitise** [comment]
Closing due to no response
