### ISSUE TITLE
IOS devices not capturing the App hierarchy in latest iphone 11 and above show as only XCUIElementTypeOther .But working in iphone 8 and iphone 7

### ISSUE THREAD

**Issue by Ishwarya121** [appium/appium-inspector#1732]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="806" alt="Iphone 11 actual" src="https://github.com/user-attachments/assets/7caf9b64-7249-435e-8b30-03ca3b2ffd00">

### Expected Behavior

<img width="809" alt="Iphone11 expected" src="https://github.com/user-attachments/assets/4be196a8-b7c4-4ff8-bccd-788f18b484bd">

### Operating System

Windows

### Appium Inspector Version

2024.3.4

### Appium Version

2.2.1

### Further Information

The hierarchy loading is not consistent in Appium inspector. Sometimes it loads and other it not loading properly. Please help on this is a critical issue. App loading is not working latest iphone devices.

**Comment by Ishwarya121** [comment]
Yes I checked in latest version of Appium.Latest Version of Appium Inspector(2024.3.4) as well. We have created with Java client library 7.6.0 and selenium 3.141.59. We are using Lambdatest platform for devices. Please let me know  where to get the server logs. We can have call to discuss to

**Comment by eglitise** [comment]
The latest version of Appium Inspector is 2024.9.1, not 2024.3.4. Please try with that.
I am not familiar with LambdaTest, so you would need to check their documentation on how to retrieve the Appium logs. It is possible that you may need to contact LambdaTest support.
I would also suggest upgrading your Java/Selenium libraries, since both are very outdated.

**Comment by eglitise** [comment]
Closing due to no response
