### ISSUE TITLE
bug: Appium Inspector (Desktop App / Linux VM) - No Scroll Bars

### ISSUE THREAD

**Issue by hal9kaye** [appium/appium-inspector#1740]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**Impacted Platform:**
|Component|Version|
|:---|:---|
|.AppImage|2024.6.1|
|Electron|13.6.9|
|Node.js|14.16.0|
|(*Appium Server*)|2.11.3|
|(*Lubuntu VM*)|22.04.2 LTS|

**Bug Summary:**
 - While creating gestures via *>**Appium Inspector** >**Gesture Builder***, I identified that no vertical scroll bar feature seems to have been implemented in the Desktop UI.

**Functional Impact:**
 - This compromises the ability to swiftly move between saved gestures.

### Expected Behavior

User should be able to vertically scroll through beyond a page of saved gestures..

### Operating System

Linux

### Appium Inspector Version

2024.6.1

### Appium Version

2.11.3

### Further Information

**Workaround:**
 - You can workaround this bug by (awkwardly) left-clicking the bottom of the UI then dragging the cursor towards the top of the screen. 

**Related Bugs:**
Following are related bugs for:
 - [Mac Platform](https://github.com/appium/appium-inspector/issues/194)
 - [Windows Platform](https://github.com/appium/appium-inspector/issues/383)

**Comment by hal9kaye** [comment]
Okay I will update it and advise..

For what it's worth, attached, is a screenshot as an example; in which I created a bunch of gesture records to go beyond inspector window height yet there is no vertical scroll bar on right hand side:

![no scroll bars](https://github.com/user-attachments/assets/9d27e073-c008-4ab1-81aa-e7335128f60b)

**Comment by eglitise** [comment]
Thanks, I see what you mean. The design used in 2024.8.2 and later is closer to that used in the Saved Capability Sets table on the Inspector's Session Builder screen. I assume that one also doesn't have a scrollbar for you (it doesn't have one on Windows), but it is still normaly scrollable using the scroll wheel.

**Comment by hal9kaye** [comment]
You are right, @eglitise, this is resolved within the latest version:

![scroll bars fixed](https://github.com/user-attachments/assets/3b12f716-63b8-47e3-b5e1-40983cf60474)

**Comment by hal9kaye** [comment]
Closed, noting fix was deployed from [release 2024.8.2](https://github.com/appium/appium-inspector/releases), onward.
