### ISSUE TITLE
bug: Appium Inspector giving "unrecognized selector sent to instance 0x302486***" while inspecting 

### ISSUE THREAD

**Issue by abhijeetkange** [appium/appium-inspector#1741]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Xcode-Version 16.0 (16A242d)
appium server- v2.11.5 
XCUITest-xcuitest@7.27.0
Appium inspector - 2019.9.1 
Real Device - ios 18.1
when i start the session in inspector it keeps loading and in appium server getting unrecognized selector sent to instance 0x302486*** error log - Encountered internal error running command: Error: Unable to launch WebDriverAgent. Original error: xcodebuild failed with code 70. This usually indicates an issue with the local Xcode setup or WebDriverAgent project configuration or the driver-to-platform version mismatch. Consider setting 'showXcodeLog' capability to true in order to check the Appium server log for build-related error messages.. Make sure you follow the tutorial at https://appium.github.io/appium-xcuitest-driver/latest/preparation/real-device-config/
    at quitAndUninstall (/Users/abhijeetkange/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:796:15)
    at /Users/abhijeetkange/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:866:13
    at wrapped (/Users/abhijeetkange/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:93:13)
    at retry (/Users/abhijeetkange/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:66:13)
    at retryInterval (/Users/abhijeetkange/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:103:10)
    at /Users/abhijeetkange/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:831:7

### Expected Behavior

Expected to load the app and able to inspect the element

### Operating System

Mac

### Appium Inspector Version

2019.9.1

### Appium Version

2.11.5

**Comment by eglitise** [comment]
Please check the Appium server log whether your device is using WebDriverAgentRunner 8.9.1 or later - if not, please rebuild it and try again.
If your issue is still reproducible with WDA >=8.9.1, please provide your full Appium server log.

**Comment by abhijeetkange** [comment]
After cleaning NPM cache , i reinstalled appium and XCUITest driver and it get resolved. 
npm cache clean --force
