### ISSUE TITLE
bug: Failed to create session. Unexpected token '<', "<html> <he"... is not valid JSON, when I start session

### ISSUE THREAD

**Issue by award-adhoc** [appium/appium-inspector#1759]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**Describe the bug**
When starting a session:

```
Error
Failed to create session. Unexpected token '<', "<html> <he"... is not valid JSON
```

<img width="1095" alt="Screenshot 2024-10-15 at 5 41 00 PM" src="https://github.com/user-attachments/assets/b55d4956-537e-43b5-8d14-317c5f1f6f7a">
<img width="1110" alt="Screenshot 2024-10-15 at 5 42 01 PM" src="https://github.com/user-attachments/assets/99e9b9f5-a579-4ed9-beac-af25d242b86c">

The only thing that changes the error is to remove the http:// in the Host value, which gives me a different error: Failed to create session. Unexpected token '<', "<!DOCTYPE "... is not valid JSON.

### Expected Behavior

I would like to receive a clearer message.
**When** http:// is copied from appium,
**Then** warn the user that http:// shouldn't be there. Using placeholder text to communicate when a specific format is needed is not accessible, especially contrast-insufficient placeholder text.

### Operating System

Mac

### Appium Inspector Version

App Version: 2024.9.1

### Appium Version

2.12.0

### Further Information

**Link to Appium Server logs**
[appium server log level debug](https://gist.github.com/award-adhoc/efc82662f6bfc87214396f6f8294998d#file-appium-server-log-level-debug)

**Environment**

 1. Appium version (or git revision) that exhibits the issue: $ appium -v 2.12.0
 2. Last Appium version that did not exhibit the issue (if applicable): unknown
 3. Node.js version (unless using Appium.app|exe): $ node -v v22.9.0
 4. Npm or Yarn package manager: $ npm -v 10.8.3
 5. Mobile platform/version under test: Android 14
 6. Real device or emulator/simulator: emulator
 7. Appium CLI or Appium.app|exe: Appium... app. -> /.nvm/versions/node/v22.9.0/bin/appium
 8. Android Studio has Build #AI-241.19072.14.2412.12360217, built on September 12, 2024
 9. Appium doctor for android is all-clear.

**Comment by award-adhoc** [comment]
Adding that fixing the address, but using the wrong port number produces a similarly cryptic error message, though this one is worse between the two. Thank you!

**Comment by unfixa1** [comment]
Make sure that the format of the Host address of the Appium server entered in the Appium Inspector is http://<hostname>:<port>. Make sure that http:// is required and do not remove it.

In addition, you can use [Servbay](servbay.com) to check your development environment, which is better than Docker on Mac. Servbay is equipped with SSL certificate function, which can adapt to the host and ensure that there is no compatibility conflict in the environment.

**Comment by eglitise** [comment]
@award-adhoc could you please provide the rest of the Appium server log, including the moment when you tried to start a session and received this error?
I do not believe the issue is caused by the `http://` in the Remote Host field - I tried to start a session with the same session parameters as in your screenshot, and I got this error:
![image](https://github.com/user-attachments/assets/63d00849-d7d6-411b-9adc-88ee6ab4bdd4)
It's not ideal, but it does show that the attempted URL is malformed, suggesting that `http://` should be removed from the Host field.

**Comment by award-adhoc** [comment]
> @award-adhoc could you please provide the rest of the Appium server log, including the moment when you tried to start a session and received this error? I do not believe the issue is caused by the `http://` in the Remote Host field - I tried to start a session with the same session parameters as in your screenshot, and I got this error: ![image](https://private-user-images.githubusercontent.com/37242620/376948379-63d00849-d7d6-411b-9adc-88ee6ab4bdd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NDExMDEsIm5iZiI6MTcyOTU0MDgwMSwicGF0aCI6Ii8zNzI0MjYyMC8zNzY5NDgzNzktNjNkMDA4NDktZDdkNi00MTFiLTlhZGMtODhlZTZhYjRiZGQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDIwMDAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlMDg2N2NkOTI5M2NhYzA0NzIwODY4OTcyYWM2ODhiZjJiYjY1YmVhZjQ5YzUxZGU2MjVmZTk2YTliMzE1NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5JOMQJ3p8K6qD_6DIuntXy81Q_cdESpppxN21CjCykA) It's not ideal, but it does show that the attempted URL is malformed, suggesting that `http://` should be removed from the Host field.

That's interesting! I have yet to get that message. For me, it was consistently the one I took a screenshot of, or the error: `Error
Failed to create session. Unexpected token < in JSON at position 0` (which I also get when port doesn't match appium port, but with the latest appium version + Mac Sequoia (updated over the weekend), I get it for both cases.

For the logs, I have no additional output to share. Appium doesn't return anything when I try to connect at this phase. The UI may error before it tries to talk to Appium, or I'm not using the logging level you require. This is a sample of the command for appium that I'm using to generate my logging:
`appium server --log-level debug --port=12345` Does that help at all?

**Comment by eglitise** [comment]
The Appium log should still contain the request from the Inspector with the capabilities, and the response from the server with the error message - that is what I am looking for. Unless you mean that the log you shared is all of it?
But I also wonder if this issue is specific to your app. Could you try starting a session using a different app (e.g. Android default settings app) and see if you get the same error?

**Comment by award-adhoc** [comment]
> Unless you mean that the log you shared is all of it?
That was the full output of Appium's log in terminal while running when I click "Start Session" with the log level set to debug. Would the console logs help at all? 
[Console.log](https://github.com/user-attachments/files/17498612/Console.log)

> Could you try starting a session using a different app (e.g. Android default settings app) and see if you get the same error?
I can reproduce this with no configuration as long as the appium server is running. I don't think the apk is a factor:
<img width="1100" alt="Screenshot 2024-10-23 at 2 56 04 PM" src="https://github.com/user-attachments/assets/028acd77-2bd9-4835-a047-2fb42d4ea3e1">

I'm sorry, it seems like you aren't going to be able to reproduce and I don't know why! I'm on an M3 Mac, so if you happen to be on an Intel machine, I wonder if that could be the difference? I'm up to date on node/npm/nvm and have the latest Appium Inspector and Appium.

**Comment by KazuCocoa** [comment]
I assume the inspector received HTML response. e.g. https://github.com/appium/appium-inspector/issues/626

Not in this appium org repositories, but I saw some proxies env environment that returned HTML response for unallowed endpoint calls.

**Comment by award-adhoc** [comment]
> I saw some proxies env environment that returned HTML response for unallowed endpoint calls.
This is one way to produce. However, I found a previous entry from a user who was unable to start the server (vs caring about the error message given) and had turned off SSL proxying and recording (for good measure) and still see it. I don't remember if I tried closing Charles at the time, now, since it was already too long ago for me.
<img width="311" alt="Screenshot 2024-10-23 at 5 38 12 PM" src="https://github.com/user-attachments/assets/2f600714-a700-4e3c-8ea5-fea4446a3963">

This gave me an idea though, and closing Charles OR ticking the "SSL" checkbox **does** produce the correct error message. 
<img width="1016" alt="Screenshot 2024-10-23 at 5 35 44 PM" src="https://github.com/user-attachments/assets/cc8e0eec-2421-48b7-81d1-ebfd92795995">

What I don't understand is this: Given SSL proxying isn't active/enabled, why does Charles merely being 'open' require Appium Inspector to have the SSL toggle enabled in order to see the expected warning message? Even if Charles was recording traffic, it's all encrypted and useless without SSL Proxying enabled. Is Appium Inspector maybe looking only for **any** certificate and deciding that's "SSL"? Not all certificates are for proxying, though, so that's unlikely, right?

**Comment by KazuCocoa** [comment]
What response could you see via browser?
You also could open "inspector" via the context menu and see what response came in the network tab:
<img width="577" alt="Screenshot 2024-10-23 at 6 20 15 PM" src="https://github.com/user-attachments/assets/72033a6f-a957-4dee-a5d5-dd3e8614fa71">

**Comment by eglitise** [comment]
Closing due to no response
