### ISSUE TITLE
bug: I can't select the System selector 

### ISSUE THREAD

**Issue by AvinashEediga90** [appium/appium-inspector#1789]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can't select the os level system selectors (iOS)
<img width="255" alt="Screenshot 2024-11-08 at 4 19 05 pm" src="https://github.com/user-attachments/assets/c233ba50-5e8c-4b24-a669-6f318eb94638">

### Expected Behavior

it should select the os level system selectors (iOS)

### Operating System

Mac

### Appium Inspector Version

2024.9.1

### Appium Version

App Version: 2024.9.1 Electron: 31.6.0 Node.js: 20.17.0

### Further Information

and also all system level components

**Comment by eglitise** [comment]
[Please refer to the XCUITest driver documentation for handling native system alerts.](https://appium.github.io/appium-xcuitest-driver/latest/guides/troubleshooting/#interact-with-dialogs-managed-by-comapplespringboard)

**Comment by AvinashEediga90** [comment]
@thanks @eglitise   

This sample code worked for me for iOS using typescript and webdriverIo 

// Switch to SpringBoard 
                await driver.updateSettings({ defaultActiveApplication: "com.apple.springboard" });
                const allowButton = await driver.$('~Allow');
                await allowButton.click(); // Revert to the original application 
                await driver.updateSettings({ defaultActiveApplication: "auto" });

Thanks,
Avi
