### ISSUE TITLE
how to add appium-inspector in appium(gui-version)

### ISSUE THREAD

**Issue by farhan4alam** [appium/appium-inspector#179]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I'm not able to get appium-inspector .dmg to install mac os, not able to use/install appium-inspector in my machine

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [x] Mac

**Comment by emaan-c** [comment]
@farhan4alam You may be downloading the wrong .dmg file for Appium depending on your MAC OS system. You will need to be more specific!

**Comment by eglitise** [comment]
Closing due to no response
