### ISSUE TITLE
bug: Appium inspector failed to connect with appium server with desired capabilities

### ISSUE THREAD

**Issue by Elanthendral02** [appium/appium-inspector#1793]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/user-attachments/assets/a093324f-be54-4820-b1f9-e4b61749ee9f)
![image](https://github.com/user-attachments/assets/2c6e36d2-099f-458b-bb74-0275b32491d0)

### Expected Behavior

should connect to appium server and open calculator app

### Operating System

Windows

### Appium Inspector Version

2024.9.1

### Appium Version

 Appium v2.12.1

### Further Information

Failed to create session. 'automationName' can't be blank; 'platformName' can't be blank

**Comment by mykola-mokhnach** [comment]
the above error is expected. Change `PlatformName` to `platformName`

**Comment by Elanthendral02** [comment]
Changes

**Comment by eglitise** [comment]
@Elanthendral02 did that fix your issue? If not, can you provide another screenshot and/or Appium server log?

**Comment by Elanthendral02** [comment]
![image](https://github.com/user-attachments/assets/d19851c0-1667-4454-a070-4bee5a5cd769)

I don't know how appium prefix is not attached near platform name. from appium inspector now its working

**Comment by eglitise** [comment]
Thanks for the confirmation 👍 
`platformName` is a standard W3C capability, so it does not require the `appium:` prefix. [Check the Capabilities documentation for more information.
](http://appium.io/docs/en/latest/guides/caps/)Please also note that you have a typo in `appium:platfromVersion`.
Closing as resolved.
