### ISSUE TITLE
bug: Inspector hangs and app freezes as soon as session begins

### ISSUE THREAD

**Issue by pasupuletisyama** [appium/appium-inspector#1801]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Please see the screenshot, the app inspector will just load like that for eternity, I can't tap any buttons on the app either as it's completely frozen so I need to force close it. I also need to force close Appium Inspector as the 'x' button does nothing when it's like this

<img width="1440" alt="Screenshot 2024-11-20 at 2 32 19 PM" src="https://github.com/user-attachments/assets/b3f65072-3d6b-4c1e-97b5-96522d021b40">

### Expected Behavior

should work

### Operating System

Mac

### Appium Inspector Version

2024.9.1

### Appium Version

2.12.1

**Comment by pasupuletisyama** [comment]
I have verified the below existing issue and it doesn't resolve my issue.
https://github.com/appium/appium-inspector/issues/1386

**Comment by eglitise** [comment]
Please provide your Appium server log.

**Comment by eglitise** [comment]
The above log confirms that the issue here is the same WDA problem I mentioned above, though the WDA logs do not return its version. My guess is that the WDA version was manually downgraded at some point.
Can you reinstall the xcuitest driver? This should ensure that the expected WDA version is also installed. You can then check this version in `.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/package.json`.

**Comment by pasupuletisyama** [comment]
![Uploading image.png…]()

**Comment by pasupuletisyama** [comment]
> The above log confirms that the issue here is the same WDA problem I mentioned above, though the WDA logs do not return its version. My guess is that the WDA version was manually downgraded at some point. Can you reinstall the xcuitest driver? This should ensure that the expected WDA version is also installed. You can then check this version in `.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/package.json`.

{
  "name": "appium-webdriveragent",
  "version": "8.11.1",
  "description": "Package bundling WebDriverAgent",
  "main": "./build/index.js",
  "types": "./build/index.d.ts",
  "scripts": {
    "build": "tsc -b",
    "dev": "npm run build -- --watch",
    "clean": "npm run build -- --clean",
    "lint": "eslint .",
    "format": "prettier -w ./lib",
    "lint:fix": "npm run lint -- --fix",
    "prepare": "npm run build",
    "version": "npm run sync-wda-version",
    "test": "mocha --exit --timeout 1m \"./test/unit/**/*-specs.js\"",
    "e2e-test": "mocha --exit --timeout 10m \"./test/functional/**/*-specs.js\"",
    "bundle": "npm run bundle:ios && npm run bundle:tv",
    "bundle:ios": "TARGET=runner SDK=sim node ./Scripts/build-webdriveragent.js",
    "bundle:tv": "TARGET=tv_runner SDK=tv_sim node ./Scripts/build-webdriveragent.js",
    "fetch-prebuilt-wda": "node ./Scripts/fetch-prebuilt-wda.js",
    "sync-wda-version": "node ./scripts/update-wda-version.js --package-version=${npm_package_version} && git add WebDriverAgentLib/Info.plist"
  },
  "engines": {
    "node": ">=14",
    "npm": ">=8"
  },
  "prettier": {
    "bracketSpacing": false,
    "printWidth": 100,
    "singleQuote": true
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/appium/WebDriverAgent.git"
  },
  "keywords": [
    "Appium",
    "iOS",
    "WebDriver",
    "Selenium",
    "WebDriverAgent"
  ],
  "author": "Appium Contributors",
  "license": "Apache-2.0",
  "bugs": {
    "url": "https://github.com/appium/WebDriverAgent/issues"
  },
  "homepage": "https://github.com/appium/WebDriverAgent#readme",
  "devDependencies": {
    "@appium/eslint-config-appium-ts": "^0.x",
    "@appium/test-support": "^3.0.0",
    "@appium/tsconfig": "^0.x",
    "@appium/types": "^0.x",
    "@semantic-release/changelog": "^6.0.1",
    "@semantic-release/git": "^10.0.1",
    "@types/bluebird": "^3.5.38",
    "@types/lodash": "^4.14.196",
    "@types/mocha": "^10.0.1",
    "@types/node": "^22.0.0",
    "@types/teen_process": "^2.0.1",
    "appium-xcode": "^5.0.0",
    "chai": "^5.1.1",
    "chai-as-promised": "^8.0.0",
    "conventional-changelog-conventionalcommits": "^8.0.0",
    "node-simctl": "^7.0.1",
    "mocha": "^10.0.0",
    "prettier": "^3.0.0",
    "semantic-release": "^24.0.0",
    "semver": "^7.3.7",
    "sinon": "^19.0.1",
    "ts-node": "^10.9.1",
    "typescript": "^5.4.2"
  },
  "dependencies": {
    "@appium/base-driver": "^9.0.0",
    "@appium/strongbox": "^0.x",
    "@appium/support": "^5.0.3",
    "appium-ios-device": "^2.7.25",
    "appium-ios-simulator": "^6.0.0",
    "async-lock": "^1.0.0",
    "asyncbox": "^3.0.0",
    "axios": "^1.4.0",
    "bluebird": "^3.5.5",
    "lodash": "^4.17.11",
    "source-map-support": "^0.x",
    "teen_process": "^2.2.0"
  },
  "files": [
    "index.ts",
    "lib",
    "build/index.*",
    "build/lib",
    "Scripts/build.sh",
    "Scripts/fetch-prebuilt-wda.js",
    "Scripts/build-webdriveragent.js",
    "Configurations",
    "PrivateHeaders",
    "WebDriverAgent.xcodeproj",
    "WebDriverAgentLib",
    "WebDriverAgentRunner",
    "WebDriverAgentTests",
    "XCTWebDriverAgentLib",
    "CHANGELOG.md"
  ]
}

**Comment by pasupuletisyama** [comment]
issue got resolved thank you so much ... i have got the correct path now .....hence closing the defect...
