### ISSUE TITLE
bug: Inspector it keeps loading without showing the device and it appears An Error Message related to Session !

### ISSUE THREAD

**Issue by EbrahimSalem1** [appium/appium-inspector#1815]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I run the Appium server and then adjust the inspector capability Builder set and try to start the session, The inspector is still loading and the device is not displayed as previously expected and when I go to 'Session Information' tab shows me a message: Call to 'getSession' failed  !

### Expected Behavior

When I start the Appium server and then set the Inspector Capacity Generator set and try to start the session, the Inspector displays the device as previously expected and I don't get a session error message because all the settings are correct because they are the same settings that were working before in the Inspector

### Operating System

Windows

### Appium Inspector Version

2024.3.1

### Appium Version

2.12.1

### Further Information

![Screenshot (144)](https://github.com/user-attachments/assets/3d7f1cbd-5569-4469-94fd-63d995270555)
![Screenshot (145)](https://github.com/user-attachments/assets/f10b74fc-8010-44ef-9939-244cf54f0ce4)
![Screenshot (147)](https://github.com/user-attachments/assets/4965d07c-16cb-42c7-8db6-d96631321b20)

**Comment by eglitise** [comment]
It looks like you are trying to change the Session Inspector tabs before the source/screenshot has loaded. This is not an expected use case and is no longer allowed as of version 2024.9.1.
If you are still having problems with the session not being loaded after upgrading to 2024.9.1, please attach your full Appium server log.

**Comment by EbrahimSalem1** [comment]
Thanks for your answered  @eglitise , Okay I will
