### ISSUE TITLE
bug: Mac OS 15.1 appium inspector don't load mobile app screen

### ISSUE THREAD

**Issue by ankushkumargarg** [appium/appium-inspector#1825]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am running appium inspector version 
App Version: 2024.9.1
Electron: 31.6.0
Node.js: 20.17.0

i installed app on IOS emulator, and when i start session on inspector, app launch on device but inspector keep loading app screen. 
it won't show any screen, source and selected element
<img width="1099" alt="Screenshot 2024-11-28 at 7 49 35 PM" src="https://github.com/user-attachments/assets/098a81c0-f8d2-406a-9956-44fedce87e32">

### Expected Behavior

it should show screen on inspector and show all elements

it was working with same config on MAC OS 14

### Operating System

Mac

### Appium Inspector Version

2024.9.1

### Appium Version

2.12.1

**Comment by eglitise** [comment]
Are you using Xcode 16 and/or iOS 18? Please ensure you have upgraded to XCUITest driver >=7.24.15 and rebuilt WDA. [Refer to the XCUITest driver documentation for Xcode/iOS version compatibility.](https://appium.github.io/appium-xcuitest-driver/latest/installation/requirements/#xcodeios-version-support)
If not, please provide your Appium server log.

**Comment by ankushkumargarg** [comment]
@eglitise , Thanks for quick response

i updated XCUITest and it worked

i was using Xcode 16 with IOS 17.4 but issue was there with IOS18 also, after driver update this inspector is working
