### ISSUE TITLE
Could not connect to Appium server URL 'https://ondemand.eu-central-1.saucelabs.com:443/wd/hub'

### ISSUE THREAD

**Issue by Thanigai2** [appium/appium-inspector#1870]
Error
Could not connect to Appium server URL 'https://ondemand.eu-central-1.saucelabs.com:443/wd/hub'. Please check if the server is running and the URL is correct (valid URLs can be found at the start of the Appium server log). If you are using the Inspector's browser version, ensure the server has been started with '--allow-cors'.

**Comment by eglitise** [comment]
I'm not sure what is unclear about this error message. It seems you are connecting to a Sauce Labs-hosted server, so please contact them for further assistance.
