### ISSUE TITLE
feature request: use monospace font in capability names and values so whitespace is obvious

### ISSUE THREAD

**Issue by tinyhare** [appium/appium-inspector#188]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I use a lot of time to get the reason of the error:
![image](https://user-images.githubusercontent.com/6851513/138584850-35f10f47-0b90-4c23-9f4d-90fb30b48555.png)
finally, I find the beginning whitespace!
![image](https://user-images.githubusercontent.com/6851513/138584871-263ad864-b0f1-4324-9089-9160e599a816.png)

_So I advise to auto remove the whitespace from the beginning and end of the string in Capability value_

## Environment

- I am running Appium Desktop version _1.22.0_.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
I think a good solution here is to switch to a monospace font in the capabilities text boxes, so spaces are more apparent.
