### ISSUE TITLE
Appium Inspector window missing start session button

### ISSUE THREAD

**Issue by Calton78** [appium/appium-inspector#193]
## The problem

Appium Inspector window doesn't show the functions in the lower part of the window (Save, Save as, Start session...); it is not possible to resize vertically the page 

## Environment

- I am running Appium Desktop version _<Appium-Inspector-linux-2021.9.2.AppImage>_ but also tried with the 2 previous releases.
- I am on (pick one):
    - [ ] Mac
    - [ ] Windows
    - [ X] Linux - Ubuntu 20.04.3 LTS
![image](https://user-images.githubusercontent.com/47217696/139727041-0f3f3688-67c2-429a-9077-cf45a376f574.png)

**Comment by jlipps** [comment]
hmm, there is a minimum height and width. what is your screen resolution?

**Comment by Calton78** [comment]
1366 x 768

**Comment by jlipps** [comment]
Yes, the minimum height of the app is 800px

**Comment by Calton78** [comment]
Ouch.. Any suggestion on how to start a session without this part?

**Comment by jlipps** [comment]
You could try to build a version of the inspector with a different min height, it would involve changing one line of code. Alternatively, do you have the ability to increase your screen resolution? 768 pixels height is pretty small nowadays.

**Comment by jlipps** [comment]
you could also try the web version? https://inspector.appiumpro.com

**Comment by jlipps** [comment]
Yeah I just checked the web version and it allows scroll to find the lower buttons at any rate.

**Comment by Calton78** [comment]
Ok Thanks I'll follow one of the solutions you wrote!
