### ISSUE TITLE
No longer possible to scroll App Source using keyboard buttons

### ISSUE THREAD

**Issue by avient** [appium/appium-inspector#194]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Inspector issue

## The problem

In Appium Inspector (App Source) view is no longer possible to scroll by left/right/up/down/End/Home/Page Down/Page Up buttons. It's really useful when App Source is huge.

It used to be possible when Inspector was the part of Appium Desktop.

## Environment

- I am running Appium Inspector version _<v2021.10.1>_.
- I am on (pick one):
    - [x] Mac

**Comment by jlipps** [comment]
Hmm strange, there were no code changes that should have caused this in the migration. We can take a look.
