### ISSUE TITLE
screenshotBox doesn't update if method getPageSource execute longer 10sec

### ISSUE THREAD

**Issue by atimofeev86** [appium/appium-inspector#195]
## Appium or Appium Desktop?
Appium 1.22.0

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

If answer from appium server longer then 10 sec then screenshotBox doesn't update
![2021-11-05_23-36-38](https://user-images.githubusercontent.com/41478386/140581584-ce121646-df57-45d8-aa64-fa68d35ad803.png)
![2021-11-05_23-37-40](https://user-images.githubusercontent.com/41478386/140581587-8d9390f2-1c62-4535-a63b-02334c694b52.png)

## Environment

- I am running Appium Desktop version 1.22.0
- I am on (pick one):
    - [ ] Mac
    - [X] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
If you're still experiencing this issue with the latest version of the inspector, can you please create a gist of the full appium log? So far I can't see anything amiss here, other than it seems the client stopped listening for the source before the source was ready. No client that I know of has a 10 second request timeout as long as it hasn't been modified...

**Comment by eglitise** [comment]
Closing due to no response
