### ISSUE TITLE
Elements are offset incorrectly in inspector IOS.

### ISSUE THREAD

**Issue by gselsidi** [appium/appium-inspector#2]
I don't know if I posted this issue in the correct place, but I need help with it. The original issue is posted here:

https://github.com/appium/appium-dot-app/issues/507

When being inspected the elements aren't full screen but offset by a factor of about 3

**Comment by bootstraponline** [comment]
Hi, the correct place for that issue is on the appium-dot-app repo. This repo is for the next generation appium inspector which hasn't been released yet to end users.

For what it's worth, I've noticed the same problem and haven't found a solution.
