### ISSUE TITLE
Inspector locks up and reverts to previous screen instead of loading new screen

### ISSUE THREAD

**Issue by wrathmelior** [appium/appium-inspector#209]
## The problem

When loading the next screen after clicking on an element, the inspector sits on the loading animation for 5-15 min and then reverts to the previous screen instead of displaying the new screen. 
Before click https://monosnap.com/file/cSllWC1SCUldJ5sJylsCg5Qj65N7Ga
After Click https://monosnap.com/file/Ksi9Hfu3c4rA1ehO083R3tuk0nxzU4
After loading https://monosnap.com/file/LCI2kmU0EinbklbhJoXgo2L7O3stTn

It seems to get stuck in this loop:
[XCUITest] Executing command 'getTimeouts'
[HTTP] <-- GET /wd/hub/session/f31ce03d-24dc-462f-8ed1-24e57eedb1e9/timeouts - - ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/f31ce03d-24dc-462f-8ed1-24e57eedb1e9/timeouts
[HTTP] {}
[W3C (f31ce03d)] Calling AppiumDriver.getTimeouts() with args: ["f31ce03d-24dc-462f-8ed1-24e57eedb1e9"]
[XCUITest] Executing command 'getTimeouts'
[HTTP] <-- GET /wd/hub/session/f31ce03d-24dc-462f-8ed1-24e57eedb1e9/screenshot - - ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/f31ce03d-24dc-462f-8ed1-24e57eedb1e9/timeouts
[HTTP] {}
[W3C (f31ce03d)] Calling AppiumDriver.getTimeouts() with args: ["f31ce03d-24dc-462f-8ed1-24e57eedb1e9"]
[XCUITest] Executing command 'getTimeouts'

## Environment

* Appium version (or git revision) that exhibits the issue:1.22.0
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: Mac Big Sur
* Node.js version (unless using Appium.app|exe): 12.8.1
* Npm or Yarn package manager:
* Mobile platform/version under test: Iphone xs IOS 15
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: appium desktop

## Link to Appium logs
https://gist.github.com/wrathmelior/b51aac17b2858cb98a8b82f7b4c7ad2c

## Capabilities used
{
  "platformName": "iOS",
  "deviceName": "BOOJ0000384",
  "udid": "00008020-000349913AF8002E",
  "app": "/Users/jessical/Desktop/HSAAPK/REMAX.ipa",
  "xcodeOrgId": "Z556Z8MS2X",
  "xcodeSigningId": "iPhone Developer",
  "automationName": "XCUITest",
  "appium:waitForQuietness": "false",
  "appium:waitForQuiescence": "false",
  "appium:wdaEventloopIdleDelay": "7",
  "appium:eventLoopIdleDelaySec": "4",
  "appium:startIWDP": "true"
}

**Comment by jlipps** [comment]
@wrathmelior does the device screen revert as well or only the inspector screen? is what you are saying that the inspector screen is out of sync with the device screen, even when the device screen is stable and you have clicked refresh in the inspector?

**Comment by wrathmelior** [comment]
Only the inspector screen reverts, the phone (real device) stays on the new screen. The inspector loses sync with the real device and gets stuck on an old screen. Clicking refresh results in a long loading animation eventually reverting back to the old screen that does not match the device.

**Comment by jlipps** [comment]
Is there anything in the inspector console log that shows an error?

**Comment by jlipps** [comment]
also, can you change the server to be the command line appium server (latest version) rather than appium desktop, to see if that makes a difference?

**Comment by wrathmelior** [comment]
The CLI has the same issue, though not as frequently. I was able to get it to work a few times but then it started locking up the same way as described above. The logs are attached, I don't see an error.

**Comment by jlipps** [comment]
In this case I'm not seeing how there could be any issue with the inspector itself. Seems like WDA or the app hangs for a long period of time, causing other requests to time out. In that case I guess a cached screenshot is returned. I would next check the iOS system log to see if there's anything there related to your app or WDA that could be causing the hang.

**Comment by wrathmelior** [comment]
This is interesting in the logs, I didn't see this error before in previous sessions:

[HTTP] <-- GET /wd/hub/session/bc08b428-7ca2-4351-a7a4-ee1f61c7feaa/source - - ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/bc08b428-7ca2-4351-a7a4-ee1f61c7feaa/timeouts
[HTTP] {}
[W3C (bc08b428)] Calling AppiumDriver.getTimeouts() with args: ["bc08b428-7ca2-4351-a7a4-ee1f61c7feaa"]
[XCUITest] Executing command 'getTimeouts'
[Xcode] 2021-12-01 11:16:24.233170-0700 WebDriverAgentRunner-Runner[341:6050] Cannot take a snapshot with attribute(s) (
[Xcode]     "XC_kAXXCAttributeElementBaseType",
[Xcode]     "XC_kAXXCAttributeHasNativeFocus",
[Xcode]     "XC_kAXXCAttributeTruncatedValue",
[Xcode]     "XC_kAXXCAttributeViewControllerTitle",
[Xcode]     "XC_kAXXCAttributeUserTestingElements",
[Xcode]     "XC_kAXXCAttributeAutomationType",
[Xcode]     "XC_kAXXCAttributeBannerIsStickyAttribute",
[Xcode]     "XC_kAXXCAttributeIdentifier",
[Xcode]     "XC_kAXXCAttributeTraits",
[Xcode]     "XC_kAXXCAttributeFrame",
[Xcode]     "XC_kAXXCAttributeVerticalSizeClass",
[Xcode]     "XC_kAXXCAttributeViewControllerClassName",
[Xcode]     "XC_kAXXCAttributeIsUserInteractionEnabled",
[Xcode]     "XC_kAXXCAttributeLabel",
[Xcode]     "XC_kAXXCAttributeURL",
[Xcode]     "XC_kAXXCAttributeParent",
[Xcode]     "XC_kAXXCAttributeHorizontalSizeClass",
[Xcode]     "XC_kAXXCAttributePlaceholderValue",
[Xcode]     "XC_kAXXCAttributeElementType",
[Xcode]     "XC_kAXXCAttributeIsVisible"
[Xcode] ) of 'XCUIElementTypeAny' after 15.00 seconds
[Xcode] 2021-12-01 11:16:24.233433-0700 WebDriverAgentRunner-Runner[341:6050] This timeout could be customized via 'customSnapshotTimeout' setting
[Xcode] 2021-12-01 11:16:24.233546-0700 WebDriverAgentRunner-Runner[341:6050] Internal error: Error kAXErrorIPCTimeout getting snapshot for element  {pid=811} {uid=[ID:1 hash:0x0]}
[Xcode] 2021-12-01 11:16:24.233678-0700 WebDriverAgentRunner-Runner[341:6050] Falling back to the default snapshotting mechanism for the element 'XCUIElementTypeAny' (some attribute values, like visibility or accessibility might not be precise though)
[Xcode] 
[HTTP] <-- GET /wd/hub/session/bc08b428-7ca2-4351-a7a4-ee1f61c7feaa/timeouts - - ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/bc08b428-7ca2-4351-a7a4-ee1f61c7feaa/timeouts
[HTTP] {}
[W3C (bc08b428)] Calling AppiumDriver.getTimeouts() with args: ["bc08b428-7ca2-4351-a7a4-ee1f61c7feaa"]
[XCUITest] Executing command 'getTimeouts'
[HTTP] <-- GET /wd/hub/session/bc08b428-7ca2-4351-a7a4-ee1f61c7feaa/timeouts - - ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/bc08b428-7ca2-4351-a7a4-ee1f61c7feaa/timeouts
[HTTP] {}
[W3C (bc08b428)] Calling AppiumDriver.getTimeouts() with args: ["bc08b428-7ca2-4351-a7a4-ee1f61c7feaa"]
[XCUITest] Executing command 'getTimeouts'
[HTTP] <-- GET /wd/hub/session/bc08b428-7ca2-4351-a7a4-ee1f61c7feaa/timeouts - - ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/bc08b428-7ca2-4351-a7a4-ee1f61c7feaa/timeouts
[HTTP] {}
[W3C (bc08b428)] Calling AppiumDriver.getTimeouts() with args: ["bc08b428-7ca2-4351-a7a4-ee1f61c7feaa"]
[XCUITest] Executing command 'getTimeouts'
[HTTP] <-- GET /wd/hub/session/bc08b428-7ca2-4351-a7a4-ee1f61c7feaa/timeouts - - ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/bc08b428-7ca2-4351-a7a4-ee1f61c7feaa/timeouts
[HTTP] {}

**Comment by jlipps** [comment]
Yeah, looks like an XCTest issue, possibly in interaction with the particular way your app is built. Maybe @mykola-mokhnach can confirm. In this case I don't see how Appium could do anything to fix it.
