### ISSUE TITLE
Unable to set geolocation in Appium inspector

### ISSUE THREAD

**Issue by hamidmunir10pearls** [appium/appium-inspector#210]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
Hi,
I am trying to set geolocation in Appium inspector and passing the following jsonObject:
{"latitude": 33.5306035, "longitude": 73.1207708, "altitude": 402.9108708 }
But i am getting this error :
Malformed type for "location" parameter of command setGeoLocation Expected: object Actual: string For more info see https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#post-sessionsessionidlocation.
Can someone guide if I am doing wrong

![image](https://user-images.githubusercontent.com/87413255/142823567-7f8d8800-a689-4f0a-a4de-31d3171f9ad0.png)

## Environment

- I am running Appium Desktop version _<1.22.0>_.
- I am on (pick one):
 - [x] Windows

**Comment by KazuCocoa** [comment]
Probably we need to adjust method in this inspector:
https://github.com/webdriverio/webdriverio/blob/6722af60eb2fdafad9f7538a69feece8574dd696/packages/webdriver/src/command.ts#L69-L71

**Comment by Thuytien** [comment]
> Probably we need to adjust method in this inspector: https://github.com/webdriverio/webdriverio/blob/6722af60eb2fdafad9f7538a69feece8574dd696/packages/webdriver/src/command.ts#L69-L71

Hi @KazuCocoa , so could you guide which is correct jsonObject format for geolocation? I have the same issue.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-inspector/blob/dda9cb65b54910517907d4a1b398e87f26dc48d7/app/renderer/components/Inspector/shared.js#L159 need up-to-date.

**Comment by Thuytien** [comment]
> https://github.com/appium/appium-inspector/blob/dda9cb65b54910517907d4a1b398e87f26dc48d7/app/renderer/components/Inspector/shared.js#L159
> 
> need up-to-date.(inspector's code)

Many thanks @KazuCocoa
