### ISSUE TITLE
Appium Inspector  2021.9.2 : Not able to scroll in iOS app

### ISSUE THREAD

**Issue by hamidmunir10pearls** [appium/appium-inspector#216]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I am using Appium inspector version 2021.9.2  and not able to scroll in IOS app but it does scroll for android app.

## Environment

- I am running Appium Desktop version _<1.22.0>_.
- I am on (pick one):

    -[ ] Windows

**Comment by jlipps** [comment]
transferred to the correct repo.

**Comment by jlipps** [comment]
i think we'll need some more information to understand what you mean.

**Comment by hamidmunir10pearls** [comment]
> i think we'll need some more information to understand what you mean.
I am trying to scroll the screen on IOS app. When i swipe the screen using coordinates (from down to up) ,it does not scroll the screen down. But when I scroll in Android using coordinates, it works. Here is the complete video



https://user-images.githubusercontent.com/87413255/143183372-f5a3ad4d-94df-4b8b-87ff-5d6e599b8b06.mp4

**Comment by jlipps** [comment]
OK thanks. Can you provide the server log as well so we can see what parameters were sent in?

**Comment by hamidmunir10pearls** [comment]
> OK thanks. Can you provide the server log as well so we can see what parameters were sent in?

I don't see any call going to server while invoking set Geolocation. So no logs are available in this case. It seems like a frontend error
You can watch in video as well

https://user-images.githubusercontent.com/87413255/143383907-94a8a2c9-bb92-45c6-a467-35a22e78c04f.mp4

l

**Comment by jlipps** [comment]
@hamidmunir10pearls the geolocation issue is unrelated to the topic of this issue. please create a new issue for it if you want to discuss.

**Comment by hamidmunir10pearls** [comment]
> @hamidmunir10pearls the geolocation issue is unrelated to the topic of this issue. please create a new issue for it if you want to discuss.

Sorry for the mistake.
I tried see the server logs by swiping using coordinated but server is not showing any logs. See vide

https://user-images.githubusercontent.com/87413255/143988339-7fd14cd5-df84-4acd-9b79-c38c2c83e875.mp4

o

**Comment by jlipps** [comment]
I'm not convinced that server is being used for the session at all. There is no create session logs, no get screenshot logs, no get source logs. So I don't think the server window you have shown is actually the one being connected to by the inspector.

**Comment by hamidmunir10pearls** [comment]
> I'm not convinced that server is being used for the session at all. There is no create session logs, no get screenshot logs, no get source logs. So I don't think the server window you have shown is actually the one being connected to by the inspector.

Hey i forgot to mention that i am using BrowserStack over the Appium inspector. I got the logs from the session which are in this file:
[Appium logs.txt](https://github.com/appium/appium-inspector/files/7631078/Appium.logs.txt)

**Comment by jlipps** [comment]
Are you able to reproduce with a locally running Appium server at the latest version?

**Comment by jlipps** [comment]
But based on what I see in the logs, I'd say Browserstack's version of Appium is too low to handle the swipe action correctly. Try to use the latest version of Appium on BS.
