### ISSUE TITLE
When we tap on the searched element, its not getting highlighted in the Snapshot

### ISSUE THREAD

**Issue by aarahmanqa** [appium/appium-inspector#217]
## Appium or Appium Desktop?

- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

1. Enter a locator in Appium Desktop and search for it.
2. It shows a list of elements that match the locator.
3. When we tap on any element, it should get highlighted in the Snapshot which is not happening now.

## Environment

- I am running Appium Desktop version _2021.9.2_.
- I am on (pick one):
    - [X] Mac
    - [ ] Windows
    - [ ] Linux
  
<img width="1792" alt="Screenshot 2021-11-19 at 12 23 16 PM" src="https://user-images.githubusercontent.com/6194278/142578752-36c562c7-53d0-40be-aa88-bae7be1a0e52.png">

**Comment by jlipps** [comment]
I moved this issue to the correct repo.

**Comment by sivajigujja** [comment]
I'm facing the same issue, @jlipps can you point me the repo where this issue was moved to? Or provide the link. I would like to know if there's any update or any fix

**Comment by jlipps** [comment]
this is the correct repo. it has not yet been investigated/fixed.

**Comment by Hristovski** [comment]
It's also not highlighting the element in the middle list/tree [App Source]

**Comment by gautham71298** [comment]
@jlipps Is there any fix provided for this?

I'm still facing this issue on the latest release: **2022.2.1**

**Comment by jlipps** [comment]
Nope, not yet! Hoping to get some more bandwidth to work on this in the coming months. Meanwhile anyone else is also welcome to investigate and propose a fix.

**Comment by kishore8143** [comment]
@jlipps Any update the above issue

**Comment by jlipps** [comment]
No update

**Comment by jlipps** [comment]
this has been fixed in the latest release

**Comment by AlinaMaliarenko** [comment]
special thank you for this fix from me!!!
