### ISSUE TITLE
Appium desktop inspector not correct for orientation

### ISSUE THREAD

**Issue by YevheniiaHre** [appium/appium-inspector#218]
The problem
When I set up portrait mode and I open inspector, simulator is in proper position (portrait mode) but inspector shows me landscape mode.

Environment
- Appium Desktop v.1.22.0
- Mac v.12.0.1
- XCode 13.1
The similar problem was registered in Appium Desktop ticket #10015

**Comment by jlipps** [comment]
Can you include screenshots of the problem as well as the Appium logs? Can you also run a basic Appium script (not using the inspector) that writes out screenshots to confirm they are in the correct orientation?

**Comment by YevheniiaHre** [comment]
The main problem with the fact that the fields are available in 'Portrait' orientation and the application only in 'Landscape'
<img width="1273" alt="Screenshot 2021-11-24 at 18 41 03" src="https://user-images.githubusercontent.com/93028875/143280189-a56b7027-d6ab-4381-9d54-b0c32ad44d0d.png">

**Comment by YevheniiaHre** [comment]
Xcode simulator <img width="1440" alt="Screenshot 2021-11-24 at 18 42 20" src="https://user-images.githubusercontent.com/93028875/143280324-caa44c12-98ff-4bd8-b733-d4426602af5e.png">

**Comment by jlipps** [comment]
so is the issue that appium desktop paints the screenshot in the incorrect rotation?

did you say your app also needs to be in portrait mode? why not rotate the simulator then?

**Comment by YevheniiaHre** [comment]
For me, the main thing is that the identification of the fields matches the screenshot, and not in different orientations

**Comment by YevheniiaHre** [comment]
How I can rotate simulator in Inspector?

**Comment by mykola-mokhnach** [comment]
Maybe the [screenshotOrientation](https://github.com/appium/appium-xcuitest-driver#settings-api) setting would be helpful there

**Comment by YevheniiaHre** [comment]
No, it didn't help (

**Comment by busrabasbahcivan** [comment]
Hello,
I face the same issue, could anyone please help with that?

**Comment by busrabasbahcivan** [comment]
Hello,
When I start Appium inspector session with my iPad Air device as landscape, Appium inspector shows the clickable elements as portrait mode. Or when I start inspector session as portrait, it shows the clickable elements as landscape mode. Because of that it is impossible to get the elements' xpaths or ids. Or I am not able to click on elements on Appium.
Does anyone have any solution for this?

My configuration is like this:
MacOS Monterey,
Appium 1.22.2,
Xcode 13.2,
Device: iPad Air (Ios version: 15.2)

Thank you,
Busra

**Comment by jlipps** [comment]
did you try to use the screenshotOrientation capability as suggested?

**Comment by busrabasbahcivan** [comment]
> did you try to use the screenshotOrientation capability as suggested?

Hello Jlipps,
Yes I tried this capability but Appium is behaving same as I mentioned :(
Do you have any other solution?

**Comment by jlipps** [comment]
my next suggestion would be to just write an appium script that gets screenshots and see which orientation they are returned in. if they are returned incorrectly, then i would report an issue to the xcuitest repository, as it would not be an inspector issue at that point.

**Comment by busrabasbahcivan** [comment]
> my next suggestion would be to just write an appium script that gets screenshots and see which orientation they are returned in. if they are returned incorrectly, then i would report an issue to the xcuitest repository, as it would not be an inspector issue at that point.

Hello Jlipps,
Could you please show me an example of that script, then I can write and share the results here?

**Comment by jlipps** [comment]
If I'm understanding your question correctly, then simply refer to the documentation for the appium client you are using in the language you are using. there will be a get screenshot or save screenshot method. you can just use it to save the screenshot to disk and then visually inspect it to see if it matches the correct orientation.

**Comment by jlipps** [comment]
closing due to no response
