### ISSUE TITLE
Appium inspector stuck loading when attach to session

### ISSUE THREAD

**Issue by rio-ap** [appium/appium-inspector#219]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

appium inspector always fail when attach ios simulator session (screenshot attached). used desktop v1.22.0, terminal v1.23 beta, resulting same issue when attach ios simulator session. but this is not happen when attached the android emulator session

xcode version : 13.1
os : monterey 12.0.1

## Screenshot
![image](https://user-images.githubusercontent.com/91875403/143579897-e3e412db-efc4-4d5f-ad1a-73150d1db090.png)

## log error 
`[HTTP] --> GET /wd/hub/session/7b018ec9-5fff-46b5-9870-a91b303e84c3/timeouts
[HTTP] {}
[debug] [W3C (7b018ec9)] Calling AppiumDriver.getTimeouts() with args: ["7b018ec9-5fff-46b5-9870-a91b303e84c3"]
[debug] [XCUITest] Executing command 'getTimeouts'
[debug] [W3C (7b018ec9)] Responding to client with driver.getTimeouts() result: {"command":10000000,"implicit":2000}`

## Environment

- I am running Appium Desktop version 1.22.0.
- I am on (pick one):
    - [x] Mac

**Comment by jlipps** [comment]
What is in the browser console of the inspector? and what version of the appium server are you running the inspector against?

**Comment by rio-ap** [comment]
@jlipps appium server version 1.23.0-beta.0
`What is in the browser console of the inspector?` testing our ios app, i connected the session via 'attach to the session' when running the appium server while appium inspector open

**Comment by jlipps** [comment]
In the inspector app, right click somewhere and click 'inspect'. This loads up a browser dev tools interface. Switch to the console. Here you can see any errors that the inspector (client) itself might have logged. it would also be helpful to have the full server log.

**Comment by jlipps** [comment]
also, what version of the inspector are you running?

**Comment by rio-ap** [comment]
@jlipps using appium inspector version 2021.9.2

for log i cannot provide anymore, because I already reverted the xcode, appium and test env to earlier version (xcode 12.5, appium 1.21)

so i think this issue can be closed, thank you

**Comment by Gowtham8494** [comment]
I'M also facing same issue in emulater 5554  im not able to get the attach to session
