### ISSUE TITLE
Latest Dev Build of Master can't connect to Sauce Labs and BrowserStack

### ISSUE THREAD

**Issue by wswebcreation** [appium/appium-inspector#22]
## The problem

I'm using the latest master and execute the following steps:

1. `npm i` in the root
1. in a new terminal window `cd inspector && npm i && npm run dev`
1. set up a connection with Sauce Labs by providing my username and accesskey + create a config that works with AD 1.18.3

When I try to connect to Sauce Labs I get this error
![image](https://user-images.githubusercontent.com/11979740/100418287-cf7eaf80-3082-11eb-818d-3b2491485abd.png)

and the logs
![image](https://user-images.githubusercontent.com/11979740/100418553-42882600-3083-11eb-9e94-9e6495e67778.png)

## Environment

- I am running Appium Desktop version _latest master_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
Yeah, web2driver doesn't call unescape directly, so the issue is somewhere else, probably in the wdio stack.

**Comment by jlipps** [comment]
Source maps would help us here but don't seem to be working well.

**Comment by KazuCocoa** [comment]
I believe this has been resolved since https://github.com/appium/appium-inspector/issues/23 also worked...

**Comment by wswebcreation** [comment]
Hi @jlipps 

I've checked it and it gives me the following error 
![image](https://user-images.githubusercontent.com/11979740/131312775-d709f319-3115-4455-aee1-055b99ea24ea.png)

it doesn't matter if I use US or EU DC

This is my version 

![image](https://user-images.githubusercontent.com/11979740/131312900-c629188f-3ad6-41b1-8987-d3d896f2a67c.png)

**Comment by jlipps** [comment]
hey @wswebcreation can you pull https://github.com/appium/appium-inspector/pull/118 locally and see if it solves the issue?
