### ISSUE TITLE
Appium Inspector is not acknowledging "deviceName" and "app" capabilities

### ISSUE THREAD

**Issue by dsilveira07** [appium/appium-inspector#221]
## The problem
After run my Appium server and and try to start my Appium Inspector is throwing an error:

_Error
Invalid or unsupported WebDriver capabilities found ("deviceName", "app"). Ensure to only use valid W3C WebDriver capabilities (see https://w3c.github.io/webdriver/#capabilities). If you run your tests on a remote vendor, like Sauce Labs or BrowserStack, make sure that you put them into vendor specific capabilities, e.g. "sauce:options" or "browserstack:options". Please reach out to to your vendor support team if you have further questions._

## Environment

* Appium version: 1.22.0
* Desktop OS/version used to run Appium: Appium Inspector for IOS:
   - App Version: 2021.9.2
   - Electron: 13.5.0
   - Node.js: 14.16.0

* Node.js version (unless using Appium.app|exe): v14.18.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium

## Details

1. I ran my Android simulator
2. I ran my Appium server desktop
3. Opened my Appium inspector and wrote the Desired Capabilities
JSON Representation:
```
{
  "platformName": "Android",
  "deviceName": "tablet_9.94",
  "app": "/Users/dcudeiro/Downloads/imcdi.mobile.junipersales_dev.apk"
}
```
4. Clicked on 'Start Session' button in my Appium Inspector
5. Appium inspector thrown an error:

_Error
Invalid or unsupported WebDriver capabilities found ("deviceName", "app"). Ensure to only use valid W3C WebDriver capabilities (see https://w3c.github.io/webdriver/#capabilities). If you run your tests on a remote vendor, like Sauce Labs or BrowserStack, make sure that you put them into vendor specific capabilities, e.g. "sauce:options" or "browserstack:options". Please reach out to to your vendor support team if you have further questions._

## Link to Appium logs
https://gist.github.com/dsilveira07/78248a6b6ef2105c0833c05d98cd51aa

## Code To Reproduce Issue [ Good To Have ]
JSON Representation:
```
{
  "platformName": "Android",
  "deviceName": "tablet_9.94",
  "app": "/Users/dcudeiro/Downloads/imcdi.mobile.junipersales_dev.apk"
}
```

**Comment by KazuCocoa** [comment]
Was your "Automatically add necessary Appium vendor prefixes on start" enabled?

**Comment by dsilveira07** [comment]
No, I disabled it because I saw how was inserted '_appium_' before "deviceName" and "app". So, it didn't work for me with and without "_Automatically add necessary Appium vendor prefixes on start_" enabled.

**Comment by jlipps** [comment]
well, it is definitely necessary to have the `appium:` in front of app. that is why you got the error that prompted this issue. so when you fix that, what happens?

**Comment by dsilveira07** [comment]
Thanks @jlipps and @KazuCocoa for taking a look at this issue... I tested all possibilities:

1. "_Automatically add necessary Appium vendor prefixes on start_" enabled. 
JSON Representation code:
```
{
  "platformName": "Android",
  "appium:deviceName": "tablet_9.94",
  "appium:app": "/Users/dcudeiro/Downloads/imcdi.mobile.junipersales_dev.apk"
}
```
Error:
_Failed to create session. The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource_


2. "_Automatically add necessary Appium vendor prefixes on start_" unable, but adding `appium:` in front of app:
JSON Representation code:
```
{
  "platformName": "Android",
  "deviceName": "tablet_9.94",
  "appium:app": "/Users/dcudeiro/Downloads/imcdi.mobile.junipersales_dev.apk"
}
```
Error
_Invalid or unsupported WebDriver capabilities found ("deviceName"). Ensure to only use valid W3C WebDriver capabilities (see https://w3c.github.io/webdriver/#capabilities).If you run your tests on a remote vendor, like Sauce Labs or BrowserStack, make sure that you put them into vendor specific capabilities, e.g. "sauce:options" or "browserstack:options". Please reach out to to your vendor support team if you have further questions._


3. "_Automatically add necessary Appium vendor prefixes on start_" unable and not adding any prefix in front of parameters:
JSON Representation code:
```
{
  "platformName": "Android",
  "deviceName": "tablet_9.94",
  "app": "/Users/dcudeiro/Downloads/imcdi.mobile.junipersales_dev.apk"
}
```
Error:
_Invalid or unsupported WebDriver capabilities found ("deviceName", "app"). Ensure to only use valid W3C WebDriver capabilities (see https://w3c.github.io/webdriver/#capabilities).If you run your tests on a remote vendor, like Sauce Labs or BrowserStack, make sure that you put them into vendor specific capabilities, e.g. "sauce:options" or "browserstack:options". Please reach out to to your vendor support team if you have further questions._

**Comment by jlipps** [comment]
Well you definitely need to do the caps as in #1. So then there is something else going wrong. Seems like your host, port, and path information should be double checked.

**Comment by KazuCocoa** [comment]
That the appium server log in _"Automatically add necessary Appium vendor prefixes on start" enabled._?

We need what kind of request reached the server.
