### ISSUE TITLE
Allow Unauthorized Certificates does not work

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium-inspector#23]
## The problem

Like below ssl error was raised with 1.19.0-beta

webdriver: Request failed due to Error: SSL Error: https://xxxx:yyyy/wd/hub/session does not support SSL

This does not happen HTTP connection. Am taking a look...

This happens only requests via webdriverio in web2driver...?
It seems `process.env.STRICT_SSL` does not affect web2driver internal.
Probably we want to set STRICT_SSL = 'false' in https://github.com/webdriverio/webdriverio/blob/e34108325ef1e0d2b8e2306fe407b5d934169777/packages/webdriver/src/request.ts#L123-L126

**Comment by jlipps** [comment]
what's the status here? do we need to update w2d with latest wdio changes?

**Comment by jlipps** [comment]
OK. I will try to upgrade wdio in w2d. Last time I tried there was some new internal dependency on Node.js that made it impossible.

**Comment by KazuCocoa** [comment]
👍 
thanks

**Comment by jlipps** [comment]
well, i tried to update webpack and got lost in a black hole of things not working. still gonna keep working on this but can't do it immediately

**Comment by KazuCocoa** [comment]
Do you think if we can fork webdriverio to our appium repository, add the  webdriverio/webdriverio#6134 in the fork, and build the fork as part of web2driver as a tentative solution for this inspector?

**Comment by jlipps** [comment]
It could be. The issues I'm having right now are related to Webpack though and not WDIO. So once I get bundling straightened out I may be able to simply pull the latest WDIO and have it work. We'll see.

**Comment by KazuCocoa** [comment]
Yes, 2021.8.5 no longer has this issue. 🎉 
So, webpack update fixed this...? (To up to date the webdriverio)

**Comment by jlipps** [comment]
Well, it required adding a whole different request library to webdriverio for web, then it was able to be bundled and we could update w2d.
