### ISSUE TITLE
Unable to execute script mobile: source

### ISSUE THREAD

**Issue by seanmajorpayne** [appium/appium-inspector#230]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

When navigating to `actions` -> `Device` -> `Execute Script` and setting my options to "mobile: source" and the JSON arguments as 

[{"excludedAttributes":["visible"]}] 
{"excludedAttributes":["visible"]}
(Or really any possible variant of trying to pass these arguments) 

I am unable to get the script to execute. Errors have been

args.map() is not a function
or
Invalid JSON

## Environment

- I am running Appium Desktop version 2021.9.2
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux
    
Any advice is appreciated.

**Comment by KazuCocoa** [comment]
what about:
<img width="540" alt="Screen Shot 2022-01-09 at 22 43 40" src="https://user-images.githubusercontent.com/5511591/148727063-a3288dbe-4fda-454f-a711-91a7018404b8.png">

**Comment by bijitbiswas1994** [comment]
Hi @KazuCocoa 
I am still facing the issue
![image](https://github.com/appium/appium-inspector/assets/56245858/eea63749-6f58-4465-8c96-ec43b12e878e)
![image](https://github.com/appium/appium-inspector/assets/56245858/81959590-c329-422a-a619-51114457f3c5)
Even tried the solution provided by you. Didn't work. Any idea where I can get documentation on all the commands we can use
I got one this https://appium.github.io/appium-inspector/latest/session-inspector/commands/ . But didn't got much help

**Comment by eglitise** [comment]
@bijitbiswas1994 you need to put `bundleId` in quotes as well, like in the example.

**Comment by bijitbiswas1994** [comment]
Same error 

https://github.com/appium/appium-inspector/assets/56245858/37af33c4-59b8-4795-8fb1-c8445e037e5d

**Comment by eglitise** [comment]
You might need to use double quotes instead of single quotes. At least I always use double quotes.

**Comment by jlipps** [comment]
the JSON spec requires double quotes, yes.

**Comment by bijitbiswas1994** [comment]
@jlipps @eglitise 
Getting same error . Please check 

https://github.com/appium/appium-inspector/assets/56245858/3b258214-e9d9-45bb-a702-34d8947e809d

**Comment by eglitise** [comment]
Hmm, I'm not sure which Inspector version you are using, but it does not look like the latest one. I think the syntax here is only supported from 2023.11.1, so I would suggest updating the app.
Alternatively you can just wrap the whole JSON argument in square brackets, like in Kazu's example above, though it is less intuitive.

**Comment by bijitbiswas1994** [comment]
Thank you so much @eglitise . It worked after updating it to latest version  2024.3.4 and it worked like this 
![image](https://github.com/appium/appium-inspector/assets/56245858/fdeb7bc2-d018-443d-a5cb-729b5b926f4f)
