### ISSUE TITLE
Latest Dev Build of Master can't send actions

### ISSUE THREAD

**Issue by wswebcreation** [appium/appium-inspector#24]
# The problem
I'm using the latest master and execute the following steps:

1. `npm i` in the root
1. in a new terminal window `cd inspector && npm i && npm run dev`
1. open the **Actions**-tab, select **Device > Execute Mobile** and send this command `mobile:pressButton` and this JSON argument `{"name": "home"}` it throws and error
![image](https://user-images.githubusercontent.com/11979740/100426449-27bcae00-3091-11eb-9ce9-e1559b758c7f.png)

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
Yes, this is part of a bigger issue. It's an easy but tedious fix. The whole actions section needs to be updated with the correct API names and parameters for webdriverio instead of wd, as Kazu said.
