### ISSUE TITLE
Contexts for Hybrid apps are not shown in the inspector

### ISSUE THREAD

**Issue by wswebcreation** [appium/appium-inspector#25]
## The problem
In the new standalone inspector (nice work by the way) contexts are not shown anymore when you want to inspect a hybrid app. 

When I execute the Action `Context > Context > Get All Contexts` I get this `["NATIVE_APP","WEBVIEW_32521.2","WEBVIEW_32521.3"]` but the UI is not showing the dropdown to switch to the contexts anymore

![image](https://user-images.githubusercontent.com/11979740/119443916-aa65b380-bd2a-11eb-8620-ab91b973cab4.png)

The old version does show it

![image](https://user-images.githubusercontent.com/11979740/119444239-3081fa00-bd2b-11eb-9e5e-b83a92451f76.png)

**Comment by jlipps** [comment]
Context detection was really slowing everything down, so you have to opt in to turning it on by clicking the icon in the left of the toolbar, to make the inspector context aware.

**Comment by wswebcreation** [comment]
Ahh, nice, didn't see that one, thanks. will close it now

**Comment by jlipps** [comment]
thanks for keeping an eye out!
