### ISSUE TITLE
Session is not starting with error asking  whether server is running or not

### ISSUE THREAD

**Issue by AbhijithSKarunakar** [appium/appium-inspector#268]
## The problem
Can't start the session,I tried inspection in web browser and application, even though the appium server is successfully running and the port number is correct, it's showing that error as server is not connected.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Pixel2
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by KazuCocoa** [comment]
I assume this duplicates of https://github.com/appium/appium-inspector/issues/162

**Comment by AbhijithSKarunakar** [comment]
> I assume this duplicates of https://github.com/appium/appium-inspector/issues/162

Yes, but I couldn't resolve the problem even after I provided the remote path as /wd/hub

**Comment by KazuCocoa** [comment]
Then what is the result of `http://127.0.0.1:4723/wd/hub` in your browser?

**Comment by AbhijithSKarunakar** [comment]
{"status":9,"value":{"error":"unknown command","message":"The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource","stacktrace":""}}

**Comment by KazuCocoa** [comment]
Thanks.
then, what was the appium log when you start a session from your inspector? Could you share the configuration of the inspector?

**Comment by AbhijithSKarunakar** [comment]
Thankyou for your support sir, it was an error caused due to the JAVA_HOME that I included the /bin also with the path in Appium configuration .

**Comment by louwjlabuschagne** [comment]
For me it was setting `hostname: process.env.APPIUM_HOST || 'localhost,` to `hostname: process.env.APPIUM_HOST || '127.0.0.1',`

**Comment by salvadorpuntozaragoza** [comment]
> For me it was setting `hostname: process.env.APPIUM_HOST || 'localhost,` to `hostname: process.env.APPIUM_HOST || '127.0.0.1',`

lol this fixed it for me too
