### ISSUE TITLE
Unable to resize appium-inspector window vertically

### ISSUE THREAD

**Issue by kevin-s-wang** [appium/appium-inspector#274]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Unable to resize the window vertically on macOS, buttons/links at the bottom are shielded from the Dock. However, resizing horizontally works fine.
![image](https://user-images.githubusercontent.com/24372742/149440189-8c7a2483-1025-4b4e-b06c-0f990d9235c2.png)

## Environment

- I am running Appium Desktop(Inspector) version _2021.12.2_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by kevin-s-wang** [comment]
Not sure why creating a new one when editing the title
https://github.com/appium/appium-inspector/issues/275

**Comment by thegarlynch** [comment]
This still happen in linux AppImage

**Comment by jlipps** [comment]
the issue here is screen resolution too small
