### ISSUE TITLE
Unable to resize appium-inspector window vertically on macOS

### ISSUE THREAD

**Issue by kevin-s-wang** [appium/appium-inspector#275]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Unable to resize the window vertically on macOS, buttons/links at the bottom are shielded from the Dock. However, resizing horizontally works fine.
![image](https://user-images.githubusercontent.com/24372742/149440189-8c7a2483-1025-4b4e-b06c-0f990d9235c2.png)

## Environment

- I am running Appium Desktop(Inspector) version _2021.12.2_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
What is your screen resolution?

**Comment by kevin-s-wang** [comment]
@jlipps Thank you for the response. Here's the screen resolution `13.3-inch (2560 × 1600)`.
In addition, the OS version is `Monterey 12.1`. The issue is reproducible even after closing the app completely or restarting my laptop. I have also verified that other apps like vscode working properly on my laptop.

**Comment by jlipps** [comment]
Can you provide a full size screenshot? I'm confused why it is below the dock. Did you try pulling it higher? The minimum height is definitely less than 1600 px.

**Comment by kevin-s-wang** [comment]
@jlipps it's taking the full height of my screen except the top menubar. 
![image](https://user-images.githubusercontent.com/24372742/149888740-5f6cd4a5-2874-4413-bbca-da77b6e35717.png)

**Comment by jlipps** [comment]
Your screen resolution doesn't appear to be set to the values you mentioned. Go into Sys Preferences > Displays and see what is written there. You may need to increase it from the default.

**Comment by kevin-s-wang** [comment]
@jlipps Thank you, after setting the display resolution to default, the inspector window is back to normal now. However, it'd better to be able to resize the window under different resolution, because the font size is a bit small under the default resolution.

**Comment by jlipps** [comment]
The inspector window is resizable, down to a certain minimum. We assume that anyone using the inspector has a sufficient screen resolution available. Allowing the inspector to be smaller would make the UI unusable.

Maybe there's also something going on with the way macOS counts pixels. It likes to do things like use more pixels for a given pixel of resolution so that your overall resolution is "smaller" but things are crisper. Not sure what we can do about that.
