### ISSUE TITLE
feature request: mechanism for handling overlapping element regions in the screenshot element selection

### ISSUE THREAD

**Issue by gavrix** [appium/appium-inspector#276]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
The is the problem with visualizing the highlighter areas at least for iOS (because view hierarchies tend to co-exist and overlap on iOS)

Here is video of the problem
![screencast 2022-01-16 22-16-05](https://user-images.githubusercontent.com/354010/149703767-09359387-22af-4ad9-838f-ee5bc2d98474.gif)

I first interact with the Reminders app and then open the details of a particular reminder  (opens in a modal on top) — and can't interact with it, because highlighter rects remain those of the screen underneath the modal. 

After playing a bit with electron debugger I found that there are actually all the highlighter rects for modal, but because all these highlighter rects are plain and ordered by zIndex - it happens that zIndex of those highlighter rects underneath the modal are greater than those of the modal elements. It happens because of how zIndex is calculated here https://github.com/appium/appium-inspector/blob/main/app/renderer/components/Inspector/HighlighterRects.js#L128
<pre>
-> Contrainer1 (zIndex:0)
  -> subContainer (zIndex:1)
    -> subSubContainer (zIndex: 2)
      -> element1 (zIndex: 3)
      -> element2 (zIndex: 3)
  -> subContainer (zIndex: 1)
    -> element3 (zIndex: 2)
</pre>

with hierarchy like this, if element1 or element2 happens to overlap with element3 — they will stay on top. And whats worth — if subSubContainer (zIndex: 2) happens to be fullscreen — it will make element3 completely inaccessible. That's what happens on the video example. 

I have a fix for this problem, which changes how zIndex is being calculated. The idea is that zIndex gets carried over when stepping across sub-hierarchies. My example hierarchy above would become: 
<pre>
-> Contrainer1 (zIndex:0)
  -> subContainer (zIndex:1)
    -> subSubContainer (zIndex: 2)
      -> element1 (zIndex: 3)
      -> element2 (zIndex: 3)
  -> subContainer (zIndex: 4)
    -> element3 (zIndex: 5)
</pre>
This way we can ensure that elements that appear "on top" in the hierarchy are guaranteed to be "on top" in the zIndex meaning.  
What do you think of this idea? I have it implemented and can push a PR with the fix. 

## Environment

- I am running Appium Desktop version 2022.1.2
- I am on (pick one):
    - [X] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
Yes, this is a known issue, and your help in fixing it would be very much appreciated! I know @xcolwell also had an idea about an auto highlight algorithm based on centroids which might be a slightly more "natural" feeling to a user. @xcolwell do you want to write that up on this issue report?

Another option I've thought about is supporting the scroll wheel to scroll through highlighting all elements that share a point with the current pointer.

**Comment by shivamXI** [comment]
I am facing the same issue. Is there another way to find the xpath for native elements till the issue is fixed?

**Comment by jlipps** [comment]
@shivamXI this is a visual issue only and doesn't affect the inspector's ability to suggest xpath selectors. so i'm not sure what problem you're referring to.
