### ISSUE TITLE
Unable to create new session via selenium grid 4 without header charset=utf-8

### ISSUE THREAD

**Issue by andriiTarasov** [appium/appium-inspector#286]
## Appium or Appium Desktop or Appium Inspector?

- [ ✔️ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Inspector issue

## The problem

I tried to create new appium session via selenium grid 4 using Appium Inspector and have response error - "Failed to create session. Content-Type header does not indicate utf-8 encoded json: application/json". 

_4444_ -  port for selenium grid 4. 

cURL data  from Appium Inspector request - 
<code>
curl 'http://127.0.0.1:4444/session' \
  -H 'Connection: keep-alive' \
  -H 'accept: application/json' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) appium-inspector/2022.1.2 Chrome/91.0.4472.164 Electron/13.6.3 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Accept-Language: ru' \
  --data-raw '{"capabilities":{"alwaysMatch":{CAPS_DATA},"firstMatch":[{}]},"desiredCapabilities":{desiredCapabilitiesData}}' \
  --compressed
</code>

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/44271190/151963406-8de467aa-c96e-4514-bcbf-031f57ca3679.png">

Request response - 

<code>
{
  "value": {
    "error": "unknown error",
    "message": "Content-Type header does not indicate utf-8 encoded json: application\u002fjson",
    "stacktrace": ""
  }
}
</code>

<img width="859" alt="image" src="https://user-images.githubusercontent.com/44271190/151963481-a9cf1204-54f0-43d8-ae7b-1966adc4cfc5.png">

Same request sended via cURL with changed _Content type: application/json;charset=utf-8_ was successful. 

## Environment

<img width="307" alt="image" src="https://user-images.githubusercontent.com/44271190/151960581-f1c160ea-aef1-474d-ba54-486cb87fb506.png">

- Appium: v2.0.0-beta.25
- Selenium Grid: 4.1.1 (revision e8fcc2cecf)
- I am running Appium Inspector version _2022.1.2_
- I am on (pick one):
    - [ ✔️] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
I doubt that the code for sending headers is in the inspector. Rather it would be in the webdriver client used, which is web2driver, built on the webdriverio core code. So that would be where the issue is. Can webdriverio start a session on se grid 4?

**Comment by broetchenrackete36** [comment]
Same problem with Grid 4.4.0 and Inspector 2022.8.1. Web2Driver 3.0.4 sends the correct header, so the problem seems to be somewhere else?

**Comment by mykola-mokhnach** [comment]
@christian-bromann Does wdio send the encoding?

**Comment by christian-bromann** [comment]
Unless defined differently by the user WebdriverIO sends this [default header](https://github.com/webdriverio/webdriverio/blob/f7a5fa64c3cf06d03ca7fef578fd07a7537b0dfc/packages/webdriver/src/request/index.ts#L45):

> `'Content-Type': 'application/json; charset=utf-8',`

**Comment by jlipps** [comment]
Can you look in the network panel of the dev tools to see what headers are sent by the inspector?

**Comment by jlipps** [comment]
just curious, what if you try to start a session with web2driver on its own (not the inspector)?

**Comment by jlipps** [comment]
I just double checked, and there's no code in the inspector that sets content-type. so it'd either be an issue with web2driver or ... something we can't change about how browser APIs work?

**Comment by broetchenrackete36** [comment]
It looks like it should be fixable with the following, but I couldn't get it to work with the inspector, only with my test electron app:

```javascript
  browserWindow.webContents.session.webRequest.onBeforeSendHeaders(function(details, callback) {
    const requestHeaders = {...details.requestHeaders, ...{
        ['content-type']: 'application/json; charset=utf-8'
    }};
    callback({cancel: false, requestHeaders})
  });
```

**Comment by jlipps** [comment]
yikes, that's strange that electron is doing something to override headers! i guess we'll need to play around with something like this until it works. i think we'd also want to just add `; charset=utf-8` to an existing `content-type` header if one already exists.

**Comment by me355** [comment]
The red

**Comment by KazuCocoa** [comment]
With:
```
    const serverOpts = {
      hostname: host,
      port: parseInt(port, 10),
      protocol: https ? 'https' : 'http',
      path,
      connectionRetryCount: CONN_RETRIES,
      connectionRetryTimeout: CONN_TIMEOUT,
      headers: {
        'content-type': HEADERS_CONTENT,
        'x-kazu-content-type': HEADERS_CONTENT
      }
```
in this repository passed to https://github.com/webdriverio/webdriverio/blob/6bbe1cf371f06e517ac62a4e02724c8b610803cb/packages/webdriver/src/request/browser.ts#L52. The options had below:

```
{
    "method": "POST",
    "retry": 0,
    "followRedirect": true,
    "responseType": "json",
    "throwHttpErrors": false,
    "https": {
        "rejectUnauthorized": true
    },
    "headers": {
        "Content-Type": "application/json; charset=utf-8",
        "Connection": "keep-alive",
        "Accept": "application/json",
        "User-Agent": "webdriver/7.16.14",
        "content-type": "application/json; charset=utf-8",
        "x-kazu-content-type": "application/json; charset=utf-8",
        "Content-Length": "216"
    },
    "timeout": 300000,
    "json": {
        "capabilities": {
            "alwaysMatch": {
                "appium:newCommandTimeout": 3600,
                "appium:connectHardwareKeyboard": true
            },
            "firstMatch": [
                {}
            ]
        },
        "desiredCapabilities": {
            "appium:newCommandTimeout": 3600,
            "appium:connectHardwareKeyboard": true
        }
    },
    "url": "http://localhost:4723/session"
}
```

but the request did not have `application/json; charset=utf-8`. It only had `application/json`. Maybe... ky behaved something unexpected in a specific case... `x-kazu-content-type"` was added expectedly, so the custom headers in webdriverio itself should have worked.

Hm..
