### ISSUE TITLE
feature request: support session id retrieval from Grid 4 /status endpoint instead of just Appium's /sessions endpoint

### ISSUE THREAD

**Issue by andriiTarasov** [appium/appium-inspector#287]
## Appium or Appium Desktop or Appium Inspector?

- [ ✔️ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Inspector issue

## The problem

Unable to attach to appium session created via selenium grid using port of grid. 

#### Steps to reproduce:
- Start selenium grid 4.x and appium 2.x
- Start new appium session via selenium grid like via cURL request (4444 - port for selenium grid 4)

<code>
curl 'http://127.0.0.1:4444/session' \
  -H 'Connection: keep-alive' \
  -H 'accept: application/json' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) appium-inspector/2022.1.2 Chrome/91.0.4472.164 Electron/13.6.3 Safari/537.36' \
  -H 'content-type: application/json;charset=utf-8' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Accept-Language: ru' \
  --data-raw '{"capabilities":{"alwaysMatch":{CAPS_DATA},"firstMatch":[{}]},"desiredCapabilities":{desiredCapabilitiesData}}' \
  --compressed
</code>

- Open Appium Inspector and using grid port value (4444) set to remote port
- Open "Attach to Session..." page and check that appium session displayed on select with sessions list

#### Expected result:
- Select with sessions display all available sessions from selenium grid

#### Actual result:
- Request for reading list of sessions try read sessions from endpoint /sessions, but grid can return session_ids informations from /status endpoint

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/44271190/152008538-d7eefa35-f97e-42c5-81ff-d81a1ca1fff8.png">

Response from /sessions endpoint - 
<code>
{
  "value": {
    "error": "unknown command",
    "message": "Unable to find handler for (GET) \u002fsessions",
    "stacktrace": ""
  }
}
</code>
<img width="937" alt="image" src="https://user-images.githubusercontent.com/44271190/152008847-42ef723b-9b32-4973-8c1a-109ef4dad999.png">

## Environment

<img width="307" alt="image" src="https://user-images.githubusercontent.com/44271190/151960581-f1c160ea-aef1-474d-ba54-486cb87fb506.png">

- Appium: v2.0.0-beta.25
- Selenium Grid: 4.1.1 (revision e8fcc2cecf)
- I am running Appium Inspector version _2022.1.2_
- I am on (pick one):
    - [ ✔️] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
OK, so this is a feature request to make Grid 4 compatible with the inspector. Got it.

**Comment by krishtoautomate** [comment]
++ appium _/sessions_ end-point is failing when connected to selenium Grid 4.

**Comment by KazuCocoa** [comment]
Perhaps... need to a switch or combine the results of both `/sessions` and `/status`..?
