### ISSUE TITLE
Macos 12.1 refuses to start Appium Inspector

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [appium/appium-inspector#292]
## The problem

Macos 12.1 refuses to start Appium Inspector.

<img width="372" alt="image" src="https://user-images.githubusercontent.com/14184826/152601366-39a752f9-5554-42b2-90a1-b7caf7e32ede.png">

I'm not sure what else to add.

## Environment

- I am running Appium Inspector version 2021.12.2.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Did you follow https://github.com/appium/appium-inspector#installing-on-macos?
