### ISSUE TITLE
Query : Is there a way to expose the driver object so that it can be accessed from the Appium Inspector console to try out quick commands ?

### ISSUE THREAD

**Issue by akash10anand** [appium/appium-inspector#295]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I was wondering if there ia way the Driver object can be exposed so that it can be accessed from the Inspector console and some small driver commands can be tried out programatically.

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
No, this isn't part of the vision of the Inspector. It's designed to be a GUI tool. If you want more of a REPL then you can simply load up a WebdriverIO object in a node session, attach to the same session as is running in the inspector, and run commands that way.

**Comment by akash10anand** [comment]
Thanks @jlipps .
