### ISSUE TITLE
On Mac Monterey 12.2 not able to open Appium Desktop

### ISSUE THREAD

**Issue by euexplorer** [appium/appium-inspector#317]
Appium Desktop issue

## The problem

Hi i have Mac Monterey 12.2 and the dmg gets downloaded in downloads then i run command xattr -cr Appium-Inspector-mac-2022.1.2.dmg after that i install it in applications. Now i cant open it. what can be done?

## Environment

- I am running Appium Desktop version _<1.22.1>_.
- I am on (pick one):
    - [ Monterey 12.2] Mac
    
<img width="261" alt="Screen Shot 2022-02-18 at 12 38 38" src="https://user-images.githubusercontent.com/99884666/154676417-589eb8d0-4054-41f1-ba71-a389d8f2ab7e.png">

**Comment by jlipps** [comment]
Under the "General" tab of the "Security & Privacy" preference pane in System Preferences, what is the value selected for "Allow apps downloaded from"?

Another thing you can try is copying the inspector .app from the dmg to your filesystem first, then running `xattr -cr` on the .app file.

**Comment by euexplorer** [comment]
To do this? can you tell me the steps?
As when i double click on dmg it unzips and only gives one option is to move the .app to applications folder. How can i extract only .app file from dmg?

**Comment by KazuCocoa** [comment]
>  move the .app to applications folder

Then, I think you can find the `.app` in the `/Applications`. Then, please call `xattr -cr` command to the inspector app in the `/Applications`

**Comment by euexplorer** [comment]
@KazuCocoa worked!! thanks
