### ISSUE TITLE
Failed to create session. Request timed out when I try to inspect a mobile app from an iOS real device located in Saucelabs cloud platform

### ISSUE THREAD

**Issue by aguillamon88** [appium/appium-inspector#321]
Hi, 

I'm trying to inspect a mobile app from an iOS real device located in Saucelabs cloud platform. Appium server is running on this host.

I can connect with Saucelabs and the app launches without problem on an iOS device. However Appium Inspector crashes after 2 minutes once I pressed the "Start Session" button.

![image](https://user-images.githubusercontent.com/100204888/155168593-83addacb-78f1-4dac-9575-5c6cd784839d.png)

In this case I used these capabilities:

{
  "platformName": "iOS",
  "appium:platformVersion": "13.1.3",
  "appium:deviceName": "iPhone_11_Pro_Max_13_cx",
  "appium:app": "storage:d7ece600-96c9-442a-bffb-c91669af5425",
  "appium:autoAcceptAlerts": true,
  "sauce:options": {
    "appiumVersion": "1.22.2",
    "deviceType": "phone",
    "orientation": "portrait",
    "name": "Appium Desktop Session"
  }
}

Anyone knows what happens? I've tried to use all the timeout capabilities I found with same result.

I use the last Appium Inspector release (v.2022.2.1) for Windows.

**Comment by KazuCocoa** [comment]
> However Appium Inspector crashes after 2 minutes once I pressed the "Start Session" button.

I'm confused, is this crash or the timeout error?

----

If timeout...:

Could you provide the full appium server log in both succeeded and the inspector's cases?
The message is probably the client did not get a new session request response in timeout.

**Comment by jlipps** [comment]
Yeah, what is the Appium log from Sauce?

**Comment by Vgalla376** [comment]
I am facing the same issue, is this resolved ?

**Comment by Vgalla376** [comment]
> I'm getting this too. The Appium session is starting fine on Sauce Labs, but it times out on the client. I'm going to check if it's something in web2driver

When its going to be resloved

**Comment by jlipps** [comment]
it's already resolved if you build from source. we're blocked from publishing a new release at the moment.

**Comment by Vgalla376** [comment]
> it's already resolved if you build from source. we're blocked from publishing a new release at the moment.

build from source - meaning ?

**Comment by jlipps** [comment]
Download the source code and follow the developer instructions for building the app yourself.

**Comment by Vgalla376** [comment]
> Download the source code and follow the developer instructions for building the app yourself.

Where can I find the developers Instructions?

**Comment by jlipps** [comment]
in the readme: https://github.com/appium/appium-inspector#development

**Comment by jlipps** [comment]
new release is also out with this fix.

**Comment by christophss** [comment]
@jlipps , does this fix only pertains to attachSession or can it be made even for the remote session creation as well? I am facing the same issue while creating a new session in sauce labs which sometimes takes close to 2.5 to 3 minutes. I tested with 2022.5.4 app version but still having the same issue. Wanted to confirm!

**Comment by jlipps** [comment]
@dpgraham any ideas about this sauce labs issue?

**Comment by Theofylrx** [comment]
@jlipps Was this issue Resolved for when creating a remote session?, i am still getting it when creating a new session using Saucelabs, i checked even on the latest version : 2022.8.1 but still getting the same issue.
