### ISSUE TITLE
Appium Inspector 1.17.1 creates uncompilable Java8 code

### ISSUE THREAD

**Issue by gchickma** [appium/appium-inspector#333]
## The problem

Appium Inspector 1.17.1 creates uncompilable Java8 code.

## Environment

* Appium version: 1.17.1
* Desktop OS/version: Mac OSX Catalina Version 10.15.6 (19G2021)
* Android 10
* Emulator/simulator (Samsung S8)
* Appium.app

## Details

Recording a simple swipe action with start and end point produces:

```
(new TouchAction(driver))
  .press({x: 684, y: 244})
  .moveTo({x: 678: y: 2505})
  .release()
  .perform()
```

Needed to correct the {x: 684, y: 244} type sections and also needed to add a semi colon at the end.

I updated the statement to look like this:

```
(new TouchAction(driver))
  .press(PointOption.point(684, 244))
  .moveTo(PointOption.point(678, 2505))
  .release()
  .perform();
```

**Comment by jlipps** [comment]
@gchickma would you be interested in contributing a fix to the java code generator? sounds like it should be relatively simple given that you have identified what needs to be changed already. Looks like it would be located here: https://github.com/appium/appium-inspector/blob/main/app/renderer/lib/client-frameworks/java.js#L114-L121

**Comment by gchickma** [comment]
@jlipps sure I can take a crack.  I'm a bit swamped with work this week however over spring break I can submit a PR

**Comment by jlipps** [comment]
awesome thanks @gchickma! the issues linked to this one contain some hints about the types of changes required, I think.

**Comment by gchickma** [comment]
@jlipps https://github.com/appium/appium-inspector/pull/373

**Comment by jlipps** [comment]
thanks!
