### ISSUE TITLE
AppiumInspector doesn't load view

### ISSUE THREAD

**Issue by GDiBiase** [appium/appium-inspector#340]
## Appium Inspector

Appium Inspector does not load the screen displayed in the simulator but remains continuously loading. 
The app is installed and opened successfully.

Capabilities:
`{
  "appium:platformName": "iOS",
  "appium:app": "filePathToAppFileToTest",
  "appium:automationName": "XCUITest",
  "appium:deviceName": "iPhone 13 Pro Max",
  "appium:platformVersion": "15.4"
}`

On the Appium Server log go on timeout.

Maybe is this the problem ? 
```
[W3C (60af6045)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
[W3C (60af6045)]     at JWProxy.command (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:274:13)
[W3C (60af6045)]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

## Environment

- I am running Appium Desktop version 1.22.2
- I am running Appium Inspector version 2022.3.2
- I am on:
    - [ ] MacBook Pro M1 Monterey 12.3

**Comment by RSUIAutomation** [comment]
Also seeing this today after ios updated to 15.4

**Comment by RSUIAutomation** [comment]
I also am seeing this issue on the feb version of appium inspector.

**Comment by judsoncarver** [comment]
My team just updated our inspectors and those on Intel see [#339](https://github.com/appium/appium-inspector/issues/339) and M1, we're getting this issue here.

**Comment by zgordon02** [comment]
> My team just updated our inspectors and those on Intel see [#339](https://github.com/appium/appium-inspector/issues/339) and M1 users see this issue here.

I am on an intel machine, the fix mentioned in this thread worked for me. It isn't ideal, but it works. https://github.com/appium/appium-inspector/issues/343

That being said, even once upgrading I am seeing the issue mentioned here on an intel machine. I'm going to rollback to a 15.2 simulator and see if that fixes the issue

**Comment by judsoncarver** [comment]
@zgordon02 Yep, we performed the codesign mentioned in #339 but as you said, once we're in to the app we cannot get past loading spinner.

**Comment by jlipps** [comment]
The inspector doesn't know anything about iOS simulators or versions. It just runs Appium commands. In this case the issue is with iOS or with an Appium driver, not the inspector. I've seen this too, where sometimes getting the page source or a screenshot can literally take minutes of time. I'll leave this issue open for a bit but I'm pretty sure it has nothing to do with the inspector. To confirm you could run an Appium script from the command line and verify whether getting the source and screenshot complete any faster.

**Comment by judsoncarver** [comment]
@zgordon02 thanks, can confirm it works with 15.2.

**Comment by GDiBiase** [comment]
Any update on this ? 
Can confirm on iOS 15.2 works without problems.
Still error on iOS 15.4.

BR

**Comment by MartinsMickus** [comment]
Here is the fix for the issue:
https://github.com/appium/appium/issues/16604

**Comment by RSUIAutomation** [comment]
> Here is the fix for the issue: [appium/appium#16604](https://github.com/appium/appium/issues/16604)

If appium gui still runs 1.22.2 this fix wont be available for appium inspector.

**Comment by GDiBiase** [comment]
using Appium GUI version: 1.22.3 the problem does not appear.
using Appium 2.0 last version the problem appear.
also, using Appium 2.0 last version a new bug appear on the driver list.

**Comment by RSUIAutomation** [comment]
> using Appium GUI version: 1.22.3 the problem does not appear. 

Just pulled up their releases and it shows latest is 1.22.2? Where did you find 1.22.3? https://github.com/appium/appium-desktop/releases

**Comment by RSUIAutomation** [comment]
You can run appium server using the CLI version and then run the inspector.

**Comment by RSUIAutomation** [comment]
That correct as I mentioned in my last post but thats not the GUI version, not sure how to point the GUI to use it, after I installed it my GUI button still shows run server using 1.22.2.

**Comment by RSUIAutomation** [comment]
The GUI says it powered by separately installed appium server but when I npm install to -g or not it doesn't update the GUIs server version.

**Comment by jlipps** [comment]
There are two GUI apps, this Inspector and then a Server app. The Server app is not necessary to use the Inspector. You just need any running Appium server. I don't recommend using the GUI Server as it is not updated frequently and will probably not be updated to Appium 2.0, at least not for some time.

**Comment by GDiBiase** [comment]
@RSUIAutomation sorry, my bad, i wrote GUI instead of CLI!

With CLI version no problem, with GUI version appear the Error with version iOS 15.4

Just DON'T use the GUI version but use the Appium CLI with last version but NOT the Appium 2.0!

**Comment by KazuCocoa** [comment]
I've created https://github.com/appium/appium-desktop/releases/tag/v1.22.3 that has appium 1.22.3 cli internally.

**Comment by ManojBadiger** [comment]
> ## Appium Inspector
> Appium Inspector does not load the screen displayed in the simulator but remains continuously loading. The app is installed and opened successfully.
> 
> Capabilities: `{ "appium:platformName": "iOS", "appium:app": "filePathToAppFileToTest", "appium:automationName": "XCUITest", "appium:deviceName": "iPhone 13 Pro Max", "appium:platformVersion": "15.4" }`
> 
> On the Appium Server log go on timeout.
> 
> Maybe is this the problem ?
> 
> ```
> [W3C (60af6045)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
> [W3C (60af6045)]     at JWProxy.command (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:274:13)
> [W3C (60af6045)]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
> ```
> 
> ## Environment
> * I am running Appium Desktop version 1.22.2
> * I am running Appium Inspector version 2022.3.2
> * I am on:
>   
>   * [ ]  MacBook Pro M1 Monterey 12.3

Im also have same device not running
