### ISSUE TITLE
Here there is no guide for Installing on Linux (Ubuntu ) here 

### ISSUE THREAD

**Issue by leonidaa** [appium/appium-inspector#341]
## Appium Inspector
 

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Inspector  issue

## The problem

Here there is no guide for Installing on Linux (Ubuntu ) here 
https://github.com/appium/appium-inspector

_Replace this section with a description of your issue_

and I know how to install and I would like to share with others this too 

## Environment

- I am running  
Appium v1.22.2

- I am on (pick one):
   
    - [ ] Linux

**Comment by jlipps** [comment]
I don't have Linux so I can't confirm that things work on Linux. I would welcome someone to add any Linux installation instructions to the README (or fix any issues with Linux packaging, we are just relying on the builder to do the right thing).

**Comment by leonidaa** [comment]
Regarding installation
I am quoting the appImage project page here:

AppImages can be downloaded and run without installation or the need for root rights.

Making it executable
You can make the appImage executable as follows:

chmod a+x exampleName.AppImage
Executing it
You can execute an appImage as follows:

./exampleName.AppImage
I have follow this steps and I was working . I am a newbie using Linux commands so I think this will be useful for others like me . 
https://askubuntu.com/questions/774490/what-is-an-appimage-how-do-i-install-it
I think the confirmation is coming from the credibility of the source that I am citing , just this lines I wanted to add into Readme , because that it is all . 
As a newbie in Github open source community this will be my contribution as a long time user of opensource software and I like to have this add it . Thank you .

**Comment by jlipps** [comment]
Sounds great @leonidaa please by all means do open a pull request so that we can include your contribution to the README.

**Comment by saifulla45** [comment]
@leonidaa Thanks a lot for mentioning the step clearly. It Help me a lot
