### ISSUE TITLE
cannot open appium inspector in macOS montery (12)

### ISSUE THREAD

**Issue by Hamzastreamwide** [appium/appium-inspector#343]
## Appium or Appium Desktop?

appium inspector

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

i installed the lastest version of appium inspector and when i right click then open , an [error] message appears 

## Environment

- I am running Appium Desktop version 2022.3.2
- I am on (pick one):
    - [ ] Mac
<img width="258" alt="Screen Shot 2022-03-17 at 09 49 28" src="https://user-images.githubusercontent.com/72748407/158772720-80ee2f7e-aa9d-468b-a59e-2612b56728d2.png">

**Comment by Hamzastreamwide** [comment]
xattr -cr "/Applications/Appium Inspector.app" i tried this by the way and it didnt help

**Comment by Hamzastreamwide** [comment]
codesign --deep --force --verbose --sign - /Applications/Appium\ Inspector.app if  fixed it :) can u add this to the description

**Comment by jlipps** [comment]
thanks. looks like somehow code signing needs to be set up properly in our release CI

**Comment by AshaSaxena11** [comment]
> codesign --deep --force --verbose --sign - /Applications/Appium\ Inspector.app if fixed it :) can u add this to the description

Yes this indeed worked , just use same command on Terminal.
I use below command 
Command : codesign --deep --force --verbose --sign - /Applications/Appium\ Server\ GUI.app
Response : /Applications/Appium Server GUI.app: replacing existing signature
/Applications/Appium Server GUI.app: signed app bundle with Mach-O thin (x86_64) [io.appium.desktop]

And post that when i open it worked

**Comment by KazuCocoa** [comment]
let me pin this issue

**Comment by jlipps** [comment]
A new release has been published without these issues: https://github.com/appium/appium-inspector/releases/tag/v2022.5.1

**Comment by soumyaranjan89** [comment]
> > codesign --deep --force --verbose --sign - /Applications/Appium\ Inspector.app if fixed it :) can u add this to the description
> 
> Yes this indeed worked , just use same command on Terminal. I use below command Command : codesign --deep --force --verbose --sign - /Applications/Appium\ Server\ GUI.app Response : /Applications/Appium Server GUI.app: replacing existing signature /Applications/Appium Server GUI.app: signed app bundle with Mach-O thin (x86_64) [io.appium.desktop]
> 
> And post that when i open it worked

Any idea how to revert this change? After i ran this command now I am blocked and getting below error while building the xcode project
Command CodeSign failed with a nonzero exit code

**Comment by jlipps** [comment]
You don't need to run that command anymore.
