### ISSUE TITLE
Appium Inspector is not taking the snapshot of the app screen.

### ISSUE THREAD

**Issue by rraj2017** [appium/appium-inspector#345]
## Appium or Appium Desktop?
Appium Desktop version -1.22.2
Appium inspector version -2022.2.1
xcode version - 13.3
Mac Os version- 12.2.1
Device Os version - 15.4
Device - iPhone 11 simulator

## The problem

Appium Inspector is not taking the snapshot of the app screen.
## Environment

- I am running Appium Desktop version 1.22.2
- I am on (pick one):
    - [ ] Mac

**Comment by KazuCocoa** [comment]
Potentially it is https://github.com/appium/appium/blob/master/CHANGELOG.md#changes-in-version-1223-from-1222
Please try out appium cli 1.22.3.

**Comment by rraj2017** [comment]
@KazuCocoa 
When I downloaded appium cli I got version 1.22.2 by default ?
Now how can I upgrade the appium cli to 1.22.3?

**Comment by KazuCocoa** [comment]
You can re-install it via `npm` package command.
https://www.npmjs.com/package/appium

**Comment by RSUIAutomation** [comment]
Appium gui which seems to need to be run in order to run inspector still shows 1.22.2 and updating appium cli via npm didnt affect the gui.

**Comment by jlipps** [comment]
> Appium gui which seems to need to be run in order to run inspector

The Inspector does not rely on the Appium GUI. You can even just use the inspector on the web: https://inspector.appiumpro.com. All it requires is a recent and running Appium server and for you to connect to it with the appropriate connection details.
