### ISSUE TITLE
[Need Help] Setting up web driver in iOS device

### ISSUE THREAD

**Issue by ps1logi** [appium/appium-inspector#350]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment
* Desktop OS/version used to run Appium: Mac OS Montreal

* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: 2.22

## Details

I m have installed latest appium deaktop release on Feb 22,2022
I couldn't run script to before installing web driver to iPhone. 
Can you please share the steps to update web driver to. Iphone and also steps to start appium inspector. 

Thank in advance.

**Comment by KazuCocoa** [comment]
Please share the appium log.

Did you have a valid provisions profile as https://appium.io/docs/en/drivers/ios-xcuitest-real-devices/?

**Comment by KazuCocoa** [comment]
https://discuss.appium.io/ also may help.

**Comment by ps1logi** [comment]
@KazuCocoa i kindly request you update the same in github also because in error which appium as github link and it has older version setup. Update it the github or link shown in error from appium

**Comment by ps1logi** [comment]
> https://discuss.appium.io/ also may help.

I couldn’t find the solution for me

**Comment by ps1logi** [comment]
> Please share the appium log.
> 
> Did you have a valid provisions profile as https://appium.io/docs/en/drivers/ios-xcuitest-real-devices/?

Thank you so much I was searching for this

**Comment by KazuCocoa** [comment]
Could you share your error logs in the appium server?

I guessed you were getting xcode error 65, then the URL helped. Then, the real device page helps. (It expects npm cli as our main stream). Afaik, newer the GUI part differs in Xcode versions, but basic steps to setup/ensure the sign are almost the same.
As _Make sure the provisioning profile has [iOS Distribution certificate](https://developer.apple.com/support/certificates/)_ in https://appium.io/docs/en/drivers/ios-xcuitest-real-devices/#troubleshooting-ideas, if you used free account's one, probably it may also fail via xcodebuild as Apple's security design.

**Comment by ps1logi** [comment]
@KazuCocoa As per our discussion, i m attaching the lo
[fail_log_appium_28032022.txt](https://github.com/appium/appium-inspector/files/8361645/fail_log_appium_28032022.txt)
g

**Comment by jlipps** [comment]
closing due to no response

**Comment by ps1logi** [comment]
@KazuCocoa i was able to fix it based on your comment 
Sorry for the delay in response
