### ISSUE TITLE
Simulator reflected on appium simulator doesn’t work properly using Espresso

### ISSUE THREAD

**Issue by pabloleal1** [appium/appium-inspector#351]
## The problem

Using Espresso as appium:automationName capability, once I tap on the emulator refelected on the appium inspector to look for the element on the app source, others elements are shown instead the element I clicked on
## Environment

* Appium version: 1.22.0
* Mobile platform/version under test: Android Emulator

Thanks you ever so much.

**Comment by jlipps** [comment]
I think we would need some more details to understand the issue. It might help to start with a set of screenshots or a video describing the problem.

**Comment by Hristovski** [comment]
Well, I've seen this and the element highlighted borders look gigantic. For example, a small button on the left takes up the whole screen and overlaps a bit off the right side of the screen.
The elements are not displayed proportionally to the left-side display. It looks like the displayed vs. actual element dpi is not correct or proportionally calculated.
There was a similar issue with iOS with one of the previous versions - (appium-desktop) 1.19 or 1.20

**Comment by pabloleal1** [comment]
Hi @jlipps due to legal matters I can't set any log or video, but the problem we faced is what @Hristovski exactly said.

Thanks!

**Comment by jlipps** [comment]
OK. Thanks for the extra detail, but I can't say I understand the problem yet. Without some kind of repro case I don't think I'll be able to help. But the code is open source so maybe with your understanding of the issue and ability to reproduce it locally, you can submit a fix.
