### ISSUE TITLE
Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70 on Xcode 13.2.1 and iOS 15.4

### ISSUE THREAD

**Issue by Thuytien** [appium/appium-inspector#354]
## Appium or Appium Desktop?
<img width="304" alt="Screen Shot 2022-03-30 at 9 41 00 AM" src="https://user-images.githubusercontent.com/6836601/160741552-5e6d7d35-c853-476d-89b3-868c51310ef7.png">

- I have verified that my issue occurs with both Appium and Appium Inspector

## The problem

- I couldn't build testing app after upgrade iOS version on my iPhone 7+ to 15.4

## Environment

- I am running Appium Inspector version: 2021.9.2
- I am on (pick one):
    - Mac: version 12.3
    - iOS: version 15.4
    - Appium: version 1.22.3
    - Xcode: version 13.2.1

**Comment by jlipps** [comment]
> I have verified that my issue occurs with both Appium and Appium Inspector

Then it should not be reported here. Please fill out a full issue report at https://github.com/appium/appium/issues
