### ISSUE TITLE
calls "codesign --deep --sign - Appium\ Inspector.app" in a release task

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium-inspector#355]
if prevent https://github.com/appium/appium-desktop/issues/2000 

Potentially the adhoc sign should be a user local one. Then, current readme is enough for now.

**Comment by KazuCocoa** [comment]
will take a look

**Comment by jlipps** [comment]
now resolved by simply using a valid developer cert (https://github.com/appium/appium-inspector/releases/tag/v2022.5.1)
