### ISSUE TITLE
Appium Inspector is not taking screenshot on a particular App installed on Android

### ISSUE THREAD

**Issue by pthakel** [appium/appium-inspector#357]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
I have installed an Android App on Android Studio Emulator as well as on a real Android phone.  I am able to start a session on Appium Inspector and get the screenshot and highlight the elements on Android System screens as well as Apps downloaded from Google Play Store.

However, for the single App I installed with a direct apk, Appium Inspector just doesn't display the screenshot.  Why is it?  Is there some apk requirements that may be missing on my App, e..g does the App needs to have debugging included?

- I am running Appium Desktop version _<2022.2.1>_.
- I am on (pick one):
    - [ ] Mac
    - [ x] Windows    - [ ] Linux

**Comment by jlipps** [comment]
Does Appium retrieve the screenshot outside of the inspector? The inspector is just an Appium client. You can also open up the debug tools in the inspector itself to see if there are any errors in the console.

**Comment by pthakel** [comment]
I do see an error :
[2022-04-04 10:32:17][WD Proxy] Proxying [GET /screenshot] to [GET http://127.0.0.1:8200/wd/hub/session/ec377211-80c6-42a6-ba50-8815bdb34b6b/screenshot] with no body
[2022-04-04 10:32:17][WD Proxy] Got response with status 500: {"sessionId":"ec377211-80c6-42a6-ba50-8815bdb34b6b","value":{"error":"unable to capture screen","message":"Failed to capture a screenshot. Does the current view have 'secure' flag 

Not sure what 'secure' flag means and how to set it differently?  I tried to have the Inspector 'use proxy' with proxy address as well as not checked 'proxy'.  They don't seem to make a difference.

**Comment by pthakel** [comment]
I found https://github.com/appium/appium-uiautomator2-server/issues/275 and this is probably the answer to my question related to the 'secure' flag.  Thanks.
