### ISSUE TITLE
Building the app on a OS 12.3 will throw an error.

### ISSUE THREAD

**Issue by wswebcreation** [appium/appium-inspector#362]
## Appium or Appium Desktop?

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

If you upgraded your Mac to 12.3 you will have issues with building the App, it will throw an error like this

```
Exit code: ENOENT. spawn /usr/bin/python ENOENT
```

This is a know issue and, as far as I understood, due to the fact that Apple removed python 2.7. This issue describes this 
 https://github.com/electron-userland/electron-builder/issues/6726, a "simple" upgrade to `"electron-builder": "23.0.2",` will solve this.

I've upgraded my own fork and as far as I can see it works. I didn't create a PR yet because I'm not sure if you are already working on it yet, but if you want I can create one

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
hmm, usually dependency updates will be proposed automatically. do you see anything having been merged like that? otherwise please do create a PR.

**Comment by wswebcreation** [comment]
Hi @jlipps 

I'm not sure, the dep updates, that become PRs, are AFAIK only security fixes. I'll create a PR for this

**Comment by wswebcreation** [comment]
Done, see https://github.com/appium/appium-inspector/pull/363
