### ISSUE TITLE
I can not connect  windowsAppDriver !

### ISSUE THREAD

**Issue by zhugunzi** [appium/appium-inspector#372]
![image](https://user-images.githubusercontent.com/30099116/162884657-2087a63f-2ff3-4421-b474-24061a62099f.png)

**Comment by zhugunzi** [comment]
Invalid or unsupported WebDriver capabilities found ("automationName", "app", "appTopLevelWindow "). Ensure to only use valid W3C WebDriver capabilities (see https://w3c.github.io/webdriver/#capabilities).If you run your tests on a remote vendor, like Sauce Labs or BrowserStack, make sure that you put them into vendor specific capabilities, e.g. "sauce:options" or "bstack:options". Please reach out to to your vendor support team if you have further questions.

**Comment by KazuCocoa** [comment]
Maybe i see the reason. You used appium 2.0, which required w3c protocol, but WinAppDriver did not support it.
You should use appium 1.x, or wait for Microsoft will release W3C compatible WinAppDriver.
https://github.com/Microsoft/WinAppDriver
