### ISSUE TITLE
Appium Inspector - The App Source doesn't have a vertical scroll bar. Which Version does?

### ISSUE THREAD

**Issue by EricProgrammerBLM** [appium/appium-inspector#383]
Appium Inspector 2022.2.1 for Windows

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

App Source inside of the Appium Inspector won't allow me to scroll down to see any elements that may pass the page.

## Environment

- I am running Appium Desktop version2022.2.1
- I am on (pick one):
    - [ ] Mac
    - [x ] Windows
    - [ ] Linux
![Appium Scrolling](https://user-images.githubusercontent.com/67605888/166394872-19fa3573-3911-4a30-b06c-df49b2e3d263.png)

**Comment by jlipps** [comment]
Out of curiosity, can you scroll via your scroll wheel or mouse pad?

**Comment by EricProgrammerBLM** [comment]
No not at all. I ended up downgrading to the Appium Desktop Version. 1.21.0
for Windows.

**Comment by jlipps** [comment]
OK, this appears to be a bug on the Windows version then, since it's possible to scroll in all 4 directions on the mac version. We'll have to find someone with a Windows machine to help reproduce and fix.
