### ISSUE TITLE
error when starting recording

### ISSUE THREAD

**Issue by atigm** [appium/appium-inspector#388]
I run web application on Windows but I can't start recording.
commands :

```
npm install
npm run build:browser
set BUILD_BROWSER=1
npm run watch:browser (In package.json, watch:browser script become parcel serve --target browser ./app/renderer/index.html)
```

I have this error when I click on Start recording button :
```Unhandled Exception
An unexpected error occurred with message: _clientFrameworks.default[actionFramework] is not a constructor.
Please kindly open up a bug report at https://github.com/appium/appium-desktop/issues/new.
TypeError: _clientFrameworks.default[actionFramework] is not a constructor
    at RecordedActions.code (http://localhost:1234/renderer.e31bb0bc.js:369942:23)
    at RecordedActions.render (http://localhost:1234/renderer.e31bb0bc.js:370011:34)
    at finishClassComponent (http://localhost:1234/renderer.e31bb0bc.js:20925:35)
    at updateClassComponent (http://localhost:1234/renderer.e31bb0bc.js:20878:28)
    at beginWork (http://localhost:1234/renderer.e31bb0bc.js:22463:20)```

**Comment by jlipps** [comment]
What are you intending to do exactly?

**Comment by atigm** [comment]
The scripts in package.json are adapted to the Linux/Mac OS and not to Windows.
When I launch the inspector in web mode, it works fine on Mac but I get the error on Windows when I click on the Start Recording button.

**Comment by jlipps** [comment]
Just curious, why are you trying to run the inspector in web mode after building from source? If you're already building from source, why not just run the electron app?

Another question: do you get the same error when using the hosted version at https://inspector.appiumpro.com?

**Comment by atigm** [comment]
Thank you @jlipps for your response.

I am only looking to run the application in web mode on Windows. 
It is a personal need.
Is this possible? If so, can someone tell me how to do it ?

Thanks

**Comment by jlipps** [comment]
does this start recording error occur (a) if you run the electron version (`npm run dev`), or (b) if you use the release version?

**Comment by atigm** [comment]
Sorry for delay.
This error occurs when I use release version : `sh release.sh`)

**Comment by atigm** [comment]
I just found the error's origin, it happens when I use another port than the default port (1234)
For example here I use port number 1000 (package.json) :
`"watch:browser": "PORT=1000 BUILD_BROWSER=1 NODE_ENV=development parcel serve --target browser ./app/renderer/index.html",`

I don't know do I leave this ticket open to be resolved or do I close it?

Thank you

**Comment by jlipps** [comment]
OK, what is the error you get. You said you get an error when you "start recording". Can you provide any more specific details?

**Comment by atigm** [comment]
when I run `npm run watch:browser ` command with another port than 1234 (for example 1235)

I have this logs (notice "configured port 1235 could not be used") :

>PORT=1235 BUILD_BROWSER=1 NODE_ENV=development parcel serve --target browser ./app/renderer/index.html

Server running at http://localhost:1235 - `configured port 1235 could not be used`.
⠼ Building index.js...You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
⠧ Building css-loader.js...You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
⠧ Building Timeline.js...You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.

**Comment by jlipps** [comment]
OK. I can repro that as well. It looks like this may be an issue with parcel.

Either way, it's not a showstopper since:
1. If you want to use this for Appium development you can develop within the electron app instead
2. If you are using this for some other purpose you can simply build the browser app in non-serve mode, and serve it with any other server tool (`python3 -m http.server` from the built dir)

Hope this helps!
