### ISSUE TITLE
pcloudy caps need updating to W3C compatible style

### ISSUE THREAD

**Issue by Dcode78** [appium/appium-inspector#391]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Unable to start the session successfully to pCloudy by configuring desired capabilities 

"Invalid or unsupported WebDriver capabilities found ("pCloudy_Username", "pCloudy_ApiKey"). Ensure to only use valid W3C WebDriver capabilities (see https://w3c.github.io/webdriver/#capabilities).If you run your tests on a remote vendor, like Sauce Labs or BrowserStack, make sure that you put them into vendor specific capabilities, e.g. "sauce:options" or "bstack:options". Please reach out to to your vendor support team if you have further questions."

Couldn't find any way to configure desired capabilities for Username and ApiKey. I end up getting above error every time. 

## Environment

- I am running Appium Desktop version 
   - App Version 2022.5.1
   - Electron  13.6.9
   -  Node.js 14.16.0
                                                  
- I am on (pick one):
    - [X] Windows
    
![pCloudy_Error](https://user-images.githubusercontent.com/32234887/167125764-49aaaf48-b0e0-4185-8db0-b4bee3ca4dc2.jpg)

**Comment by KazuCocoa** [comment]
Probably they should update https://github.com/appium/appium-inspector/blob/bee6ef9effbd125affc82a545b9316551653a27b/app/renderer/actions/Session.js#L389-L390 to set the capability as `pCloud:`(?) prefix.

Could you send an email to their support team, please?

**Comment by Dcode78** [comment]
Dropped a mail at their contact us address, will update once reply received. Thank you for your time @KazuCocoa .

**Comment by Dcode78** [comment]
pCloudy support has responded requesting to use [Appium desktop](https://github.com/appium/appium-desktop/releases/tag/v1.18.2) instead of appium-inspector and I tried it works.

**Comment by KazuCocoa** [comment]
thank you for the confirmation.
Maybe their system hasn't been upgraded? to work with w3c capabilities.

**Comment by jlipps** [comment]
@Dcode78 Appium Desktop no longer bundles the inspector, and hasn't in a very long time. there will be no updates to the old inspector that was bundled with the Appium Desktop. if this is pcloudy's suggestion, I think we should remove them from the current Inspector as it is broken. at least until they fix their system to use w3c capabilities or whatever the issue is.

**Comment by KazuCocoa** [comment]
Agree with it > I think we should remove them from the current Inspector as it is broken. at least until they fix their system to use w3c capabilities or whatever the issue is

Hm, they previously checked that https://github.com/appium/appium-inspector/pull/118#issuecomment-914075672 worked for them, but I guess webdriverio has been restricted the capability check after the version?

**Comment by KazuCocoa** [comment]
> pCloudy: @shibupanda

Hi, could you ensure pCloud supports the latest appium-inspector? According to https://github.com/appium/appium-inspector/issues/391#issuecomment-1124517978, pCloud did not support fully tet for the appium-insoector, so they recommended using old Appium Desktop. We'd like to check if pCloud supports latest appium-inspector.

https://github.com/appium/appium-inspector/issues/128#issuecomment-913812515

**Comment by shibupanda** [comment]
@KazuCocoa let me check what's missing here. Next month we have a release I will try to add the fix asap.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-inspector/pull/1388 fixed this issue
