### ISSUE TITLE
Appium_Inspector TunnelIdentifier not working

### ISSUE THREAD

**Issue by Theofylrx** [appium/appium-inspector#402]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ Yes ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
Hi, I am trying to set the TunnelIdentifier & parentTunnel or WonderProxy in Appium Inspector and passing the following jsonObject:

So this is how we are passing our json Representation
{
  "testobject_test_name":"Our Test Object Test Name",
  "appiumVersion": "1.71.1",
  "platformName": "iOS",
  "devicename": "iPhone .*",
  "tunnelIdentifier": "london", - _**Note: This is what Appium is not picking Up**_
  "parentTunnel": "sso- our parent tunnel" - _**Note: So we do add our parent tunnel, but before this we were just using "'WonderProxy': 'london'" instead the "TunnelIdentifier and parentTunnel"**_
  "automationName": "XCUITest",
  "orientation": "PORTRAIT",
  "app": "storage:filename=Our App name",
  "platformVersion": "14.8"
}

So with the Above JsonObject the **_TunnelIdentifier_** and _**ParentTunnel**_ are not getting picked up by Appium, so the location we suspecting it's using the PC location but we want to use the Location we passed to **_TunnelIdentifier_** which is the one not getting picked up.

Even with using **_WonderProxy_** instead of the _**TunnelIdentifier**_ and _**parentTunnel**_ still the location i not getting picked up.

Can anyone please assist with this, or if there's a way we are supposed to be doing this then can anyone please suggest how ?

We have also used Appium Desktop version _**1.21.0**_ and here the _**tunnelIdentifier**_ and _**parentTunnel**_ or _**WonderProxy**_ works but the issue is that iOS Version _**15**_ and up is not supported fully as we can't be able to inspect Location services Pop-ups and other verison 15 Pop-ups/pickerwheels, hence we decided upon using  Appium Desktop version _<_**2022.5.2**_>_ then we had issues with the **_tunnelIdentifier_** and _**parentTunnel**_ or _**WonderProxy**_ not getting picked up.

## Environment
- I am running Appium Desktop version _<2022.5.2>_.
- I am on (pick one):
    - [ Yes ] Windows

**Comment by jlipps** [comment]
this doesn't appear to be an issue with appium inspector, but rather with your cloud service. have you contacted their customer support?

**Comment by jlipps** [comment]
i.e., tunnelIdentifier, parentTunnel, wonderProxy, none of these things are related to Appium Inspector.

**Comment by Theofylrx** [comment]
Ok cool, but the same configuration is working on a prior version 1.21.0 of Appium inspector

**Comment by jlipps** [comment]
that is an ancient version of the inspector. if there is a change it probably has to do with the way capabilities are sent. for example the new inspector auto-prefixes appium capabilities unless you uncheck the box. it's possible testobject doesn't know what to do with prefixed capabilities.

**Comment by Theofylrx** [comment]
cool, Thanks for your help @jlipps  Bro, im gonna have to communicate with Sauce-Labs then, maybe im passing the Capabilities for the TunnelIdentifier Incorrectly as you are suggesting

**Comment by jlipps** [comment]
yes, have them take a look at what you're doing. if they can provide some more details as to why this would be an Inspector issue, then I'm happy to reopen this.
