### ISSUE TITLE
I need your help

### ISSUE THREAD

**Issue by jiang-xin9** [appium/appium-inspector#424]
Failed to create session. An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.netease.cloudmusic' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. Original error: 'Command 'D:\\androidsdk\\platform-tools\\adb.exe -P 5037 -s 181QGEYN227MN shell am start -W -n com.netease.cloudmusic/com.netease.cloudmusic.activity.MainActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' exited with code 4294967295'; Command output: Exception occurred while executing 'start': java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.netease.cloudmusic/.activity.MainActivity } from null (pid=10505, uid=2000) not exported from uid 10214 at
![图片](https://user-images.githubusercontent.com/82875017/168949548-4ed39083-1c50-49bc-962f-30a1ecf8340a.png)
![图片](https://user-images.githubusercontent.com/82875017/168949586-9560e5e9-f4bf-4620-b966-26c0e99f4d40.png)

**Comment by jlipps** [comment]
commented on your other issue.

**Comment by Alexis365** [comment]
Se pudo solucionar el error? o alguna idea de como arreglarlo, yo tengo el mismo problema
