### ISSUE TITLE
Unable to use inspector

### ISSUE THREAD

**Issue by nived001** [appium/appium-inspector#437]
## Appium or Appium Desktop?

I used this command to run Appium "appium -a 0.0.0.0 -p 4723 —allow-cors"
and tried https://inspector.appiumpro.com/ with following capabilities 
{
  "platformName": "iOS",
  "appium:platformVersion": "14.0",
  "appium:deviceName": "iPhone 12",
  "appium:automationName": "XCUITest",
  "appium:app_url": ""
}
## The problem

Could not connect to server; are you sure it's running? If you are using the browser version, also ensure your Appium server has been started with --allow-cors.

## Environment
 https://inspector.appiumpro.com/  v2022.5.4

- I am running Appium CLI version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac

**Comment by nived001** [comment]
I also download the latest appium desktop inspector [v2022.5.4](https://github.com/appium/appium-inspector/releases/tag/v2022.5.4) for Mac and tried Browserstack. Still no luck

**Comment by jlipps** [comment]
> -a 0.0.0.0

You should never tell Appium to run on `0.0.0.0` as that is not a host

**Comment by nived001** [comment]
Should I start appium with appium --allow-cors and then start Appium Inspector Desktop? Im using Android studio emulator and physical device?

{
  "platformName": "Android",
  "appium:platformVersion": "12.0",
  "appium:deviceName": "Pixel_4_API_30",
  "appium:automationName": "UiAutomator2",
  "appium:app": "/Users/xxxx.apk"
}

**Comment by nived001** [comment]
when I try to create session using browserstack then getting this "Error
Failed to create session. Error : Platform can be one of MAC, WIN8, XP, WINDOWS, and ANY"
