### ISSUE TITLE
Appium desktop - 

### ISSUE THREAD

**Issue by sabasharif** [appium/appium-inspector#456]
Appium Desktop - Inspector 

I am trying to run the Appium inspector for WinAppDriver and always getting the invalid or unsupported Webdriver Capabilities found error.  Please guide what can be changed to  resolve this issue. Thank you! 

![image](https://user-images.githubusercontent.com/40474185/171986909-d668fb04-8b1a-4592-a3a6-6f28fd4a7a93.png)

I am running this on Windows10

**Comment by jlipps** [comment]
these are invalid caps, exactly as the message says. if you check the box under capabilities to automatically add vendor prefixes the error will go away.
