### ISSUE TITLE
Failed to create appium session for android

### ISSUE THREAD

**Issue by anshul90** [appium/appium-inspector#458]
## Appium or Appium Desktop?
Appium

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
I'm getting error "failed to crease appium session". I am using below mentioned capabilities to start session. 
 
`{
  "platformName": "Android",
  "appium:platformVersion": "11.0",
  "appium:deviceName": "Pixel 5 API 30",
  "appium:automationName": "UiAutomator2",
  "appium:appActivity": ".ui.mainActivity.MainActivity",
  "appium:appPackage": "com.package.xxxxx",
  "appium:app": "/Users/anshultyagi/Downloads/v2.2.1.apk"
}`  

<img width="1280" alt="Screenshot 2022-06-06 at 3 59 02 PM" src="https://user-images.githubusercontent.com/4475866/172144490-ee59e83d-469e-46b1-a466-7e1ee10a0022.png">

I have tested in android physical device and emulator both but its not working for me.

## Environment

- I am running Appium Desktop version _1.22.3_.
- I am on (pick one):
    - [x] Mac

**Comment by jlipps** [comment]
Please show me the appium logs for:

1. This failure case
2. The success case you found when not using Appium Inspector

**Comment by anshul90** [comment]
Below shared the screenshots of both the scenarios. 

And today I have figured out that problem is with flavours. I'm having multiple flavours in same android project and same activity as the launcher for all flavours. I've tested with a sample app, and it works fine for me but my flavoured app is not getting launched.

<img width="1787" alt="Screenshot 2022-06-07 at 10 26 45 AM" src="https://user-images.githubusercontent.com/4475866/172309895-713b5ab4-9af5-4d8a-bb8e-ee47f9141758.png">

<img width="1636" alt="Screenshot 2022-06-07 at 10 18 21 AM" src="https://user-images.githubusercontent.com/4475866/172309885-a0f04986-863f-4993-826f-a187e4131294.png">

**Comment by jlipps** [comment]
@anshul90 it looks like you're using Appium Desktop as the appium server. You'll need to use the latest Appium 2 beta from the command line as well as the latest version of the UiAutomator2 driver if you'd like us to explore further (the version of Appium that you're running is very old)

**Comment by anshul90** [comment]
Hi @jlipps 

The issue was fixed by using the correct app package name. Thanks for your support.
