### ISSUE TITLE
cannot parse capability: chromeOptions from unknown error: unrecognized chrome option: androidDeviceSerial

### ISSUE THREAD

**Issue by jaxonister** [appium/appium-inspector#465]
I use the inspector to debug the webview hybrid application, use "web/hybrid", it prompts "cannot parse capability: chromeOptions from unknown error: unrecognized chrome option: androidDeviceSerial"

**Comment by emaan-c** [comment]
Hey @jaxonister, can you please show us the Appium logs and screenshots of running the session with the error?

**Comment by ra-hdz** [comment]
Hi guys. I encountered this same issue and found itwhich has been solved in Appium 2 (https://github.com/appium/appium/issues/16514) though I haven't tried it out. I noticed this error does not occur if you add the `app` capability when starting the session. This seems to add `androidPackage` to the `chromeOptions` sent when creating the Chromedriver session. You can try it as a workaround @jaxonister.

**Comment by kabdul-incomm** [comment]
I'm also getting this error. More information you can find here https://discuss.appium.io/t/appium-inspector-windows-call-to-switchcontext-failed/38105.

**Comment by eglitise** [comment]
The fix should be included in `appium-uiautomator2-driver` v2.0.4 or later. Note that it is only compatible with Appium 2.
