### ISSUE TITLE
Unable to perform Long press with appium desktop inspector using Action options 

### ISSUE THREAD

**Issue by sgovarathan** [appium/appium-inspector#470]
Scenario:
We need to long press the Mobile app in IOS mobile

Tried actions:
1.Touch Option
2.longpress action option

Issue:
Unable to perform Long press with appium desktop inspector using Action options
 It is asking  KeyCode, metaState, Flags fields to execute.

**Comment by jlipps** [comment]
If you're talking about a long touch press (not a long key press), then the only way you'll be able to solve this now is to use the Actions API and construct an actions JSON object according to the w3c spec.

we'll be working on a complex gesture editor that will allow building these kinds of things visually over the next few months

**Comment by sgovarathan** [comment]
Hi,

Thanks for your reply!!

Do you have any other work around for performing longpress?

We need to Longpress the mobile application and send the different url to
that application and to lunch it.

Note: need to do in Manual using appium inspector.

Thanks,
Govarthan S

**Comment by jlipps** [comment]
No, no other workaround is available in the inspector at this time.

**Comment by JayD123** [comment]
> If you're talking about a long touch press (not a long key press), then the only way you'll be able to solve this now is to use the Actions API and construct an actions JSON object according to the w3c spec.
> 
> we'll be working on a complex gesture editor that will allow building these kinds of things visually over the next few months

Do you have a task for complex gesture editor that I can follow

**Comment by jlipps** [comment]
it's already released
