### ISSUE TITLE
Unable to perform Long press with appium desktop inspector using Action options 

### ISSUE THREAD

**Issue by sgovarathan** [appium/appium-inspector#472]
Scenario: Need to long press the Mobile application in IOS device.

Tried Using:
1.Touch option 
2. long press action but its not working

Issue: 
Unable to perform Long press with appium desktop inspector using Action options

**Comment by sgovarathan** [comment]
You have shared the code for long press, While executing program we able to long press the application 

Issue is manually trying do in appium desktop inspector
![Uploading IMG_20220616_211542__01.jpg…]()
Attached the screenshot

**Comment by KazuCocoa** [comment]
So, the below action did not help in your case?
<img width="884" alt="Screen Shot 2022-06-18 at 0 43 04" src="https://user-images.githubusercontent.com/5511591/174428153-a5bad7cd-baab-40aa-b2bf-7dceab9f275d.png">
<img width="581" alt="Screen Shot 2022-06-18 at 0 42 59" src="https://user-images.githubusercontent.com/5511591/174428156-f7d105f4-daf9-4523-aae1-fcb1c8becf42.png">

Maybe, then, it will be a new feature request to do long press via appium inspector.

(btw, your attached image was perhaps broken)

**Comment by eglitise** [comment]
Issue can be resolved by using the gesture editor in the Actions tab.
