### ISSUE TITLE
inspector: every element has x=0 y=0 and with 'full screen' width and height

### ISSUE THREAD

**Issue by achtan** [appium/appium-inspector#473]
## The problem
every element that I inspect has:
<img width="241" alt="Screenshot 2022-06-17 at 14 26 05" src="https://user-images.githubusercontent.com/1048212/174297843-3dd66cf6-0432-45ee-9775-aeb3793b7eb5.png">

## Environment

- I am running Appium Desktop version 
App Version: 2022.5.4
Electron: 13.6.9
Node.js: 14.16.0

- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by emaan-c** [comment]
Hey @achtan, I believe that you are selecting a container or parent node that might be the size of you entire screen, meaning that the element you're selecting starts at the coordinates (0, 0) and has a width and height that takes up the entire screen. This doesn't seem to be an issue with the Inspector, but you may just be highlighting the wrong element!

**Comment by jlipps** [comment]
And there are some apps (like games for example) that only expose basic container elements, whereas all the user-interactable elements are opaque to the accessibility system (and therefore Appium). so it could be that Appium just can't see individual elements you'd like to work with.

**Comment by achtan** [comment]
@emaan-c @jlipps but all my elements have this issue... so what should I do to make it work? 
I do have some elements with `testId` and `accessible=true`. I have a React Native app...

**Comment by jlipps** [comment]
you probably need to adjust the way you are using accessibility in your react native app. it may be hiding all the internal elements. i know @wswebcreation has written some things about this, maybe he can link here for reference?

**Comment by eglitise** [comment]
Closing due to no response
