### ISSUE TITLE
New session window footer can get pushed outside the visible GUI

### ISSUE THREAD

**Issue by TDL-EdgarsEglitis** [appium/appium-inspector#479]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

In the new session window, the footer (which includes the Start Session button) may get pushed outside the visible GUI and require scrolling down to reach it. This can happen in the Desired Capabilities tab (if I add many capabilities), or in the Saved Capability Sets tab (if I have many saved capability sets).
Scrolling down then affects the entire GUI:
<img src="https://user-images.githubusercontent.com/78592357/174993721-0504fde8-bc4c-4ca3-b0d9-3f93ab031785.png">
<img src="https://user-images.githubusercontent.com/78592357/174994323-ea325512-6c98-4d53-a08b-c9312bc0e42c.png">

I also checked other inspector versions:
* Could replicate in 2022.5.1
* Could not replicate in 2022.2.1

## Environment

- I am running Appium Desktop version _2022.5.4_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by emaan-c** [comment]
Hey @TDL-EdgarsEglitis, thanks for this bug report! I can see it happening on my end as well. Will need to create a PR to fix the scrolling under the 'Saved Capability Sets' tab

**Comment by TDL-EdgarsEglitis** [comment]
Seeing as #525 is fixed and merged - closing this.
