### ISSUE TITLE
while I'm Clicking on the inspect move then show the direct link of github

### ISSUE THREAD

**Issue by Talha0024** [appium/appium-inspector#482]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem when opening the appium server the issue is inpect move is not working it goes to the next github account 

_Replace this section with a description of your issue_ kinldy check and open the next screen

## Environment

- I am running Appium Desktop version _<v1.22.3>_.
- I am on (pick one):
   
    - [x] Windows
    
#

**Comment by anaplesniovski** [comment]
Estou com o mesmo problema

**Comment by jlipps** [comment]
I'm sorry I don't understand the problem. All I see is a screenshot of this repo. Can you provide a more detailed bug report?

**Comment by TDL-EdgarsEglitis** [comment]
This is probably a case of user confusion due to an incorrect button tooltip in the Appium Server GUI. Likely related to [appium-desktop#2053](https://github.com/appium/appium-desktop/issues/2053).
![inspector-moved](https://user-images.githubusercontent.com/78592357/176831657-1cbfd462-5c84-4b90-b92c-ca3466e3c649.png)

**Comment by jlipps** [comment]
OK. I'm kicking off a new publish of Appium Desktop so it will hopefully get any new translations.

**Comment by dbora-silva** [comment]
I'm having this issue too. I'm using Appium v1.22.3. 

![A-I-1](https://user-images.githubusercontent.com/82063557/183155772-5b8f9f0b-e204-4b77-a093-ba9c50c37e59.png)
![A-I-2](https://user-images.githubusercontent.com/82063557/183155784-f59eba67-9425-4d5f-aad8-b57e0ddb91ef.png)

**Comment by jlipps** [comment]
This is the correct behaviour. the inspector is no longer a part of appium desktop.

**Comment by fortuneobinna** [comment]
I'm facing exactly same as above. Any solution?

**Comment by jlipps** [comment]
> This is the correct behaviour. the inspector is no longer a part of appium desktop.

You need to download the inspector from the page that opened.

**Comment by dapshad** [comment]
How do i download the inspector from this page? Where's the link

**Comment by jlipps** [comment]
do you see the Releases section?

**Comment by URashmi23** [comment]
Hi,  I am using MacBook Air.
I am also facing the same issue when i click on search icon from Appium server GUI. app, it says
inspector moved.
How to resolve this? Please help


![Screenshot 2022-09-15 at 4 32 44 PM](https://user-images.githubusercontent.com/113539834/190388971-8f5f6906-cd8c-45b4-beb5-64168728a32f.png)

**Comment by URashmi23** [comment]
We need to ignore this, coz now inspector is an different tool

**Comment by dapshad** [comment]
@jlipps , i have been able to get my appium inspector working now but when setting my capabilities, i had to take off the apk app file before the inspector could open, and now i need to install a new apk file for my virtual device, will be useful if you have any link for Android and i'm using windows

**Comment by jlipps** [comment]
sorry, don't understand your question. appium inspector is not an android app.

**Comment by Eshantrana03** [comment]
> 

scroll down and see the release link
