### ISSUE TITLE
tips:Original error: 'POST /elements' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed).

### ISSUE THREAD

**Issue by poscergx** [appium/appium-inspector#491]
appium-inspector version:
appium version: 1.22.3
devices: mac android

when i search elements, tips it.
same error in appium-server too.

full error info:Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Origi
nal error: 'POST /elements' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details

**Comment by poscergx** [comment]
appium-inspector version:2022.5.4

**Comment by AnunayaThakureb** [comment]
I am also getting the same error when I set the desired capability to UIAutomator2: 

[debug] [WD Proxy] Proxying [GET /appium/device/info] to [GET http://127.0.0.1:8200/wd/hub/session/71ab7af2-64ca-47b5-ae36-d652b730b773/appium/device/info] with no body
[debug] [WD Proxy] Got response with status 200: {"sessionId":"71ab7af2-64ca-47b5-ae36-d652b730b773","value":{"androidId":"c42f2593a677fa76","apiVersion":"30","bluetooth":{"state":"ON"},"brand":"nxp","carrierName":"","displayDensity":213,"locale":"en_US","manufacturer":"nxp","model":"XXX","networks":[],"platformVersion":"11","realDisplaySize":"1920x1080","timeZone":"GMT"}}
[debug] [ADB] Running '/opt/intallation-location/android-sdk/platform-tools/adb -P 5037 -s 0608200e828bb075 shell dumpsys window'
[AndroidDriver] Screen already unlocked, doing nothing
[UiAutomator2] Starting 'com.XXXX.av.tripplannerapp/.TripPlannerActivity and waiting for 'com.XXX.av.tripplannerapp/.TripPlannerActivity'
[debug] [ADB] Running '/opt/intallation-location/android-sdk/platform-tools/adb -P 5037 -s 0608200e828bb075 shell am start -W -n com.XXXX.av.tripplannerapp/.TripPlannerActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [WD Proxy] Proxying [GET /appium/device/pixel_ratio] to [GET http://127.0.0.1:8200/wd/hub/session/71ab7af2-64ca-47b5-ae36-d652b730b773/appium/device/pixel_ratio] with no body
[WD Proxy] socket hang up
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [WD Proxy] Matched '/' to command name 'deleteSession'
[debug] [WD Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:8200/wd/hub/session/71ab7af2-64ca-47b5-ae36-d652b730b773] with no body
[WD Proxy] socket hang up
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
@jlipps Can you please help?

**Comment by KazuCocoa** [comment]
Did you take a look at the logcat?

**Comment by jlipps** [comment]
This is not an inspector issue. Seems like something crashed. As @KazuCocoa says, looking at the logcat would probably show you what the error is. In either case I'm going to close the error here. Feel free to open up another one at the uiautomator 2 driver repo if you think there's a bug happening.
