### ISSUE TITLE
Appium Inspector is not able to find UIObject2 Android

### ISSUE THREAD

**Issue by AnunayaThakureb** [appium/appium-inspector#495]
## Appium or Appium Desktop?

Tried with both appium and appium desktop 

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue:
      Occurs on both 

## The problem
     Appium Inspector is not able to find UIObject2

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by AnunayaThakureb** [comment]
@jlipps Is it a known issue. Any help will be highly appreciated.

**Comment by KazuCocoa** [comment]
What does this mean? Did you fail to find an element in UIA2 driver?

Appium inspector is an appium client that has GUI, so appium server itself is the same as other appium clients.

```
Appium inspecctor <---> appium/UIA2 driver <---> device
```

**Comment by jlipps** [comment]
> Appium Inspector is not able to find UIObject2

No idea what this means. Please provide a full bug report.

**Comment by eglitise** [comment]
Closing due to no response
