### ISSUE TITLE
Bug with 'CLASS_CHAIN' search

### ISSUE THREAD

**Issue by tking16** [appium/appium-inspector#497]
App Version: 2022.5.4
Electron: 13.6.9
Node.js: 14.16.0
Platform: Mac OS

You guys have a bug with your 'Find Element' section, When you search by class chain the inspector tries to search by 'CLASS_CHAI' so naturally nothing will ever be found

https://imgur.com/a/1fax7db

**Comment by TDL-EdgarsEglitis** [comment]
Not sure if this will solve your issue, but your example is using an xpath selector with the class chain strategy 🙂 The correct class chain selector would be ``**/XCUIElementTypeButton[`name == "Settings"`]``.
[Check the class chain construction rules here.](https://github.com/facebookarchive/WebDriverAgent/wiki/Class-Chain-Queries-Construction-Rules)

**Comment by jlipps** [comment]
As @TDL-EdgarsEglitis mentioned, this is probably just a typo in the code which is displayed in the recorder. The Inspector never actually runs this code; it's just displayed as a reference. But yes, we should fix the typo.
