### ISSUE TITLE
Clicking inspector icon did not launch the inspector but direct to github repository instead

### ISSUE THREAD

**Issue by loktung339** [appium/appium-inspector#501]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

- The inspector icon shows tooltip as "InspectMoved"
- When i clicked the icon, it just redirects me to github repo instead of launching the inspector
![螢幕截圖 2022-07-05 上午12 39 02](https://user-images.githubusercontent.com/16813388/177193846-009bf327-91df-48a4-8712-d6a2b80decfc.png)

## Environment

- I am running Appium Desktop version : latest v1.22.3-4
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
This is expected. The Inspector used to be a part of Appium Desktop, and now it's not. Rather than delete the button, we had it send users to the GitHub repo where they can download the Inspector.

**Comment by SparshGoyal08** [comment]
@jlipps I downloaded the inspector from GitHub repo and still when I click inspector it is still redirecting to GitHub repo. What can I do? Any suggestions?

**Comment by eglitise** [comment]
@SparshGoyal08 you may be downloading from the wrong location.
The correct location is on the `appium-inspector` repo - [here is a link to the releases section](https://github.com/appium/appium-inspector/releases).
The application that redirects to GitHub is Appium Desktop, on the `appium-desktop` repo - [here is a link to the repo](https://github.com/appium/appium-desktop). It is deprecated and not recommended to be used.
