### ISSUE TITLE
data-* attribute present in html to identify a unique element not present in appium inspector. 

### ISSUE THREAD

**Issue by Manasa-patgar** [appium/appium-inspector#503]
data-* attribute present in html to identify a unique element not present in appium inspector. We are using appium java client version 7.2 and appium server version v1.21.0. Please let us know the way forward

**Comment by jlipps** [comment]
The inspector is not a good tool for inspecting HTML. For that you should use a web browser's debug tools.

If you want to try the inspector, you'll need to put it into web context mode and make sure your web context is selected. But even here the options will be minimal. It's much better to use Chrome or Firefox or whatever to connect to the mobile webview for inspection.
