### ISSUE TITLE
feat request: show spinner over source instead of screenshot when viewing an MJPEG stream

### ISSUE THREAD

**Issue by krishtoautomate** [appium/appium-inspector#504]
## The problem

Mjpeg video mode is still showing loader when tap is called though it is video/screen cast
<img width="559" alt="image" src="https://user-images.githubusercontent.com/20734341/177333347-51e30e84-70ed-4ace-8834-7f55480eee58.png">

## Environment

- I am running Appium Desktop version _2022.5.4_.
- I am on (pick one):
    - [ ] Mac

**Comment by jlipps** [comment]
the loader does show while the hierarchy is being refreshed. could that be what's happening?

**Comment by krishtoautomate** [comment]
Yes thats correct. I think, video doesn't need refresh as it is live already. Only pagesource should be loaded.

**Comment by jlipps** [comment]
Sure, this issue can be converted into a feature request for the spinner to be shown over the source tree instead if we're in MJPEG mode

**Comment by krishtoautomate** [comment]
also this feature works only if i run iproxy command in parallel in a terminal for mjpeg port

**Comment by jlipps** [comment]
that's expected. appium doesn't do anything special for real devices as far as port forwarding, I don't think.

**Comment by eglitise** [comment]
Feature has been added in version 2023.6.1. FYI @krishtoautomate
