### ISSUE TITLE
Recorder-generated scripts seem to be generating out of date code

### ISSUE THREAD

**Issue by devjta** [appium/appium-inspector#506]
Hey!

I just wanted to try out Appium, but what should I do with the recorded script from appium inspector? I tried running it in javascript and in java, but the functions simple doesnt exist.

All tutorials or howto uses them, but they are mostly >2years old.

There is no AndroidDriver().findElementByXPath.. 

Using this java client: testImplementation 'com.github.appium:java-client:ea09b21'

Same when using JS:Webdriverio. There is no element function in the driver object..

So what am I missing here? Why is the inspector generating code, which can no where be executed? Why are all samples from the past also looking like that?

**Comment by jlipps** [comment]
I guess the inspector code samples are a bit out of date. No one is really on top of maintaining them whenever there are updates to the corresponding client libraries. But you should be able to read the docs for the client libraries and see what changes you might need to make.

alternatively you could install older versions of the libraries.

If you find specific changes that we could make to our boilerplate or function generators, please help us out by raising an issue describing the problem (or even making a PR yourself!).

**Comment by zeufack** [comment]
Hey, is someone working on this issue ? If not, I want to take it

**Comment by eglitise** [comment]
I don't think anyone is working on this right now - any and all contributions will be appreciated :)

**Comment by jlipps** [comment]
this would be a huge help @zeufack !

**Comment by zeufack** [comment]
Good

**Comment by eglitise** [comment]
All current recorder scripts have now been updated with (hopefully) functional code. The changes will be included in the next release.
