### ISSUE TITLE
Failed to create session. The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource

### ISSUE THREAD

**Issue by Kalyanb447-github** [appium/appium-inspector#509]
on ubontu 22.0
Error
Failed to create session. The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource

**Comment by hiyaji6007** [comment]
appium server expect /wd/hub/sessions endpoint, but inspector sends request to /sessions instead

**Comment by jlipps** [comment]
Yes. This error means you need to start your appium server, or update connection details to match.

**Comment by hariharasuthanMS** [comment]
Failed to create session. The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource.  I don't know why this error message was shown again and again.

**Comment by eglitise** [comment]
@hariharasuthanMS if you are still experiencing this, please create a new issue with more details.

**Comment by hariharasuthanMS** [comment]
@eglitise 
1. im open my appium inspector through appium but it will again and again redirect to https://github.com/appium/appium-inspector this page .
2. After giving  all credential in appium inspector about platform details im still getting this error The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource.
3. if Webdriver is must or not

**Comment by eglitise** [comment]
@hariharasuthanMS as I mentioned, please create a *new issue* and provide more details.
