### ISSUE TITLE
inspector full screen problem

### ISSUE THREAD

**Issue by gen-apps** [appium/appium-inspector#515]
Bug:
1. Appium inspector doesn't have full screen window mode
2. to resize window is limited and user is not able to make smaller window
3. the save button and start session button is hidden and user is not able to save caps or start session 

## Environment
- I am running Appium Inspector version 2022.5.4
- I am using 
    - [ Elementary os] Linux (ubuntu dist) 
    
    regards

**Comment by jlipps** [comment]
Sorry, at this point our only advice is to use a device with higher screen resolution, or to use the [web version](https://inspector.appiumpro.com) which would work with a mouse that can scroll horizontally and vertically.
