### ISSUE TITLE
Reset App doesn't work in Appium Inspector

### ISSUE THREAD

**Issue by MishkaTheCub** [appium/appium-inspector#518]
The issue occurs with Appium Inspector. Was not an issue in Appium Desktop.

- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Inspector issue

## The problem

The Reset App action in Appium Inspector doesn't work. An error is shown saying "Call to 'resetApp' failed. The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource"

<img width="430" alt="Screen Shot 2022-07-14 at 11 57 00" src="https://user-images.githubusercontent.com/13021303/179068115-9a057cea-ce53-49fd-9561-498a6c47f234.png">

Error in Appium: No route found for /wd/hub/session/080cffc2-ac7c-4ebf-a6d5-6a6c9d0f15db/appium/app/resetApp

Steps to reproduce:
1. After creating a session and getting a successful screenshot, select the Actions tab.2. 
2. In the first drop-down list select Device. In the second drop-down select App.
3. Click Reset App. Observe the error message.

## Environment
Appium version: 1.22.3
- I am running Appium Inspector version _2022.7.1_. (not reproducible with Appium Desktop 1.21.0-1)
- I am on (pick one):
    - [X] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
this looks like an upstream bug in webdriverio: https://github.com/webdriverio/webdriverio/issues/8523

but in any case the functionality is deprecated so you probably want to find a different strategy (stopping/starting the session again is recommended)

**Comment by jlipps** [comment]
and we should probably remove this action entirely from the inspector
