### ISSUE TITLE
Launch App and Close App options are missing in Appium Inspector

### ISSUE THREAD

**Issue by MishkaTheCub** [appium/appium-inspector#519]
The issue occurs with Appium Inspector. Was not an issue in Appium Desktop.

- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

The Launch App and Close App options are missing in Appium Inspector. The options made possible to work with the currently running app. The new options "Activate App" and "Terminate App" always require a bundle ID to be entered. 

## Environment

- I am running Appium Inspector version _2022.7.1_. (not reproducible with Appium Desktop 1.21.0-1)
- I am on (pick one):
    - [ ] Mac
    - [ ] Windows
    - [ ] Linux

Options in Appium Desktop:
<img width="781" alt="Expected" src="https://user-images.githubusercontent.com/13021303/179072493-3b974cae-b9a6-416e-8504-8055920d7a8a.png">

Options in Appium Inspector:
<img width="880" alt="Actual" src="https://user-images.githubusercontent.com/13021303/179072538-8efb6431-af3d-483b-a017-0f0946d24bec.png">

**Comment by jlipps** [comment]
These were intentionally removed as Appium has deprecated them. They do not generally do what users expect. Please use the methods that require an app package / bundle id. If you don't know the app id you can always launch the app manually and then see what it is in the session information tab.
