### ISSUE TITLE
Feature request: Ability to create multiple sessions in Appium Inspector

### ISSUE THREAD

**Issue by MishkaTheCub** [appium/appium-inspector#520]
- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Inspector issue

## The problem

_Appium Inspector doesn't allow multiple session windows to be open, just one at a time. Appium Desktop 1.21.0-1 allowed multiple sessions to be created at the same time by pressing CMD+N or selecting New Session Window... in the menu, and have them running on all connected devices as long as the `wdaLocalPort` value was unique for the devices_

## Environment

- I am running Appium Inspector version _2022.7.1_. (not reproducible with Appium Desktop 1.21.0-1)
- I am on (pick one):
    - [X] Mac
    - [ ] Windows
    - [ ] Linux

How it looked on Appium Desktop:
<img width="1512" alt="Screen Shot 2022-07-14 at 13 04 39" src="https://user-images.githubusercontent.com/13021303/179074732-c62060e7-2b18-4dcd-89ea-ff727a2fcec7.png">

**Comment by jlipps** [comment]
https://github.com/appium/appium-inspector/pull/521

**Comment by jlipps** [comment]
If you want multiple sessions at a time _now_, then just open up multiple browser windows to https://inspector.appiumpro.com
