### ISSUE TITLE
Appium inspector fails to inspect certain pages. Refreshes back to the last viewed page.

### ISSUE THREAD

**Issue by vinayak-kaladhar** [appium/appium-inspector#523]
## Appium or Appium Desktop?
Appium Desktop using appium server GUI(Appium-Server-GUI-mac-1.22.3-4) + appium inspector (Appium-Inspector-mac-2022.7.1)

## The problem

Appium inspector fails to inspect certain pages. Refreshes back to the last viewed page.
Am on a different screen which opens up with the payment methods,
though refreshed many times, it still refers the old page and is not able to inspect the new page.

## Environment

- I am running Appium Desktop version _Appium-Server-GUI-mac-1.22.3-4.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

<img width="1613" alt="Screenshot 2022-07-17 at 2 01 09 PM" src="https://user-images.githubusercontent.com/96525672/179390581-63504567-2bd5-4b3a-b5ff-51c24c61f927.png">

**Comment by jlipps** [comment]
It looks like Appium is picking up the screen which is behind the popup/overlay. You may need to adjust which is the active application to find the UI for the other one. I think there is a setting you can set for this purpose. @KazuCocoa any ideas?

**Comment by KazuCocoa** [comment]
I haven't seen the behavior, but probably the modal implementation did not appear in the screenshot API properly...?
Did you try a real device?

**Comment by eglitise** [comment]
Closing due to no response
