### ISSUE TITLE
Android Hybrid App, unable to switch to web context

### ISSUE THREAD

**Issue by durgapatro** [appium/appium-inspector#534]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Getting below error while switching to web context. What I have to do to make it work?Also the URL reference given is not working.

Call to 'switchContext' failed
An unknown server-side error occurred while processing the command. Original error: No Chromedriver found that can automate Chrome '91.0.4472'. You could also try to enable automated chromedrivers download server feature. See **https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md** for more details

## Environment

- I am running Appium Desktop version _<2022.5.1>_.
- I am on (pick one):
    - [x] Windows

![Screenshot 2022-07-26 225259](https://user-images.githubusercontent.com/76612272/181071209-7901ac45-c487-4f35-9f49-023a9fb962c6.png)

**Comment by jlipps** [comment]
The correct docs link address for now is https://github.com/appium/appium/blob/1.x/docs/en/writing-running-appium/web/chromedriver.md

**Comment by durgapatro** [comment]
Thank you, I followed below steps available in there but getting error. Could you please help

When starting the server
Chromedriver version can be specified at runtime, by specifying the --chromedriver-executable server flag, along with the full path to the Chromedriver executable which was manually downloaded and put to the server file system, e.g.,

appium --chromedriver-executable /path/to/my/chromedriver

**index.js: error: unrecognized arguments: --chromedriver-executable C:\\Users\\xxxx\\OneDrive\\Desktop\\Appium_Contents\\Apps\\chromedriver.exe**

**Comment by jlipps** [comment]
that is now an environment variable (see the [migration guide](https://github.com/appium/appium/blob/master/packages/appium/docs/en/guides/migrating-1-to-2.md#bangbang-chromedriver-installation-flags))

**Comment by eglitise** [comment]
The simplest solution that I can suggest here is to launch the Appium server with the flag `--allow-insecure chromedriver_autodownload`. For more information on hybrid mode in Appium 2, see the [UiAutomator2 documentation](https://github.com/appium/appium-uiautomator2-driver#hybrid-mode). 
For now, closing due to no response.

**Comment by yakovenko79** [comment]
Please, help me if i want to run telegram web app from Telegram and i face with the same issue which the flag should i write? Web app telegram is not use chromedriver? am i correct ?

**Comment by eglitise** [comment]
If you're getting the same 'no chromedriver found' error, see my comment above for using the chromedriver autodownload flag. If you can't see the webview at all, you can check if it is debuggable through [Chrome DevTools](https://developer.chrome.com/docs/devtools/remote-debugging/). If it doesn't appear there, then Appium will also not be able to see it.
For general questions please use [the Appium forum](https://discuss.appium.io/).
