### ISSUE TITLE
Appium inspector stopped working after upgrading iOS version!

### ISSUE THREAD

**Issue by Robot1988** [appium/appium-inspector#544]
<img width="1314" alt="Screenshot 2022-07-31 at 12 58 30 PM" src="https://user-images.githubusercontent.com/94165470/182022471-7df1298b-7332-45b0-b474-649f73c95d3a.png">

All the configurations were made for mobile ios automation and was working perfectly fine.
Once I upgraded my mobile iOS to latest things stopped working, I upgraded XCode, Appium desktop, Appium inspector everything to latest. Using XCode I am able to access my mobile iOS now, but Appium inspector is failing, its showing “Gathering initial app source” and keeps looping. I am unable to downgrade iOS version to older version as its against my company policy, how to get this fixed. Tried everything from internet its not working.

Appium desktop Version - 1.22.3
Appium Inspector Version - 2022.7.1
Xcode Version - 13.4.1
iOS Version - 15.6

[debug] �[35m[W3C (266873f7)]�[39m Calling AppiumDriver.getScreenshot() with args: ["
[debug] �[35m[XCUITest]�[39m Executing command 'getScreenshot'
[debug] �[35m[XCUITest]�[39m Taking screenshot with WDA
[debug] �[35m[WD Proxy]�[39m Matched '/screenshot' to command name 'getScreenshot'
[debug] �[35m[WD Proxy]�[39m Proxying [GET /screenshot] to [GET http://127.0.0.1:8100/session/46E1C0CD-4256-4203-8A2C-01C88DDAF54D/screenshot] with no body
[info] �[35m[WD Proxy]�[39m socket hang up
[warn] �[35m[XCUITest]�[39m Error getting screenshot: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
[debug] �[35m[XCUITest]�[39m Taking screenshot with WDA
[debug] �[35m[WD Proxy]�[39m Matched '/screenshot' to command name 'getScreenshot'
[debug] �[35m[WD Proxy]�[39m Proxying [GET /screenshot] to [GET http://127.0.0.1:8100/session/46E1C0CD-4256-4203-8A2C-01C88DDAF54D/screenshot] with no body
[debug] �[35m[iProxy@00008030:8100]�[39m Connection was refused to port 8100
[info] �[35m[WD Proxy]�[39m socket hang up[error] �[35m[WebDriverAgent]�[39m xcodebuild exited with code '65' and signal 'null'
[debug] �[35m[XCUITest]�[39m Taking screenshot with WDA
[debug] �[35m[WD Proxy]�[39m Matched '/screenshot' to command name 'getScreenshot'
[debug] �[35m[WD Proxy]�[39m Proxying [GET /screenshot] to [GET http://127.0.0.1:8100/session/46E1C0CD-4256-4203-8A2C-01C88DDAF54D/screenshot] with no body
[debug] �[35m[iProxy@00008030:8100]�[39m Connection was refused to port 8100
[info] �[35m[WD Proxy]�[39m socket hang up
[debug] �[35m[W3C (266873f7)]�[39m Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
[debug] �[35m[W3C (266873f7)]�[39m at JWProxy.command (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:274:13)
[debug] �[35m[W3C (266873f7)]�[39m at runMicrotasks ()
[debug] �[35m[W3C (266873f7)]�[39m at processTicksAndRejections (internal/process/task_queues.js:97:5)
[debug] �[35m[W3C (266873f7)]�[39m at XCUITestDriver.proxyCommand (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:96:12)
[debug] �[35m[W3C (266873f7)]�[39m at getScreenshotFromWDA (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/screenshots.js:11:18)
[debug] �[35m[W3C (266873f7)]�[39m at wrapped (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:60:13)
[debug] �[35m[W3C (266873f7)]�[39m at retry (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:43:13)
[debug] �[35m[W3C (266873f7)]�[39m at retryInterval (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:70:10)
[debug] �[35m[W3C (266873f7)]�[39m at XCUITestDriver.getScreenshot (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/screenshots.js:42:10)
[info] �[35m[HTTP]�[39m �[37m<-- GET /wd/hub/session/266873f7-bdb3-479c-967a-e8905dc86ee7/screenshot �[39m�[31m500�[39m �[90m1130 ms - 1660�[39m
[info] �[35m[HTTP]�[39m �[90m�[39m[info] �[35m[HTTP]�[39m �[37m-->�[39m �[37mGET�[39m �[37m/wd/hub/session/266873f7-bdb3-479c-967a-e8905dc86ee7/window/rect�[39m
[info] �[35m[HTTP]�[39m �[90m{}�[39m
[debug] �[35m[W3C (266873f7)]�[39m Calling AppiumDriver.getWindowRect() with args: ["266873f7-bdb3-479c-967a-e8905dc86ee7"]
[debug] �[35m[XCUITest]�[39m Executing command 'getWindowRect'
[debug] �[35m[WD Proxy]�[39m Proxying [GET /window/size] to [GET http://127.0.0.1:8100/session/46E1C0CD-4256-4203-8A2C-01C88DDAF54D/window/size] with no body
[debug] �[35m[iProxy@00008030:8100]�[39m Connection was refused to port 8100
[info] �[35m[WD Proxy]�[39m socket hang up
[debug] �[35m[W3C (266873f7)]�[39m Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
[debug] �[35m[W3C (266873f7)]�[39m at JWProxy.command (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:274:13)
[debug] �[35m[W3C (266873f7)]�[39m at runMicrotasks ()
[debug] �[35m[W3C (266873f7)]�[39m at processTicksAndRejections (internal/process/task_queues.js:97:5)
[debug] �[35m[W3C (266873f7)]�[39m at XCUITestDriver.proxyCommand (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:96:12)
[debug] �[35m[W3C (266873f7)]�[39m at XCUITestDriver.getWindowSizeNative (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/general.js:78:10)
[debug] �[35m[W3C (266873f7)]�[39m at XCUITestDriver.getWindowSize (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/general.js:87:12)
[debug] �[35m[W3C (266873f7)]�[39m at XCUITestDriver.getWindowRect (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/general.js:160:27)
[info] �[35m[HTTP]�[39m �[37m<-- GET /wd/hub/session/266873f7-bdb3-479c-967a-e8905dc86ee7/window/rect �[39m�[31m500�[39m �[90m47 ms - 1424�[39m
[info] �[35m[HTTP]�[39m �[90m�[39m
[info] �[35m[HTTP]�[39m �[37m-->�[39m �[37mGET�[39m �[37m/wd/hub/session/266873f7-bdb3-479c-967a-e8905dc86ee7/source�[39m
[info] �[35m[HTTP]�[39m �[90m{}�[39m
[debug] �[35m[W3C (266873f7)]�[39m Calling AppiumDriver.getPageSource() with args: ["266873f7-bdb3-479c-967a-e8905dc86ee7"]
[debug] �[35m[XCUITest]�[39m Executing command 'getPageSource'
[debug] �[35m[WD Proxy]�[39m Matched '/source?scope=AppiumAUT' to command name 'getPageSource'
[debug] �[35m[WD Proxy]�[39m Proxying [GET /source?scope=AppiumAUT] to [GET http://127.0.0.1:8100/session/46E1C0CD-4256-4203-8A2C-01C88DDAF54D/source?scope=AppiumAUT] with no body
[debug] �[35m[iProxy@00008030:8100]�[39m Connection was refused to port 8100
[info] �[35m[WD Proxy]�[39m socket hang up
[debug] �[35m[W3C (266873f7)]�[39m Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
[debug] �[35m[W3C (266873f7)]�[39m at JWProxy.command (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:274:13)
[debug] �[35m[W3C (266873f7)]�[39m at runMicrotasks ()
[debug] �[35m[W3C (266873f7)]�[39m at processTicksAndRejections (internal/process/task_queues.js:97:5)
[debug] �[35m[W3C (266873f7)]�[39m at XCUITestDriver.proxyCommand (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:96:12)
[debug] �[35m[W3C (266873f7)]�[39m at XCUITestDriver.getNativePageSource (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/source.js:26:19)
[debug] �[35m[W3C (266873f7)]�[39m at XCUITestDriver.getPageSource (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/source.js:22:10)
[info] �[35m[HTTP]�[39m �[37m<-- GET /wd/hub/session/266873f7-bdb3-479c-967a-e8905dc86ee7/source �[39m�[31m500�[39m �[90m32 ms - 1237�[39m
[info] �[35m[HTTP]�[39m �[90m�[39m[info] �[35m[HTTP]�[39m �[37m-->�[39m �[37mGET�[39m �[37m/wd/hub/session/266873f7-bdb3-479c-967a-e8905dc86ee7/timeouts�[39m
[info] �[35m[HTTP]�[39m �[90m{}�[39m
[debug] �[35m[W3C (266873f7)]�[39m Calling AppiumDriver.getTimeouts() with args: ["266873f7-bdb3-479c-967a-e8905dc86ee7"]
[debug] �[35m[XCUITest]�[39m Executing command 'getTimeouts'
[debug] �[35m[W3C (266873f7)]�[39m Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[info] �[35m[HTTP]�[39m �[37m<-- GET /wd/hub/session/266873f7-bdb3-479c-967a-e8905dc86ee7/timeouts �[39m�[32m200�[39m �[90m8 ms - 42�[39m
[info] �[35m[HTTP]�[39m �[90m�[39m[info] �[35m[HTTP]�[39m �[37m-->�[39m �[37mGET�[39m �[37m/wd/hub/session/266873f7-bdb3-479c-967a-e8905dc86ee7/timeouts�[39m
[info] �[35m[HTTP]�[39m �[90m{}�[39m
[debug] �[35m[W3C (266873f7)]�[39m Calling AppiumDriver.getTimeouts() with args: ["266873f7-bdb3-479c-967a-e8905dc86ee7"]
[debug] �[35m[XCUITest]�[39m Executing command 'getTimeouts'
[debug] �[35m[W3C (266873f7)]�[39m Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[info] �[35m[HTTP]�[39m �[37m<-- GET /wd/hub/session/266873f7-bdb3-479c-967a-e8905dc86ee7/timeouts �[39m�[36m304�[39m �[90m3 ms - -�[39m
[info] �[35m[HTTP]�[39m �[90m�[39m[info] �[35m[HTTP]�[39m �[37m-->�[39m �[37mGET�[39m �[37m/wd/hub/session/266873f7-bdb3-479c-967a-e8905dc86ee7/timeouts�[39m
[info] �[35m[HTTP]�[39m �[90m{}�[39m
[debug] �[35m[W3C (266873f7)]�[39m Calling AppiumDriver.getTimeouts() with args: ["266873f7-bdb3-479c-967a-e8905dc86ee7"]
[debug] �[35m[XCUITest]�[39m Executing command 'getTimeouts'
[debug] �[35m[W3C (266873f7)]�[39m Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[info] �[35m[HTTP]�[39m �[37m<-- GET /wd/hub/session/266873f7-bdb3-479c-967a-e8905dc86ee7/timeouts �[39m�[36m304�[39m �[90m11 ms - -�[39m
[info] �[35m[HTTP]�[39m �[90m�[39m[info] �[35m[HTTP]�[39m �[37m-->�[39m �[37mGET�[39m �[37m/wd/hub/session/266873f7-bdb3-479c-967a-e8905dc86ee7/timeouts�[39m

**Comment by jlipps** [comment]
That error is not an appium inspector error. I would make sure you can start a session after following all the relevant guides and help. And if you think there's a bug in the driver, open an issue at the driver repo.
