### ISSUE TITLE
Appium session button is not visible in landscape mode for linux 2022

### ISSUE THREAD

**Issue by BaseerAzhar** [appium/appium-inspector#549]
## The problem
Hey,
In the appium inspector the start session is not visible in landscape mode..but it always visible in portrait mode... check in different screen size as well

## Environment

* Appium version: [v2022.7.1](https://github.com/appium/appium-inspector/releases/tag/v2022.7.1)
* Desktop OS/version used to run Appium: Lixux 22, with appium inspector image..

## Details
![image](https://user-images.githubusercontent.com/32225656/183476825-b9a44beb-dbb4-4265-8a65-db095a622055.png)

**Comment by jlipps** [comment]
increase your screen resolution or use the web version at https://inspector.appiumpro.com

**Comment by BaseerAzhar** [comment]
hey my screen resolution is completely full and already check on different
screens as well but not working

**Comment by jlipps** [comment]
what is your screen resolution?

**Comment by shubham2211b** [comment]
Still same issue facing with my system not able get Start button

**Comment by shubham2211b** [comment]
Any fix for the same

**Comment by eglitise** [comment]
Please try with version 2023.6.2, it improve support for smaller screens.

**Comment by mtahirmunir** [comment]
Hopefully, the article "[The Appium Inspector Start Session Button Not Displaying](http://blog-box.com/the-appium-inspector-start-session-button-not-displaying/)" helps you resolve the issues with the Appium Inspector's Start Session Button not displaying.
