### ISSUE TITLE
Robot.js do not replace blank space of "accessibility id"

### ISSUE THREAD

**Issue by rushian** [appium/appium-inspector#552]
- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## Where
in file robot.js
appium-inspector\app\renderer\lib\client-frameworks\

## The problem
When you record a action with accessibility id, the codeFor_findAndAssign at line 49 in file robot.js, don't replace the blank space by underline

I am testing myDemoApp [https://github.com/saucelabs/my-demo-app-android/releases]

## Environment

- I am running Appium Inspector version _202.7.1 _.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
Thanks for the report. I don't really know anything about Robot Framework. Mind submitting a PR to fix it?

**Comment by rushian** [comment]
> Thanks for the report. I don't really know anything about Robot Framework. Mind submitting a PR to fix it?

Done!

**Comment by KazuCocoa** [comment]
Merged as #556
