### ISSUE TITLE
Layout of robot framework boilerplate 

### ISSUE THREAD

**Issue by rushian** [appium/appium-inspector#553]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## Where 
in file robot.js
appium-inspector\app\renderer\lib\client-frameworks\

## The problem
The layout used when you generated a code and you click in show boilerplate is wrong for robot framework

the lines 42 - 46 [
*** Test Teardown ***
    Quit Application

*** Suite Teardown ***
    Close Application`;
] should be deleted and this settings goes to line 32:

Test Teardown     Quit Application
Suite Teardown   Close Application

## Environment

- I am running Appium Desktop version _2022.7.1_.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
Thank you. I'm not sure who added Robot Framework support but it's not surprising that this is incorrect since I don't know anything about it. If you don't mind submitting a PR to fix it, it could help other people!

**Comment by rushian** [comment]
> Thank you. I'm not sure who added Robot Framework support but it's not surprising that this is incorrect since I don't know anything about it. If you don't mind submitting a PR to fix it, it could help other people!

I didn't know how to do it, but I went back and got:
https://github.com/appium/appium-inspector/pull/555

**Comment by KazuCocoa** [comment]
merged as #555
