### ISSUE TITLE
Cannot Be Opened Because Apple Can't Check for Malicious Software

### ISSUE THREAD

**Issue by ju1ianj0rdan** [appium/appium-inspector#554]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. 

- [X ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_I am seeing a message that I have to contact the develope because it isn't able to be checked for malicious software_

## Environment
<img width="251" alt="Screen Shot 2022-08-11 at 10 00 10 AM" src="https://user-images.githubusercontent.com/53064370/184151735-e5c82aab-1f48-43f4-82b0-813871c9bb7b.png">

- I am running Appium Desktop version _2022.7.1_.
- I am on (pick one):
    - [X] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
It is by Apple's security thing that app is downloaded from the internet (not from AppStore). You can open the app via Finder for the first time.
