### ISSUE TITLE
How can I find the code of interaction between the appium-inspector and appium-desktop

### ISSUE THREAD

**Issue by iloveleejunghyun** [appium/appium-inspector#56]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [v] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I read "appium-inspector\app\renderer\actions\Inspector.js" and found that the actions like setFieldValue will be sent to the appium-desktop
![image](https://user-images.githubusercontent.com/35329140/122872700-65519300-d363-11eb-84b5-a2cb1f1b1f06.png)
But I can't get more details because I don't know what is the "dispatcher function".
Wind you mind to give me some help?

## Environment

- I am running Appium Desktop version _<1.21>_.
- I am on (pick one):
    - [ ] Mac
    - [v] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
The call will be handled in https://github.com/appium/appium-inspector/blob/3883d60c22a03468a2a1b66ed7ea2d2e122452eb/app/renderer/reducers/Inspector.js#L160

appium-desktop will only have an appium server on the package. So, this inspector will have only inspector part.
This inspector will send Appium APIs to a server running on the appium-desktop

**Comment by jlipps** [comment]
Yes. the short answer is, there is no interaction between appium-inspector and appium-desktop. But if you use both of them together, then appium-inspector acts as an HTTP (webdriver) client of appium-desktop's bundled appium server.

**Comment by iloveleejunghyun** [comment]
> Yes. the short answer is, there is no interaction between appium-inspector and appium-desktop. But if you use both of them together, then appium-inspector acts as an HTTP (webdriver) client of appium-desktop's bundled appium server.

Where is the code of appium-inspector to send HTTP requests to appium-desktop?

**Comment by jlipps** [comment]
There is none. It is like asking, "where is the code that an Appium test uses to send HTTP requests to the Appium server?" It is inside the Appium client library which is used. In our case, appium-inspector uses [web2driver](https://github.com/projectxyzio/web2driver) to send webdriver requests to the Appium server. So it is not really a part of appium-inspector itself.

**Comment by iloveleejunghyun** [comment]
Got it. Thanks!
