### ISSUE TITLE
Unable to fetch the simulator devices in Appium Inspector.

### ISSUE THREAD

**Issue by deadlyghost9** [appium/appium-inspector#564]
## Appium or Appium Desktop?
-------Appium Desktop.
You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
Could not determine iOS SDK version: Could not find path to Xcode by symlinks located in /var/db/xcode_select_link, or /usr/share/xcode-select/xcode_dir_link error message 

When I try to connect with simulator in Appium inspector. As, I have updated xcode to 13.4.1 its not able to fetch the simulators. 

## Environment

- I am running Appium Desktop version _1.22.3_.
- I am on (pick one):
    - [ Monterey 12.5] Mac.

**Comment by jlipps** [comment]
xcode has nothing to do with the inspector. but anyway you probably want to research the `xcode-select` command.
