### ISSUE TITLE
Appium recorder does not have assertions

### ISSUE THREAD

**Issue by Mehdi-HAFID** [appium/appium-inspector#568]
## Appium or Appium Desktop?
Appium Inspector

## The problem

When recording a test, there is only two options: tap and send keys. asserting that a text equal some value or that an element contains a certain text is missing. Do I have to develop these features myself to be able to use the recorder for my specific use case?

## Environment

- I am running Appium inspector 2022.7.1
- I am on (pick one):
    - [x] Windows

**Comment by jlipps** [comment]
The Inspector is not designed to be a test runner or framework. It provides a recording feature merely to help show what the client code would look like for various Appium actions. Appium itself has no assertions. Appium is just an automation library. Assertions are part of language-specific test libraries and frameworks. It's not a design goal for the Inspector to include assertions.

**Comment by Mehdi-HAFID** [comment]
I'm using inspector to gather user actions, so I can automate running them in the server -java-. it just that the only two actions a user can do is click & input text. I think I will have to add them my self then. also can you tell me if you're gonna switch to react hooks in a future version. also you're using thunk are you considering switching to Saga?

**Comment by jlipps** [comment]
no plans right now to update the way we use react/redux
