### ISSUE TITLE
Not able to use Appium Pro web inspector

### ISSUE THREAD

**Issue by LambdaTest-Certifications** [appium/appium-inspector#581]
I am trying to run a test on Appium Pro web inspector however been facing errors from about 2-3 months now. 
Please refer to screenshot shared: 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/76526252/187595300-c298eddf-1183-44b3-910b-dcbaab98dc8d.png">
https://inspector.appiumpro.com/

However same when trying to Appium app, it is working fine there. 
Anyone else facing this or know how to resolve this issue?

- I am on:

    - Windows 11 workstation(laptop)

**Comment by KazuCocoa** [comment]
What error message can you see in the browser's web inspector?

**Comment by jlipps** [comment]
i bet lambda test's server doesn't properly set cross origin request accept headers

**Comment by eglitise** [comment]
Closing this due to no response. The issue is also likely not with Appium Inspector, but with hte LambdaTest server configuration.
