### ISSUE TITLE
Failed to create session. Request timed out when I try to inspect a mobile app from an iOS real device located in Saucelabs cloud platform

### ISSUE THREAD

**Issue by likhoBomvana** [appium/appium-inspector#589]
When creating a new session on Appium using cloud provider saucelabs, i get a Failed to create session, Request timeout , this issue was once logged before.

Here's the url to the issue that was logged, of which is the same issue im now facing on the latest build:https://github.com/appium/appium-inspector/issues/321

other info is that our IPA is about 1 GB to 2 GB, would that be the cause for the response we getting ?

- I am running Appium Inspector Desktop version _<2022.8.1>_.
- I am on (pick one):
    - [ ] Mac
    - [X] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
If you think this is not a problem with sauce labs, please provide more detailed information for us to investigate. Have you reached out to sauce support? Does connecting to sauce with a command line script work?

**Comment by likhoBomvana** [comment]
Im currently waiting for them to get back to me, then i will reach out to you again

**Comment by christophss** [comment]
@jlipps , I tried with JD repl to create a session and it created without issues but when I do it using Appium Inspector, it throws this error due to possible timeout. The session gets created in Sauce Labs slow and the before the session can get created, Appium Inspector stops the request with a error “Failed to create session”

**Comment by jlipps** [comment]
OK, maybe there is some webdriverio connection timeout we can increase somewhere.

**Comment by eglitise** [comment]
Closing due to no response from original reporter
