### ISSUE TITLE
Can not move inspector window, if the the inspector window has focus.

### ISSUE THREAD

**Issue by stephenjg24-git** [appium/appium-inspector#59]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ x] Mac
    - [ ] Windows
    - [ ] Linux

I am running beta 5, this is a UI issue with inspector, not related to anything appium.

Launch the Inspector
click in the top area of the window, keep holding the left ouse button down and try to drag the window to a new area.
This fails

Workaround
Click on an open area on the screen, to move focus away from the inspector
Then repeat the above steps,
This works.

**Comment by jlipps** [comment]
Which mac version do you have? I can't replicate this bug.

**Comment by stephenjg24-git** [comment]
I have the beta 5 version.

**Comment by sme81** [comment]
Getting same bug, workaround doesnt seem to be working. same app version. Mac Catalina

**Comment by jlipps** [comment]
Can you record a video of the bug, with the devtool console log open so I can see any logging that comes through? (Right click > inspect on any element, then select the console).

**Comment by sme81** [comment]
Gist [here](https://gist.github.com/sme81/fc2993a7eb83db32eca4b4c13e369d00) of devtools console after initial opening.

Video here, cleared console, doesnt log anything new when moving...


https://user-images.githubusercontent.com/48491431/126275450-ff2ba880-9410-4324-a659-8e767536fd93.mov

**Comment by jlipps** [comment]
OK thanks. I'm going to try to publish a new version of the inspector. Let's see if it gets rid of the issue.

**Comment by jlipps** [comment]
@sme81 for some reason our publishing flow isn't working. Could you try this instead: https://inspector.appiumpro.com/ (if you need to you can open it up in its own browser window and move and resize to your heart's content).

**Comment by sme81** [comment]
@jlipps yeah opening in browser loads and can move that window about. 

Can't get it connecting to locally hosted devices though, so will just have to wait and use appium-desktop. 

Thanks for looking at this

**Comment by jlipps** [comment]
What error do you get connecting to local devices? That's why I tested while building this.

**Comment by sme81** [comment]
Was missing '--allow-cors' on Appium Server CLI, works now in browser

**Comment by jlipps** [comment]
Ah yes. I need to add that to the error message for easy troubleshooting.

**Comment by Auto81** [comment]
@jlipps works for me :) Will be looking to move team to Appium CLI 2.0 and Inspector combo when ready. Nice Test Tribe vid too
