### ISSUE TITLE
Elements are not getting detected in appium if the actions are done through appium inspector

### ISSUE THREAD

**Issue by karthikeyanParamasivam** [appium/appium-inspector#590]
Facing a weird issue when i do action over appium inspector some of the elements are not reflecting in the dom whereas when do the same action manuall and refresh the UI in the inspector then those elements are reflecting ....!

**Comment by jlipps** [comment]
just hit 'refresh' again. after appium performs an appium it retrieves the page source, but this might happen before the new page is fully loaded. unfortunately there's no way to know when the action's consequences are fully realized. this is why we have a refresh button. does the refresh button cause it to work?

**Comment by karthikeyanParamasivam** [comment]
@jlipps Its not helping in my scenario even after multiple refresh the DOM is not getting updated. but whereas if i do all the actions on the device manually and then if i sync up to the present view i was able to see the locators and proper DOM structure

**Comment by jlipps** [comment]
i think you might need to record a video for me to understand what you are saying

**Comment by eglitise** [comment]
Closing due to no response
