### ISSUE TITLE
In Session window the link to Capabilities Documentation is broken

### ISSUE THREAD

**Issue by rushian** [appium/appium-inspector#603]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ X ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

When we click at Desired Capabilities Documentation link in the Session window it open the broked link:
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md

instead 
http://appium.io/docs/en/writing-running-appium/caps/index.html

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [ x ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
Thanks. that other link will also break with the move to appium 2, but we'll figure it out.

**Comment by neonfink** [comment]
Hi there! Is this issue still to be picked up in future Appium Inspector releases?
I see there is a PR linked above but it currently indeed leads to the old Appium docs (https://appium.io/docs/en/writing-running-appium/caps/index.html) giving a `404` instead of the 2.0 version of the docs

**Comment by jlipps** [comment]
ok got a PR open to fix
