### ISSUE TITLE
Silent installation flags for Windows installer? (2022.8.1)

### ISSUE THREAD

**Issue by jhrabi** [appium/appium-inspector#606]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ X ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I am trying to install Appium Inspector from the EXE file in Releases on Windows 10. When running the executable, we are asked if we want to install for the current user or all users. I want to be able silently install Appium Inspector for the current user as part of an automated process but the install documentation on the README.md does not state any silent install functionality. Does this function exist at all and is not documented? Or is there no way to run this silently?

## Environment

- I am running Appium Desktop version
- I am on (pick one):
    - [ ] Mac
    - [ X ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
No, nothing like this exists as far as I know. We simply use electron-builders exe bundling. I have no idea how windows stuff works. If you can find some setting for electron-builder that allows us to bundle the windows exe with a different set of flags, by all means submit a PR!

**Comment by jhrabi** [comment]
Knowing what you're using to create the EXE is all I needed. I found the electron-builder silent flags here: 

https://github.com/electron-userland/electron-builder/issues/4445#issuecomment-557410197

For anyone else looking for this information, adding /S will install it silently, and you can choose /allusers or /currentuser to choose how you need to install it.

Thanks!

**Comment by jlipps** [comment]
great find!
