### ISSUE TITLE
Appium inspector cannot find some elements

### ISSUE THREAD

**Issue by mark0-77** [appium/appium-inspector#609]
## Appium or Appium Desktop?

- Appium Desktop -------> Appium-Server-GUI-windows-1.22.3-4 
- Appium Inspector -------> Appium-Inspector-windows-2022.8.1

## The problem

Appium inspector can't find some elements, I tried adding "enableMultiWindows: true: and it still doesn't find the elements. The weird thing is that visually they are visible but when trying to locate it is only possible to select one element android.view.View.
I've also tried turning on the "Show element handles" switch and it doesn't identify any of the elements I need (the textbox, yellow button, etc).  I've tried to refresh the screen several times and it has not worked for me either.

Please I need help! 

## Environment

- I am running Appium Desktop version _<Appium-Server-GUI-windows-1.22.3-4 >_.
- I am on (pick one):
    - [ ] Mac
    - [X] Windows
    - [ ] Linux

- My desired capabilities

```
{
  "appium:deviceName": "Galaxy S22 Ultra",
  "appium:udid": "MY_PHONE_ID",
  "platformName": "Android",
  "appium:platformVersion": "12",
  "appium:noReset": true,
  "appium:autoGrantPermissions": true,
  "appium:automationName": "uiautomator2",
  "appium:uninstall": true,
  "appium:enableMultiWindows": true
  "appium:app": "MY_APK_PATH",
}

```
![image](https://user-images.githubusercontent.com/57364757/190290675-c1d7788f-e4c6-45df-9a3f-65088306709a.png)

![image](https://user-images.githubusercontent.com/57364757/190291052-6beac6c3-4899-451e-a30d-a9990c5b437a.png)

**Comment by KazuCocoa** [comment]
Appium's this behavior depends on AccessibilityNodeInfo (by Android), so I guess the system did not recognized them.
enableMultiWindows, ignoreUnimportantViews and allowInvisibleElements are possible options we could configure in uia2.

**Comment by mark0-77** [comment]
@KazuCocoa you're awesome!! 

I tried using  ignoreUnimportantViews and allowInvisibleElements options and it works!!

Thank you man!!
