### ISSUE TITLE
Recorder generated scripts do not fetch coordinates

### ISSUE THREAD

**Issue by Maydrian** [appium/appium-inspector#615]
## Recorder generated scripts do not fetch coordinates
Setup: Connecting with inspector on windows machine to a remote appium server machine (Ubuntu).
All coordinate based recordings like swipe or tap at specific location do not record the actual coordinates.
Instead the generated code refers to them as ([object Object],undefined) which might be some sort of null reference.

Python Code snipped which was recorded by tapping on Coordinates X:500; Y :500:
```
actions = ActionChains(driver)
actions.w3c_actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
actions.w3c_actions.pointer_action.move_to_location([object Object], undefined)
actions.w3c_actions.pointer_action.pointer_down()
actions.w3c_actions.pointer_action.pause(0.1)
actions.w3c_actions.pointer_action.release()
actions.perform()
```
This issue persists over all available output languages.

## Environment

- I am running Appium Inspector version _2022.8.1_ Windows.
- I am running Appium server (remote) version _2.0.0-beta.44_ running on Ubuntu 20.04.
- Unit under test: Google Pixel 2; Android 11
- I am on:
    - [ ] Mac
    - [X] Windows
    - [ ] Linux

**Comment by rushian** [comment]
I will check if the problem is in GestureEditor.js

**Comment by jlipps** [comment]
this is not an issue with gestureeditor, but with the code generation

**Comment by secretrobotron** [comment]
Confirming same problem on inspector with both Mac and Windows on two different Android devices on different OS versions.
