### ISSUE TITLE
Jetpack Compose support

### ISSUE THREAD

**Issue by JuanCarlos-Arceredillo** [appium/appium-inspector#617]
## The problem

My issue is a mix between a question and a request. We have an application implemented with Jetpack Compose, but not all of it. 

Is it possible to run the inspector using espresso-driver configured to work with compose ?

And in case that it could be possible...

Is is possible to switch between compose and espresso with the inspector without resetting it ?

## Environment

- I am running Appium Desktop version 2021.9.2
- I am on (pick one):
    - [ * ] Mac
    - [ ] Windows
    - [ ] Linux

Thank you!

**Comment by KazuCocoa** [comment]
Yes, https://github.com/appium/appium-espresso-driver#jetpack-compose-support

You can switch compose and espresso via settings api.
https://github.com/appium/appium-espresso-driver#settings-api
I haven't attempted via the inspector, but the action is actions -> session -> settings
