### ISSUE TITLE
 Failed to create a new session

### ISSUE THREAD

**Issue by Usnork** [appium/appium-inspector#626]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [X ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
My Appium inspector stopped working and failed to create new session.  Error was: Failed to create session. Unexpected token < in JSON at position 0.
I updated to latest version for both server and inspector didn't make any difference.   I had issues before it stopped working that the app(iOS) I was inspecting hang a few times.  After that, I am not able to start a session for either iOS or Android.  I had not no problem before it happened.  Is there cached data persisted through different installation?
## Environment

- I am running Appium Desktop version _2022.8.1_.
- I am on (pick one):
    - [ X] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Please attach the appium server log as GIST

**Comment by Usnork** [comment]
There is no log in Appium server.  Inspector did not connect to the server yet before the error.

**Comment by Usnork** [comment]
I am imagining there was a cached data(corrupted) from Inspector that caused the problem.  If we know the file path, we could delete it and solve my problem. Isn't it?

**Comment by KazuCocoa** [comment]
Then, could you share your capabilities and connection target info such as remote host/remote path?

Perhaps you can see the HTTP request/response in the Web Inspector (available with right-click's context menu like the attached one). Then, the network capture may also help.

<img width="201" alt="image" src="https://user-images.githubusercontent.com/5511591/193698394-90537539-e3a6-4ec7-afdb-d8fdd3118869.png">

**Comment by Usnork** [comment]
Remote path is: /wd/hub .  Capabilities are:
{
"appium:platformVersion": "11",
  "appium:deviceName": "Pixel 4",
  "appium:udid": "98141FFA-mydevice id",
  "platformName": "Android"
}
It was working fine.

**Comment by Usnork** [comment]
It turned out be a proxy issue. Network error was from a proxy that it was not be able to connect the server.  It will be very helpful if the original error message was displayed.   I will close this issue.
