### ISSUE TITLE
Could not load a driver for automationName 'XCUITest' and platformName 'iOS'. Please verify your Appium installation

### ISSUE THREAD

**Issue by DeliaLing** [appium/appium-inspector#629]
Appium Desktop  Appium inspector

- [ x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

1. Start appium server from GUI version
2. Open appium inspector, add and save below desired capabilities.
3. Connect device
4. Click on start section
Result: Failed to create session. An unknown server-side error occurred while processing the command. Original error: Could not load a driver for automationName 'XCUITest' and platformName 'iOS'. Please verify your Appium installation
 Attached logs: 
[appium logs.rtfd.zip](https://github.com/appium/appium-inspector/files/9748165/appium.logs.rtfd.zip)

{
  "appium:deviceName": "iPhone XR",
  "appium:platformVersion": "16.0",
  "appium:udid": "my device udid",
  "platformName": "iOS",
  "appium:bundleId": "my app bundled",
  "appium:xcodeOrgId": "myorgid",
  "appium:xcodeSigningId": "iPhone Developer",
  "appium:fullReset": false,
  "appium:noReset": true,
  "appium:automationName": "XCUITest",
  "appium:newCommandTimeout": "30000",
  "appium:wdaEventloopIdleDelay": "5",
  "appium:waitForQuiescence": false,
  "appium:useNewWDA": true,
  "appium:wdaLaunchTimeout": "999999",
  "appium:wdaConnectionTimeout": "999999"
}

## Environment

- I am running Appium Desktop version _<1.22.3-4>_.
- Appium inspector-2022.9.1
- I am on (pick one):
    - [x ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by DeliaLing** [comment]
Hi @sudharsan-selvaraj  I am using appium GUI v1.22.3-4

**Comment by KazuCocoa** [comment]
Could you share the appium server log?

**Comment by DeliaLing** [comment]
Hi @KazuCocoa , here is the appium log. Thanks.
[Appiumlogs-2.rtfd.zip](https://github.com/appium/appium-inspector/files/9758196/Appiumlogs-2.rtfd.zip)

**Comment by KazuCocoa** [comment]
> Downloaded web driver agent v4.9.0 and use it to replace the original web driver agent, the issue in step 4 is no more happened. able to see web agent driver installed in app and trusted it from settings

Did you build the JavaScript code after the replacement? WDA repository has JS code as well, so simple replacement could break JS code. If you'd like to change WDA only, you may need to do something like https://github.com/appium/appium/issues/17497#issuecomment-1275191319

As an inspector, we'd recommend to use `appium` CLI and attach to it

**Comment by jlipps** [comment]
It would be much, much simpler to just start Appium from the command line and not use the server GUI at all. It is not maintained or updated and will only be a headache.

**Comment by jlipps** [comment]
It would be much, much simpler to just start Appium from the command line and not use the server GUI at all. It is not maintained or updated and will only be a headache.

**Comment by jlipps** [comment]
It would be much, much simpler to just start Appium from the command line and not use the server GUI at all. It is not maintained or updated and will only be a headache.

**Comment by DeliaLing** [comment]
> > Downloaded web driver agent v4.9.0 and use it to replace the original web driver agent, the issue in step 4 is no more happened. able to see web agent driver installed in app and trusted it from settings
> 
> Did you build the JavaScript code after the replacement? WDA repository has JS code as well, so simple replacement could break JS code. If you'd like to change WDA only, you may need to do something like [appium/appium#17497 (comment)](https://github.com/appium/appium/issues/17497#issuecomment-1275191319)
> 
> As an inspector, we'd recommend to use `appium` CLI and attach to it

Thanks @KazuCocoa , it is working now after replacing WDA related files as screenshot attached. fully replacement caused the issue.
<img width="282" alt="WebDriverAgent-4_9_0_and_appium-webdriveragent_and_WebDriverAgent-4_9_0" src="https://user-images.githubusercontent.com/115450980/195464853-3e7e67c4-f841-4513-ae03-ca2ebbd0e706.png">

**Comment by DeliaLing** [comment]
@KazuCocoa I replaced these files only, it works for one time only, can you please help to check if any other files should be replaced ? or which exact folders below I need to keep? Thanks.
<img width="907" alt="appium-webdriveragent" src="https://user-images.githubusercontent.com/115450980/195674897-c66977ca-41c1-4653-86ed-2d333d556090.png">

**Comment by KazuCocoa** [comment]
What error did you get? Usually, the building itself happens in a cache by xcodebuild, so if no change happened after the copy, it is maybe xcodebuild internal stuff

**Comment by DeliaLing** [comment]
Hi @KazuCocoa, it failed in WDALib test-integration3Tests after replaced five files in WDA folder (The replaced files are highlighted in screenshot above). Attached log: 
[WDALib-TestLog.txt](https://github.com/appium/appium-inspector/files/9793964/WDALib-TestLog.txt)

Other: Web driver agent runner can be built and tested successfully.
++++++++++++++++++++++++++++++++
Appium-1.22.4
Xcode: 14.0.1
iOS: v16.0.2
