### ISSUE TITLE
build the inspector for production gives error: Cannot read properties of undefined (reading 'directConnectProtocol')

### ISSUE THREAD

**Issue by Mehdi-HAFID** [appium/appium-inspector#631]
## The problem

I have this command to build for production:
`"build:prod:browser:2": "cross-env BUILD_BROWSER=1 NODE_ENV=production parcel build --no-content-hash --out-dir ./dist-browser --target browser --public-url . ./app/renderer/index.html",`

this build successfully.

and this one to start a server and serve the inspector:
`"deploy:prod:browser": "serve -l 1234 ./dist-browser",`
 this start a serve server and deploy the inspector. the problem is I get this error: 
`Cannot read properties of undefined (reading 'directConnectProtocol')`

I'm just trying to build and deploy for production, can you please help do this. Thanks.

## Environment

- I am running Appium version 2022.7.1.
- I am on :
    - [x] Windows

**Comment by jlipps** [comment]
Feel free to submit a PR to update the README, and the build command! the README is primarily for users, not for developers. Most users would never have any need to build the app as it is downloadable from the releases page and available online already.
