### ISSUE TITLE
Not connecting to appium grid using appium inspector - showing unknown device or udid

### ISSUE THREAD

**Issue by krishtoautomate** [appium/appium-inspector#637]
Not connecting to appium grid using appium inspector - showing udid not found.

Same connection with same capabilities working fine with code in IDE or jenkins.

**Comment by krishtoautomate** [comment]
<img width="895" alt="image" src="https://user-images.githubusercontent.com/20734341/196272749-5c69c6f8-6a8e-47dd-ac38-af4922aa6a69.png">

**Comment by KazuCocoa** [comment]
Could you share the full appium server log?

**Comment by krishtoautomate** [comment]
I think its not reaching Appium server and it is failing to create a session with grid itself. Is their anyway to check logs of inspector?

**Comment by KazuCocoa** [comment]
You can see the request itself via the web inspector. (available right click -> inspect element as same as general web browser's inspect element in chromium)

**Comment by krishtoautomate** [comment]
Connects 1 in 10 times to same device without modifying any settings

**Comment by KazuCocoa** [comment]
So, appium-inspector sent the same capabilities, but the grid replied back to the error, correct?
(Not this inspector's issue, or not)

**Comment by krishtoautomate** [comment]
<img width="872" alt="image" src="https://user-images.githubusercontent.com/20734341/196313102-b038adb2-bb85-4006-a878-20b6c533195f.png">

**Comment by krishtoautomate** [comment]
{"value":{"error":"unknown error","message":"An unknown server-side error occurred while processing the command. Original error: Unknown device or simulator UDID: '00008110-000C341826B9401E'","stacktrace":"UnknownError: An unknown server-side error occurred while processing the command. Original error: Unknown device or simulator UDID: '00008110-000C341826B9401E'\n    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)\n    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)"}}

**Comment by krishtoautomate** [comment]
retrying multiple times connects without making any changes :

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/20734341/196314629-43494578-d84d-452e-bbd7-f1da5ddb6c7a.png">

**Comment by krishtoautomate** [comment]
> So, appium-inspector sent the same capabilities, but the grid replied back to the error, correct? (Not this inspector's issue, or not)

seeing this issue with appium inspector only and not with java code

**Comment by KazuCocoa** [comment]
What Java client did you use? v8? appium-inspecotor itself depends on webdriverio https://github.com/webdriverio/webdriverio as the appium client, so the same issue might occur in the webdriverio as well, then.


Btw, where was the appium server running? `/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9` It means the request reached the appium server, so you may be able to get the appium server log, correct?

**Comment by krishtoautomate** [comment]
Request is not reaching appium server. it is failing in 1-2 seconds.

Java client: implementation 'io.appium:java-client:7.6.0'

**Comment by krishtoautomate** [comment]
failing to handshake with grid itself i guess.

**Comment by KazuCocoa** [comment]
Sorry, I'm confused. The stacktrace in your attached error message indicated the error was by `/usr/local/lib/node_modules/appium`. It is an appium server installed in somewhere, not selenium grid.

> {"value":{"error":"unknown error","message":"An unknown server-side error occurred while processing the command. Original error: Unknown device or simulator UDID: '00008110-000C341826B9401E'","stacktrace":"UnknownError: An unknown server-side error occurred while processing the command. Original error: Unknown device or simulator UDID: '00008110-000C341826B9401E'\n at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)\n at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)"}}

**Comment by krishtoautomate** [comment]
im confused as well with the error. may be it is trying to hit my local appium-base-driver or grid machine appium-base-driver. 

I checked the logs and It is not reaching my node appium for sure.

**Comment by KazuCocoa** [comment]
then, could you share the appium server log when you run the Java client code as GIST?

**Comment by krishtoautomate** [comment]
nodes % tail -f /tmp/4723.log
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.22.3"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 68
[HTTP] 
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8388/session/1EE11E3D-8B56-4054-9B76-58407E0EC9C7/element] with body: {"using":"xpath","value":"//XCUIElementTypeButton[@name='Try Again']"}
[WD Proxy] Got response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'xpath', value '//XCUIElementTypeButton[@name='Try Again']'","traceback":"(\n\t0   WebDriverAgentLib                   0x00000001083fc320 FBNoSuchElementErrorResponseForRequest + 252\n\t1   WebDriverAgentLib                   0x00000001083fc150 +[FBFindElementCommands handleFindElement:] + 308\n\t2   WebDriverAgentLib                   0x00000001083c38cc -[FBRoute_TargetAction mountRequest:intoResponse:] + 168\n\t3   WebDriverAgentLib                   0x00000001083aff68 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 400\n\t4   WebDriverAgentLib                   0x00000001083e478c -[RoutingHTTPServer handleRoute:withRequest:response:] + 160\n\t5   WebDriverAgentLib                   0x00000001083e5218 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 64\n\t6   libdispatch.dylib                   0x00000001b5e35fdc C663D847-B94F-3FB0-9254-32EDBC55315E + 16348\n\t7   libdispatch...
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[debug] [BaseDriver] Waited for 3701 ms so far
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8388/session/1EE11E3D-8B56-4054-9B76-58407E0EC9C7/element] with body: {"using":"xpath","value":"//XCUIElementTypeButton[@name='Try Again']"}
[WD Proxy] Got response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'xpath', value '//XCUIElementTypeButton[@name='Try Again']'","traceback":"(\n\t0   WebDriverAgentLib                   0x00000001083fc320 FBNoSuchElementErrorResponseForRequest + 252\n\t1   WebDriverAgentLib                   0x00000001083fc150 +[FBFindElementCommands handleFindElement:] + 308\n\t2   WebDriverAgentLib                   0x00000001083c38cc -[FBRoute_TargetAction mountRequest:intoResponse:] + 168\n\t3   WebDriverAgentLib                   0x00000001083aff68 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 400\n\t4   WebDriverAgentLib                   0x00000001083e478c -[RoutingHTTPServer handleRoute:withRequest:response:] + 160\n\t5   WebDriverAgentLib                   0x00000001083e5218 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 64\n\t6   libdispatch.dylib                   0x00000001b5e35fdc C663D847-B94F-3FB0-9254-32EDBC55315E + 16348\n\t7   libdispatch...
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[debug] [BaseDriver] Waited for 4403 ms so far
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8388/session/1EE11E3D-8B56-4054-9B76-58407E0EC9C7/element] with body: {"using":"xpath","value":"//XCUIElementTypeButton[@name='Try Again']"}
[WD Proxy] Got response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'xpath', value '//XCUIElementTypeButton[@name='Try Again']'","traceback":"(\n\t0   WebDriverAgentLib                   0x00000001083fc320 FBNoSuchElementErrorResponseForRequest + 252\n\t1   WebDriverAgentLib                   0x00000001083fc150 +[FBFindElementCommands handleFindElement:] + 308\n\t2   WebDriverAgentLib                   0x00000001083c38cc -[FBRoute_TargetAction mountRequest:intoResponse:] + 168\n\t3   WebDriverAgentLib                   0x00000001083aff68 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 400\n\t4   WebDriverAgentLib                   0x00000001083e478c -[RoutingHTTPServer handleRoute:withRequest:response:] + 160\n\t5   WebDriverAgentLib                   0x00000001083e5218 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 64\n\t6   libdispatch.dylib                   0x00000001b5e35fdc C663D847-B94F-3FB0-9254-32EDBC55315E + 16348\n\t7   libdispatch...
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[debug] [W3C (feec6878)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[debug] [W3C (feec6878)]     at XCUITestDriver.doNativeFind (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:130:11)
[debug] [W3C (feec6878)]     at runMicrotasks (<anonymous>)
[debug] [W3C (feec6878)]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[debug] [W3C (feec6878)]     at XCUITestDriver.findNativeElementOrElements (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:90:10)
[debug] [W3C (feec6878)]     at XCUITestDriver.findElOrEls (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:23:12)
[debug] [W3C (feec6878)]     at XCUITestDriver.findElOrElsWithProcessing (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:33:12)
[debug] [W3C (feec6878)]     at XCUITestDriver.findElement (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:53:10)
[HTTP] <-- POST /wd/hub/session/feec6878-d66a-4f74-8d97-a8b43ffa0daf/element 404 5103 ms - 1072
[HTTP] 
[HTTP] --> POST /wd/hub/session/feec6878-d66a-4f74-8d97-a8b43ffa0daf/element
[HTTP] {"using":"-ios predicate string","value":"type == 'XCUIElementTypeButton' AND name IN {'Continue Button','Not Now'}"}
[debug] [W3C (feec6878)] Calling AppiumDriver.findElement() with args: ["-ios predicate string","type == 'XCUIElementTypeButton' AND name IN {'Continue Button','Not Now'}","feec6878-d66a-4f74-8d97-a8b43ffa0daf"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id, css selector
[debug] [BaseDriver] Waiting up to 5000 ms for condition
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8388/session/1EE11E3D-8B56-4054-9B76-58407E0EC9C7/element] with body: {"using":"predicate string","value":"type == 'XCUIElementTypeButton' AND name IN {'Continue Button','Not Now'}"}
[WD Proxy] Got response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'predicate string', value 'type == 'XCUIElementTypeButton' AND name IN {'Continue Button','Not Now'}'","traceback":"(\n\t0   WebDriverAgentLib                   0x00000001083fc320 FBNoSuchElementErrorResponseForRequest + 252\n\t1   WebDriverAgentLib                   0x00000001083fc150 +[FBFindElementCommands handleFindElement:] + 308\n\t2   WebDriverAgentLib                   0x00000001083c38cc -[FBRoute_TargetAction mountRequest:intoResponse:] + 168\n\t3   WebDriverAgentLib                   0x00000001083aff68 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 400\n\t4   WebDriverAgentLib                   0x00000001083e478c -[RoutingHTTPServer handleRoute:withRequest:response:] + 160\n\t5   WebDriverAgentLib                   0x00000001083e5218 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 64\n\t6   libdispatch.dylib                   0x00000001b5e35fdc C663D847-B94F-3FB0-92...
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[debug] [BaseDriver] Waited for 113 ms so far
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8388/session/1EE11E3D-8B56-4054-9B76-58407E0EC9C7/element] with body: {"using":"predicate string","value":"type == 'XCUIElementTypeButton' AND name IN {'Continue Button','Not Now'}"}
[WD Proxy] Got response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'predicate string', value 'type == 'XCUIElementTypeButton' AND name IN {'Continue Button','Not Now'}'","traceback":"(\n\t0   WebDriverAgentLib                   0x00000001083fc320 FBNoSuchElementErrorResponseForRequest + 252\n\t1   WebDriverAgentLib                   0x00000001083fc150 +[FBFindElementCommands handleFindElement:] + 308\n\t2   WebDriverAgentLib                   0x00000001083c38cc -[FBRoute_TargetAction mountRequest:intoResponse:] + 168\n\t3   WebDriverAgentLib                   0x00000001083aff68 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 400\n\t4   WebDriverAgentLib                   0x00000001083e478c -[RoutingHTTPServer handleRoute:withRequest:response:] + 160\n\t5   WebDriverAgentLib                   0x00000001083e5218 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 64\n\t6   libdispatch.dylib                   0x00000001b5e35fdc C663D847-B94F-3FB0-92...
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[debug] [BaseDriver] Waited for 725 ms so far
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8388/session/1EE11E3D-8B56-4054-9B76-58407E0EC9C7/element] with body: {"using":"predicate string","value":"type == 'XCUIElementTypeButton' AND name IN {'Continue Button','Not Now'}"}
[WD Proxy] Got response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'predicate string', value 'type == 'XCUIElementTypeButton' AND name IN {'Continue Button','Not Now'}'","traceback":"(\n\t0   WebDriverAgentLib                   0x00000001083fc320 FBNoSuchElementErrorResponseForRequest + 252\n\t1   WebDriverAgentLib                   0x00000001083fc150 +[FBFindElementCommands handleFindElement:] + 308\n\t2   WebDriverAgentLib                   0x00000001083c38cc -[FBRoute_TargetAction mountRequest:intoResponse:] + 168\n\t3   WebDriverAgentLib                   0x00000001083aff68 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 400\n\t4   WebDriverAgentLib                   0x00000001083e478c -[RoutingHTTPServer handleRoute:withRequest:response:] + 160\n\t5   WebDriverAgentLib                   0x00000001083e5218 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 64\n\t6   libdispatch.dylib                   0x00000001b5e35fdc C663D847-B94F-3FB0-92...
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[debug] [BaseDriver] Waited for 1337 ms so far
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8388/session/1EE11E3D-8B56-4054-9B76-58407E0EC9C7/element] with body: {"using":"predicate string","value":"type == 'XCUIElementTypeButton' AND name IN {'Continue Button','Not Now'}"}
[WD Proxy] Got response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'predicate string', value 'type == 'XCUIElementTypeButton' AND name IN {'Continue Button','Not Now'}'","traceback":"(\n\t0   WebDriverAgentLib                   0x00000001083fc320 FBNoSuchElementErrorResponseForRequest + 252\n\t1   WebDriverAgentLib                   0x00000001083fc150 +[FBFindElementCommands handleFindElement:] + 308\n\t2   WebDriverAgentLib                   0x00000001083c38cc -[FBRoute_TargetAction mountRequest:intoResponse:] + 168\n\t3   WebDriverAgentLib                   0x00000001083aff68 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 400\n\t4   WebDriverAgentLib                   0x00000001083e478c -[RoutingHTTPServer handleRoute:withRequest:response:] + 160\n\t5   WebDriverAgentLib                   0x00000001083e5218 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 64\n\t6   libdispatch.dylib                   0x00000001b5e35fdc C663D847-B94F-3FB0-92...
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[debug] [BaseDriver] Waited for 1948 ms so far
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8388/session/1EE11E3D-8B56-4054-9B76-58407E0EC9C7/element] with body: {"using":"predicate string","value":"type == 'XCUIElementTypeButton' AND name IN {'Continue Button','Not Now'}"}
[WD Proxy] Got response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'predicate string', value 'type == 'XCUIElementTypeButton' AND name IN {'Continue Button','Not Now'}'","traceback":"(\n\t0   WebDriverAgentLib                   0x00000001083fc320 FBNoSuchElementErrorResponseForRequest + 252\n\t1   WebDriverAgentLib                   0x00000001083fc150 +[FBFindElementCommands handleFindElement:] + 308\n\t2   WebDriverAgentLib                   0x00000001083c38cc -[FBRoute_TargetAction mountRequest:intoResponse:] + 168\n\t3   WebDriverAgentLib                   0x00000001083aff68 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 400\n\t4   WebDriverAgentLib                   0x00000001083e478c -[RoutingHTTPServer handleRoute:withRequest:response:] + 160\n\t5   WebDriverAgentLib                   0x00000001083e5218 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 64\n\t6   libdispatch.dylib                   0x00000001b5e35fdc C663D847-B94F-3FB0-92...
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[debug] [BaseDriver] Waited for 2560 ms so far
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8388/session/1EE11E3D-8B56-4054-9B76-58407E0EC9C7/element] with body: {"using":"predicate string","value":"type == 'XCUIElementTypeButton' AND name IN {'Continue Button','Not Now'}"}
[WD Proxy] Got response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'predicate string', value 'type == 'XCUIElementTypeButton' AND name IN {'Continue Button','Not Now'}'","traceback":"(\n\t0   WebDriverAgentLib                   0x00000001083fc320 FBNoSuchElementErrorResponseForRequest + 252\n\t1   WebDriverAgentLib                   0x00000001083fc150 +[FBFindElementCommands handleFindElement:] + 308\n\t2   WebDriverAgentLib                   0x00000001083c38cc -[FBRoute_TargetAction mountRequest:intoResponse:] + 168\n\t3   WebDriverAgentLib                   0x00000001083aff68 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 400\n\t4   WebDriverAgentLib                   0x00000001083e478c -[RoutingHTTPServer handleRoute:withRequest:response:] + 160\n\t5   WebDriverAgentLib                   0x00000001083e5218 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 64\n\t6   libdispatch.dylib                   0x00000001b5e35fdc C663D847-B94F-3FB0-92...
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[debug] [BaseDriver] Waited for 3233 ms so far
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.22.3"}}

**Comment by KazuCocoa** [comment]
> {"desiredCapabilities":{"server:CONFIG_UUID":"34659b82-a16d-4e43-a1ca-0d67a5fdff6a","noReset":false,"bundleId":"com.apple.TestFlight","autoDismissAlerts":true,"deviceName":"iPhone 14 Pro","fullReset":false,"wdaLocalPort":8388,"wdaStartupRetryInterval":2000,"autoLaunch":true,"newCommandTimeout":120,"platformVersion":"12.2","automationName":"XCUITest","wdaStartupRetries":2,"platformName":"ios","udid":"00008120-000E656011D3401E"},"capabilities":{"firstMatch":[{"platformName":"ios","server:CONFIG_UUID":"34659b82-a16d-4e43-a1ca-0d67a5fdff6a"}]}}

The request only had old protocol, which is not W3C. Then, appium 2 and appium-inspector do not work since they follow w3c webdriver protocol as the primary method. Java v7 can work since it sends both protocol, but v8 won't work.

You can use https://github.com/appium/appium-desktop's inspector pert for your use case.

**Comment by krishtoautomate** [comment]
why apply w3c rules to appium inspector? isn't it used for debugging and people might use it for some new or custom capabilities and might face unrequired errors or completely blocked.
Why not just add warnings?

**Comment by KazuCocoa** [comment]
Since Appium inspector is designed for appium 2 as its readme. The appium 2 expects w3c, so appium-inspector also follows it. Appium itself has been supported both protocol for long since maybe v1.10 or around, so this inspector change should not break them.

In this (i guess grid v3?) case, it seems like your grid config? partially converted requests as

> "capabilities":{"firstMatch":[{"platformName":"ios","server:CONFIG_UUID":"34659b82-a16d-4e43-a1ca-0d67a5fdff6a"}]}}

(I'm not so familiar with the grid configuration though)

So, as the inspector, maybe it can leave a note to use the old appium-desktop for grid v3 as it may have an issue in the inspector.

**Comment by krishtoautomate** [comment]
Im still using grid v2, with custom capability matcher udid.

Can you me to make it work with appium:udid

**Comment by KazuCocoa** [comment]
Perhaps it can by specifying grid config with `appium:` capabilities: https://discuss.appium.io/t/grid-appium-and-custom-capabilities/23800

I'm not sure how grid v3 is compatible w3c spec, so potentially it has difficulties in the grid itself.

https://discuss.appium.io/ may help to ask questions.

**Comment by krishtoautomate** [comment]
fixed. changed capabilityMatcher to match appium:$UDID with node capability $UDID in Grid2.
thanks
