### ISSUE TITLE
what is the default location for Inspector on Windows 10?

### ISSUE THREAD

**Issue by oldpride** [appium/appium-inspector#638]
## Appium or Appium Desktop?
I am using Appium Desktop and it asked me to install Appium Inspector to view more details.

## The problem
I came to this site and downloaded the zip file. But neither in the zip file nor in the github's README file mentioned where I should unzip the downloaded zip file. I assume that I need to unzip it to somewhere that Appium Desktop would look for it.

I didn't download the .exe file because of anti-virus reason.

## Environment

- I am running Appium Desktop version v1.22.3
- I am on Windows 10

**Comment by oldpride** [comment]
default location is C:\Program Files\Appium Inspector

**Comment by jlipps** [comment]
You can put it anywhere. Appium Desktop won't look for it. The apps are not related.
