### ISSUE TITLE
Appium Inspector does not show element ID's for webview content

### ISSUE THREAD

**Issue by Vishnuakkireddy** [appium/appium-inspector#641]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

The app that we automate have few screens where we need to switch to webview. But when trying to find any element ID's it does not  show any such references to create xpath. The issue is with android device

## Environment

- I am running Appium Desktop version _<V1.22.3>_.
- Appium inspector version _<2022.9.1>
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
did you switch to  webview mode and then choose the appropriate webview in the inspector?

it would help to evaluate this issue to include a detailed report of what you did, or even a video

**Comment by eglitise** [comment]
Closing due to no response
