### ISSUE TITLE
Appium inspector cannot find some elements

### ISSUE THREAD

**Issue by stefanie0722** [appium/appium-inspector#657]
## Appium or Appium Desktop?

Appium Inspector -------> Appium-Inspector-windows-2022.5.4

## The problem

I use Appium inspector to find element in attach picture 1, I tried to click the element which is a arrow button to call a dropdown list. But in Appium inspector, it can not recognize the arrow button, the button and the edit test are recognized as a view together.
I have tried to add enableMultiWindows, ignoreUnimportantViews and allowInvisibleElements, but it still doesn't work.

## Environment

- I am running Appium-Inspector-windows-2022.5.4
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

## My desired capabilities
`{
  "appium:platformName": "Android",
  "appium:platformVersion": "10",
  "appium:deviceName": "HUAWEI LIO-AN00",
  "appium:appPackage": "com.foreverht.workplus.hcbmpre",
  "appium:appActivity": "com.foreveross.atwork.modules.main.activity.SplashActivity",
  "appium:noReset": "true",
  "uftm:oauthClientId": "oauth2-JteND1rXqIXZ3dBhUwuD@microfocus.com",
  "uftm:oauthClientSecret": "avYdaJv6kqOj6nn6433E",
  "uftm:tenantId": "999999999",
  "appium:automationName": "uiautomator2",
  "appium:ignoreUnimportantViews": true,
  "appium:enableMultiWindows": true,
  "appium:allowInvisibleElements": true
}`
![1](https://user-images.githubusercontent.com/83010970/201296441-599bd5aa-719b-4955-b440-723868163564.png)
![2](https://user-images.githubusercontent.com/83010970/201299537-8620e8a2-513e-4a66-97ff-070737c79a83.png)

**Comment by jlipps** [comment]
In this case it must be that the element is not visible to the accessibility system. Consider getting the devs to make the element accessible. Or if you're writing a script, find the element next to it and then generate a location based tap based on the sibling element's position.
