### ISSUE TITLE
The App Source section is small on start, but when there's too many elements it scrolls the whole content

### ISSUE THREAD

**Issue by Hristovski** [appium/appium-inspector#664]
## The problem

_The App Source section is small on start, but when there's too many elements it scrolls the whole content_

## Environment

- I am running Appium Inspector version _2022.11.1_.
- I am on (pick one):
    - [X] Mac
    - [x] Windows
    - [ ] Linux

![Screenshot 2022-11-16 at 12 54 47 AM](https://user-images.githubusercontent.com/4580306/202049591-10288293-2ba7-4d1d-8f9e-5715cc8bad45.png)

![Screenshot 2022-11-16 at 12 47 56 AM](https://user-images.githubusercontent.com/4580306/202049354-318be706-2306-4156-a640-f1846df8d747.png)

**Comment by Hristovski** [comment]
Reproducible on Windows 11 too.

![Untitled](https://user-images.githubusercontent.com/4580306/202051797-bddaf1c7-a2d3-4761-9b13-ee9f7ded882b.jpg)

**Comment by jlipps** [comment]
seems like a regression due to a css library dependency. i see it too.

**Comment by Hristovski** [comment]
The issue is still reproducible in 2023.2.1

**Comment by jlipps** [comment]
Yes, no work has been done to resolve this issue.

**Comment by vrnvorona** [comment]
Still no fix? If it's just css issue isn't it easy to fix, plus there was PR with fix already.

**Comment by jlipps** [comment]
The fix will be in 2023.3.1
