### ISSUE TITLE
Unable to download Windows .exe build

### ISSUE THREAD

**Issue by YingLu16** [appium/appium-inspector#667]
i download the latest version(2022-11) appnium inspector almost all the night , and get the same response "network problem"
for that, i use laptop dowmload other resource but no same statement
pls check whether the windows_exe download link contains the right source, or server problems
today is 2022-11-26, i am waiting for update
thanks

**Comment by KazuCocoa** [comment]
Do you mean you failed to download .exe https://github.com/appium/appium-inspector/releases/download/v2022.11.1/Appium-Inspector-windows-2022.11.1.exe ?

I was able to download it, and succeeded in starting the exe on a Windows laptop. Then, an installation started, the inspector was installed and succeeded in starting the process.

**Comment by YingLu16** [comment]
> 

hi Cocoa:
thanks for your reply,anyway, i try a lot of times to download windows_exe, it run as low speed firstly and then cancelled express"network issue" , when i restart the steps three or four times in the cancelled download file , it would come out authorisation issue.
for test whether is network problem, i download new software and some music source, it run nomarl.
thus, i think that maybe appnium inspector exists some defects,which i download is exactly https://github.com/appium/appium-inspector/releases/download/v2022.11.1/Appium-Inspector-windows-2022.11.1.exe
i am waiting for your response, best wishes!
![微信图片_20221127103359](https://user-images.githubusercontent.com/56776286/204116652-72a8c896-f360-4923-a52c-9a016d3021fe.png)

**Comment by KazuCocoa** [comment]
What about other packages? I mean not only exe but also dmg etc. I wonder if your environment is not good for downloading GitHub release’s artifacts.

**Comment by rushian** [comment]
here the download works normally

**Comment by eglitise** [comment]
Closing due to no response
