### ISSUE TITLE
prefixed with "appium:" are set repeatedly

### ISSUE THREAD

**Issue by youngfreeFJS** [appium/appium-inspector#68]
## Appium or Appium Desktop?

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
prefixed with "appium:" are set repeatedly while I click the _**startSession**_ button .
It seems that because of this [PR](https://github.com/appium/appium-inspector/pull/65/files#diff-cc0a8b1e7efd7e5b9ee01a00c256283251315b2c0c18cca08911fef1c01fa0b9R181
).
@jlipps 

https://user-images.githubusercontent.com/46949537/125063592-3e74ba00-e0e2-11eb-9117-4414f9af529c.mov

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

- branch: main

**Comment by jlipps** [comment]
Hmm OK. I checked for this case. I will check again.

**Comment by jlipps** [comment]
OK have a PR up, it was a typo
