### ISSUE TITLE
Test did not see a new command for 90 seconds. Timing out. - Saucelabs

### ISSUE THREAD

**Issue by rdhandapani88** [appium/appium-inspector#685]
Appium Inspector

- [ x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

I was trying to connect in to Saucelabs simulator devices, using the Appium inspector with Saucelabs credentials. I is hitting saucelabs and session is created and I can successfully see the app is installed in the simulator and webdriveragent is also installing in the simulator. But Once the app launches, we are getting error in Appium inspector like "Failed to create session. Request timed out", and at Saucelabs we are seeing error like "Test did not see a new command for 90 seconds. Timing out."

## Environment
My desired Capabilities

{
  "appium:deviceName": "iPhone 11 Simulator",
  "platformName": "iOS",
  "appium:app": "storage:filename=xxxxxxxxxx.2.zip",
  "appium:platformVersion": "15.4",
  "appium:automationName": "XCUITest",
  "appium:appiumVersion": "1.22.0",
  "sauce:options": {
    "appium:privateDevicesOnly": true,
    "appium:phoneOnly": true,
    "name": "Appium Desktop Session -- Dec 14, 2022 5:17 PM"
  },
  "browserName": "",
  "appium:newCommandTimeout": "1800"
}

Note:
It worked couple of times without any issue, later something broken I Cannot inspect the simulator from Saucelabs

- I am running Appium Desktop version _<2022.11.1>_.
- I am on 
    - [ x] Mac

**Comment by jlipps** [comment]
Anything in the console log from the inspector? This isn't really enough to go on to investigate. Seems like maybe the new session response from sauce labs is not what the inspector expects

**Comment by rdhandapani88** [comment]
@jlipps , There is no much logs from inspector to identify the issues. But now I am able to connect to Saucelabs after introducing "appium:wdaConnectionTimeout": "65000" in desired capabilities. Thanks for jumping in. Will keep posted, We can close this as of now.

**Comment by jlipps** [comment]
sounds good
