### ISSUE TITLE
Appium Inspector not respecting the UDID of my simulated iOS device to inspect

### ISSUE THREAD

**Issue by Sam-Levene** [appium/appium-inspector#687]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I am trying to inspect a device with a UDID of DC563E3E-F30E-4A04-AFEC-066E89E74008; this is a local virtual simulated device that I wish to inspect using the inspector and I am specifying as such in the Desired Capabilities; instead; when I launch the inspector; I can see that, in my appium logs, it is actually using a different device with UDID of 87716616-92B5-411E-B3FE-85A89D40AA5C and launches that device instead. Both devices are virtual devices and are XCode Simulators designed specifically for this purpose:

<img width="876" alt="Screenshot 2023-01-04 at 10 09 43" src="https://user-images.githubusercontent.com/19433453/210532231-cc54cbd2-8497-416c-a042-82bf8a6fbd42.png">

Why is the inspector not inspecting against the correct device UDID; even when it is supplied in the desired capabilities:

<img width="601" alt="Screenshot 2023-01-04 at 10 07 52" src="https://user-images.githubusercontent.com/19433453/210531761-2c8c76ad-69cd-4e66-8da1-58d3e34fe034.png">

## Environment

- I am running Appium Desktop version: **2022.11.1**
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
the simulator is sending your capability to the server just fine. so this is not a simulator issue. please report instead with a full set of logs at the appium repo.
