### ISSUE TITLE
request has been blocked by CORS policy when I use "watch:browser"

### ISSUE THREAD

**Issue by youngfreeFJS** [appium/appium-inspector#69]
## Appium or Appium Desktop?

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

![image](https://user-images.githubusercontent.com/46949537/125064715-8516e400-e0e3-11eb-9136-0c2ed4dd2ab8.png)

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
The appium server must be started with `--allow-cors` if you wish to use the browser version.

**Comment by jlipps** [comment]
With Electron we can disable CORS checks, but we cannot do this as a webpage.
