### ISSUE TITLE
still unable to open inspector in macOS 13.1

### ISSUE THREAD

**Issue by Arjunmettu** [appium/appium-inspector#692]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

still unable to open inspector in macOS 13.1
## Environment
mac)S 13.1 Ventura

- I am running Appium Desktop version _1.22.3_.
- I am on (pick one):
    - [ ] Mac
<img width="336" alt="image" src="https://user-images.githubusercontent.com/116766605/213358930-6df7532b-d537-4ab8-a3d6-e81affdfde43.png">
<img width="336" alt="Screenshot 2023-01-19 at 04 57 39" src="https://user-images.githubusercontent.com/116766605/213358986-2df3bda5-8e18-4dd2-9817-5424ad5505ff.png">

**Comment by jlipps** [comment]
did you follow the instructions in the readme? https://github.com/appium/appium-inspector#installing-on-macos

**Comment by Jose-Luis-Nunez** [comment]
helped me -> xattr -cr "/Applications/Appium Inspector.app"

 https://appium.github.io/appium-inspector/latest/quickstart/installation/
