### ISSUE TITLE
Keyword Tap from robot framework is deprecated

### ISSUE THREAD

**Issue by rushian** [appium/appium-inspector#695]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ x ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

In robot framework the keyword Tap now is "Tap with positions" and the way to use it have changed too...

## Environment

- I am running Appium Desktop version _2022.11.1_.
- I am on (pick one):
    - [ ] Mac
    - [ x ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
Cool, mind submitting a PR? I don't know anything about robot framework.

**Comment by jlipps** [comment]
Ah I see you did. Thanks.

**Comment by rushian** [comment]
> Ah I see you did. Thanks.

You are welcome...
