### ISSUE TITLE
'Get timing' feature for User's own created locators.

### ISSUE THREAD

**Issue by swap12875** [appium/appium-inspector#698]
## 'Get timing' feature should extended to Users locators beyond the appium suggested locators only (must have feature)?

While using appium inspector, the locators which appium is suggesting are displayed on the right 'Selected Element' panel, On the same panel it have Icon of 'Hour glass'(Get timing) by which the appium gives the time taken to find that element with particular locators strategy and selectors.
But when user search the element with their own selector and strategy, he is not able to check the time taken on the UI to find that element. So It is highly Good to have rather I say must to have feature on the inspector that **'User can check the time for their own designed/created selectors and strategies on the Inspector'**

## The problem

User is not able to check the time taken by their own preferred strategies and locators to find the elements.

## Environment

- I am running Appium Desktop version _<App Version: 2022.11.1>_.;  Electron: 13.6.9;  Node.js: 14.16.0

- I am on (pick one):
    - [ ] Mac
    
## Snapshot

![Monosnap Appium 2023-01-29 11-40-10](https://user-images.githubusercontent.com/67191980/215308511-931cfd2b-4304-4d7c-b1ab-e3a1bd4ca053.jpg)

**Comment by jlipps** [comment]
Yeah, good idea!

**Comment by swap12875** [comment]
Hope the feature will be included in next release!

**Comment by eglitise** [comment]
This feature is included in version 2023.5.2.
