### ISSUE TITLE
Appium Inspector not working correctly whith Espresso

### ISSUE THREAD

**Issue by lofi96** [appium/appium-inspector#699]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I tried to write some Test Automation for one of my companies apps. While doing this wanted to use Appium Inspector to get some help finding the correct elements.
I started with this Capabilities:
{
“appium:app”: “C:\Users\User\Downloads\app-debug.apk”,
“appium:appActivity”: “au.com.demo.helloworld2.MainActivity”,
“appium:appPackage”: “au.com.demo.helloworld2”,
“appium:automationName”: “UiAutomator”,
“appium:espressoBuildConfig”: “{ “additionalAppDependencies”: [ “com.google.android.material:material:1.0.0”, “androidx.lifecycle:lifecycle-extensions:2.1.0” , “org.reduxkotlin:redux-kotlin-jvm:0.5.5”, “org.reduxkotlin:redux-kotlin-threadsafe-jvm:0.5.5”, “org.reduxkotlin:redux-kotlin-thunk:0.5.5”]}”,
“platformName”: “Android”,
“appium:showGradleLog”: true
}

The Inspector looked like this and I was able to easily locate the element:
The Element is highlighted green when hovering with the mouse and the Element handlers are shown at the correct position:
![grafik](https://user-images.githubusercontent.com/55657132/215360341-aaa90647-38a2-4df1-821d-4b0c8afb94ad.png)

The Sample App can be find here: https://github.com/sonugupta029/sampleAPK/blob/master/app-debug.apk

After some tests I noticed that I should switch to Espresso instead of UiAutomator. So I changed my Capabilities to:
{
“appium:app”: “C:\Users\User\Downloads\app-debug.apk”,
“appium:appActivity”: “au.com.demo.helloworld2.MainActivity”,
“appium:appPackage”: “au.com.demo.helloworld2”,
“appium:automationName”: “Espresso”,
“appium:espressoBuildConfig”: “{ “additionalAppDependencies”: [ “com.google.android.material:material:1.0.0”, “androidx.lifecycle:lifecycle-extensions:2.1.0” , “org.reduxkotlin:redux-kotlin-jvm:0.5.5”, “org.reduxkotlin:redux-kotlin-threadsafe-jvm:0.5.5”, “org.reduxkotlin:redux-kotlin-thunk:0.5.5”]}”,
“appium:forceEspressoRebuild”: true,
“platformName”: “Android”,
“appium:showGradleLog”: true
}

But now I’m facing the problem that the shown elements cannot be located anymore by simply clicking them. The Elements are not highlighted green and also the element handlers are shown at wrong positions:
![grafik](https://user-images.githubusercontent.com/55657132/215360334-7a1bee87-bd37-40e4-b1d4-1f79cd77aa43.png)

To me it looks like the whole screen is shifted. Is there a setting for this that I don’t know about? I am new to this topic.

I’m using the latest versions of Appium, Appium Inspector and Appium Esspresso. Just installed them today

## Environment

- I am running Appium Desktop version 3.1.4
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
@mykola-mokhnach any ideas here? does the espresso xml source contain accurate coordinates in the same format as the uiauto2 driver? 

i don't really have any way to use/test the espresso driver at the moment.

**Comment by mykola-mokhnach** [comment]
> does the espresso xml source contain accurate coordinates in the same format as the uiauto2 driver?

I would not expect both page sources to be the same. UIA2 fetches this info from the accessibility layer, while Espresso - directly from the app views hierarchy.

**Comment by jlipps** [comment]
OK. Maybe the coordinates are not translated based on screen dpi or something. @KazuCocoa any ideas how we can make the espresso driver compatible with the inspector?

**Comment by KazuCocoa** [comment]
I thought the espresso driver also worked. Let me try with our test app tomorrow

**Comment by lofi96** [comment]
Hi all, thanks for your quick replies.. @KazuCocoa feel free to also test with the app I linked in the issue description :)

**Comment by lofi96** [comment]
Hi @KazuCocoa can you fix this calculation in the near future? would help me a lot. Thanks :)

**Comment by KazuCocoa** [comment]
I'll try when I have time

**Comment by lofi96** [comment]
Hi @KazuCocoa,
I did some more investigation and noticed the following: 

When I run the application in UiAutomater2, the coordinates match the bounds. The Right, Lower Coordinate of the Bound of the Main Element is "720,1184" and also the displayed Coordinate matches (almost):
![grafik](https://user-images.githubusercontent.com/55657132/218584515-2e6a635c-0c34-4348-a430-cf5ef624059e.png)

When I run the app in Espresso, the coordinates no longer match the bounds. The Right, Lower Coordinate of the Bound of the Main Element is "720,1184", but the displayed coordinate is "475,843". So for me it looks like the screenshot resolution or something like that is wrong?
![grafik](https://user-images.githubusercontent.com/55657132/218585912-aae37fbb-f60d-45a7-95b9-2d5e2da5b1f3.png)

I have checked out the code of the application from Git, but I can't find the right place to look at the calculation... Do you have any ideas?

**Comment by lofi96** [comment]
FIXED IT! @KazuCocoa  @jlipps 

Did some debugging and found out the following: 
When using UiAutomator2 the deviceScreenSize is filled: 
![grafik](https://user-images.githubusercontent.com/55657132/218881507-010ec403-04fe-4eb1-81f4-edc487d8947a.png)

Using Espresso it is not: 
![grafik](https://user-images.githubusercontent.com/55657132/218881623-c849c0d2-522d-40ac-8bec-f72535ddb186.png)



These values theme to come from Appium. Looks for me the Appium Interface isn't working correct for Espresso.. 

My solution to get it working: Add this line to your configuration: 
"appium:deviceScreenSize": "720x1280"
![grafik](https://user-images.githubusercontent.com/55657132/218881770-e193055c-a454-4eff-baad-d3219da20ba0.png)

Or changing this line of code: 
![grafik](https://user-images.githubusercontent.com/55657132/218883985-514d8260-79ad-44f7-84fb-f9c6c4a93e33.png)


I must say, I don't really understand what the comment before the if statement was supposed to mean....
Please let me know your thoughts on this :)

**Comment by KazuCocoa** [comment]
Thank you for the investigation.
It seems like the inspector should do the trick (removed code) only for UIA2 automationName. The `deviceScreenSize` was not expected capabilities, it accidentally worked in the inspector as its implementation reason.

**Comment by lofi96** [comment]
@KazuCocoa thanks for your advice. I created a pull request to fix it
