### ISSUE TITLE
Tap by Coordinates does not work for Android apps in landscape

### ISSUE THREAD

**Issue by secretrobotron** [appium/appium-inspector#701]
## The problem

If I start a session in portrait mode, and then switch to landscape, tap by coordinates no longer works. It appears that the screen size is incorrect, and so all taps are offset. (I have tested this by finding the right button coordinates, and clicking those instead.) In other words:
1. Put phone in portrait mode
2. Start Appium session
3. Put phone in landscape mode
4. Try to click things

![image](https://user-images.githubusercontent.com/403231/216041839-99cad1c5-b7a4-4464-b66d-c880404d50a9.png)

To verify this, I've tried a couple of things:

1. I started Appium making sure the phone was in landscape mode already, which does work as expected.
2. The screen capture above is my phone in landscape mode, where I'm hovering over the Facebook icon at 248x272. My phone resolution is actually 1080x2220, so that maps to 509x559 (I think, used aspect ratio). If I find and click on those coordinates instead, it works.  The actual image inside the inspector is about 1080x529. 
 
My guess is that the source of the problem is that old width remains, and height is recalculated based on that. So, X and Y coordinates will always be too small.

I don't *think* this is an Appium problem, because I can see the right coordinates (those generated by Appium Inspector) in the Appium Server logs. I think the problem lies somewhere in how Appium Inspector recalculates the clickable area of the phone after an orientation change.

## Environment

- I am running Appium Desktop version 2022.11.1 (Appium Inspector).
- I am on (pick one):
    - [x] Mac
    - [x] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
after the orientation changes, if you click 'refresh' in the inspector does that change anything?

**Comment by secretrobotron** [comment]
@jlipps I don't believe so, but I will double-check. (I used that particular button a lot to try to go to different screens to test out this bug.)

**Comment by secretrobotron** [comment]
Confirmed: no
