### ISSUE TITLE
Press TAB and then ENTER to access website on Chrome

### ISSUE THREAD

**Issue by atigm** [appium/appium-inspector#702]
I launch Chrome, then I tape the url, this url is displayed in address bar there is no way to validate to access the website of the url.

Thank you

**Comment by jlipps** [comment]
I'm sorry I'll need a fuller description to understand what you are saying the problem is. What are you trying to accomplish? What steps are you taking to do it? What isn't working as you expect?

**Comment by atigm** [comment]
Hello,

Thank you for your response.

When I enter the website url in address bar of Chrome, I usually click on the Enter key to access my website, on Appium-Inspector, what key do I click?
1. Click on Chrome browser, then click on tab button
2. Click on textbox area, then click on tab button
3. Enter : https://mywebsite.com : click on Send keys button
4. I'm blocked here, what is the button I should click to access my website ? 
<img width="344" alt="inspector-chrome" src="https://user-images.githubusercontent.com/32271996/216928112-04d9c3ba-7591-41a9-8ab1-d77c643bbf58.png">

**Comment by jlipps** [comment]
what about clicking the blue arrow button the keyboard?

**Comment by atigm** [comment]
It's not possible to click on the blue button. it is not selectable.

**Comment by jlipps** [comment]
You could try going to the actions tab and filling out the details for press keycode to enter the code for the ENTER button. or you could tap by location instead of by selectable elements.

**Comment by atigm** [comment]
Thank you very much @jlipps 
I use the second method : by location.
