### ISSUE TITLE
Microsoft auth log in: loading issue

### ISSUE THREAD

**Issue by tetianakravchuk** [appium/appium-inspector#714]
## Appium or Appium Desktop?

I try to automate the app that has a Microsoft login. I use Sauce Lab's tunnel and Appium inspector to launch the app. Once I launch the app I get a blank screen. I have to refresh 6-7 times to see the login screen. How can I resolve this issue? 

## The problem

The app is not launching 

## Environment

- I am running Appium Desktop version  2022.7.1
- I am on (pick one):
    - [ ] Mac

**Comment by KazuCocoa** [comment]
Probably asking their support team is better than ask here
