### ISSUE TITLE
have two same name webview how to switch（java client）

### ISSUE THREAD

**Issue by KnightBlood** [appium/appium-inspector#726]
![image](https://user-images.githubusercontent.com/14256591/220261536-9df6b9da-6746-4285-9a3f-93b583fe0d86.png)
have two same name webview how to switch（java client）

**Comment by jlipps** [comment]
If you run an automated test instead of an inspector session and call get contexts, what items are in that list?

**Comment by KnightBlood** [comment]
> If you run an automated test instead of an inspector session and call get contexts, what items are in that list?

just native_app,webview_xxx.xxx.xxx

**Comment by jlipps** [comment]
then just switch to the webview_ one. once you're in the web context you may also need to switch to the correct window (the way chromedriver works is different webviews are located as different windows), by using getWindows or whatever.

**Comment by eglitise** [comment]
Closing due to no response
