### ISSUE TITLE
Cannot select button for Microsoft login page

### ISSUE THREAD

**Issue by Stanzarectah** [appium/appium-inspector#727]
When I use Appium Inspector I cannot select the 'Continue' button. The selector does not highlight the button if I attempt to mouse over it. Instead, the entire page gets highlighted.

![image](https://user-images.githubusercontent.com/17443786/220507704-86f683ad-f2f9-43d8-9240-9881811755c6.png)

I need to get the element reference of the button so that I can automate the click action whenever the user encounters this page.

This is on an Android 11 emulator device with Android Studio on Windows 10 I am using Appium 2.0.

**Comment by KazuCocoa** [comment]
You mayI would switch the context with WEBVIEW
