### ISSUE TITLE
Cannot start the Appium Inspector session

### ISSUE THREAD

**Issue by bughunterqa** [appium/appium-inspector#728]
When I use Appium Inspector I cannot start session and get an error message.
![image](https://user-images.githubusercontent.com/68702481/220693769-66ff831a-c994-4d03-af31-faf4f6974b20.png)

**Comment by jlipps** [comment]
this isn't an inspector issue. the error message is coming from the appium server. if you think there's a bug in the appium server, submit an issue at the appium repo with full logs.
