### ISSUE TITLE
Failed to create session. 'automationName' can't be blank; 'platformName' can't be blank

### ISSUE THREAD

**Issue by arielelkin** [appium/appium-inspector#729]
## Appium or Appium Desktop?
- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

1. start the appium server in my terminal
2. open Appium Inspector
3. click "Start Session"
4. this error appears:
<img width="937" alt="image" src="https://user-images.githubusercontent.com/1756909/221578092-bacfa895-09b6-489e-b921-1a6500f613f8.png">

```
Failed to create session. 'automationName' can't be blank; 'platformName' can't be blank
```

It's not clear why this is, nor where I can fill those values...

## Environment

- I am running Appium Desktop version 2023.2.1
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
You need to include proper capabilities to start an Appium session.

**Comment by jlipps** [comment]
You should add your capabilities in the capability builder. If you're confused about what capabilities are or which ones are required, best to start at the Appium documentation and go through all the intro guides and then read the docs for the driver you want to use. https://appium.github.io/appium/docs/en/2.0/
