### ISSUE TITLE
Appium inspector issue with Browserstack

### ISSUE THREAD

**Issue by vadik24** [appium/appium-inspector#742]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I'm having trouble to figure out why Appium Inspector  recognize hybrid android app to switch to webview when I'm connecting the android app locally but doesn't recognize hybrid view and unable to switch to webview when connected to BrowserStack cloud. Browserstack and local apps are the same app that I ran the build. No issue for IOS
BROWSERSTACK CLOUD SCREENSHOT
<img width="1000" alt="BrowserStack connected has no webview" src="https://user-images.githubusercontent.com/3231410/227109404-82f7539b-af3f-4763-b868-2942afa3d452.png">
LOCAL CONNECTION SCREENSHOT
<img width="1006" alt="Local connected has webview" src="https://user-images.githubusercontent.com/3231410/227109793-43b7fcd0-d6e1-4303-a2a3-3a5850bc5777.png">

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Mostly a timing issue I guess, but maybe it would be nice to ask BS support team
