### ISSUE TITLE
Appium Inspector - Unable to start a new session

### ISSUE THREAD

**Issue by iniyavans** [appium/appium-inspector#753]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

I Just /user a below desired capabilities :
{
  "platformName": "android",
  "appium:platformVersion": "12",
  "appium:deviceName": "Xiaomi 220116SI",
  "appium:automationName": "UiAutomator2",
  "appium:app": "/Users/iniyavanchoco/Downloads/debug.apk"
}
![Screenshot 2023-04-03 at 1 03 51 PM](https://user-images.githubusercontent.com/88368294/229441862-82de0aac-cd0b-4939-8c43-1494528aad17.png)

And get a Failed to create session. The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource error message.

I tried lot of way, If anyone can found a solution for it?
![Screenshot 2023-04-03 at 1 05 06 PM](https://user-images.githubusercontent.com/88368294/229442138-db0813ab-3c75-464e-8f53-b9b3554be060.png)

**Comment by jlipps** [comment]
What are your server connection details? Are they correct? What is the Appium log output if any?

**Comment by iniyavans** [comment]
Hi jlipps, I found a solution. 

https://discuss.appium.io/t/could-not-connect-to-server-to-appium-server/38872

**Comment by iniyavans** [comment]
We will close the issue
