### ISSUE TITLE
No route found for //session

### ISSUE THREAD

**Issue by tinyhare** [appium/appium-inspector#770]
## The problem
I copy Python code from appium-inspector -> Session Information -> Start this Kind of Session with Code.
![image](https://user-images.githubusercontent.com/6851513/231407385-d99bd543-6694-479d-b5bc-8080a1d99430.png)

 When I run it , I get error:  **"[debug] [HTTP] No route found for //session"** on the server side.

And to fix it , I must delete the trailing slash (/) in ` webdriver.Remote("http://172.16.5.2:4723/", caps)` ,  to this  ` webdriver.Remote("http://172.16.5.2:4723", caps)` 

Should it fixed by appium-inspector, the webdriver lib or appium server side ?
## Environment

- I am running Appium-inspector version _<2023.3.1>_.
- I am running Appium server version _<2.0.0-beta.62>_.
- I am on (pick one):
    - [x] Mac
    - [x] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
good question! i wonder if the best place for a fix would be the python client? what do you think @KazuCocoa ?

**Comment by KazuCocoa** [comment]
Maybe https://github.com/appium/appium-inspector/blob/2dec305b664cc482e5b3aa817d80142ae1a5fe12/app/renderer/lib/client-frameworks/framework.js#L8
The default placeholder has `/`, so the line should be `''` in case it is `/`

**Comment by jlipps** [comment]
yeah probably a good idea too
