### ISSUE TITLE
CORS error - SauceLabs on Web version Appium Inspector

### ISSUE THREAD

**Issue by wan-ps** [appium/appium-inspector#774]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I am encountering the CORS error while accessing the SauceLabs cloud server with the Web version Appium Inspector.

## Environment

- I am running Appium Inspector version 2022.7.1 (Web - Chrome browser).
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

<img width="977" alt="Screenshot 2023-04-13 at 5 21 44 PM" src="https://user-images.githubusercontent.com/32145793/231886547-87e27748-e381-4a0d-a00d-f22b4dc1d970.png">

**Comment by jlipps** [comment]
This means the sauce labs server doesn't have a cross origin header that allows requests from the browser version of appium inspector. Please report the bug to them.
