### ISSUE TITLE
IOS inpector

### ISSUE THREAD

**Issue by MuhammadHarisSikander** [appium/appium-inspector#841]
## Appium or Appium Inspector?

You are reporting an issue at the Appium Inspector repository. Appium Inspector is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Inspector but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Inspector issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Inspector version _<insert version here>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
What makes you think this is an issue with the inspector? Please also include the full appium log (not as a screenshot).

**Comment by eglitise** [comment]
Closing due to no response
