### ISSUE TITLE
feature idea: export/import saved actions

### ISSUE THREAD

**Issue by jlipps** [appium/appium-inspector#843]
With our new Actions Editor, it would be nice for users to be able to export their saved actions in JSON or some other format that other users could import. I think we could export to file and/or show json w/ copy/paste. And import could be similar (open file or have a box to paste json in).

**Comment by sudharsan-selvaraj** [comment]
Hey @jlipps @eglitise, I've taken a stab at implementing the export/import functionality using JSON files and would love to hear your early thoughts. Please share your feedback when you can. Thank you!

https://github.com/appium/appium-inspector/assets/20136913/e25b0d4b-f11e-4f37-9e6b-285a64b51712

**Comment by jlipps** [comment]
seems like a good idea, want to make a PR?

**Comment by sudharsan-selvaraj** [comment]
Cool, will open a PR soon!
