### ISSUE TITLE
An unexpected error occurred with message: Cannot read property 'toLowerCase' of undefined.

### ISSUE THREAD

**Issue by restmine** [appium/appium-inspector#869]
## Appium or Appium Inspector?

You are reporting an issue at the Appium Inspector repository. Appium Inspector is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Inspector but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Inspector issue

## The problem

when I try click search bar to find element, the issue is happened,  and I tried once more, the issue still occurred regularly.
the whole issue is:
An unexpected error occurred with message: Cannot read property 'toLowerCase' of undefined. Please kindly open up a bug report at https://github.com/appium/appium-inspector/issues/new. TypeError: Cannot read property 'toLowerCase' of undefined
[LICENSE.electron.txt](https://github.com/appium/appium-inspector/files/11636002/LICENSE.electron.txt)

## Environment

- I am running Appium Inspector version _<2023.5.2>_.
- I am on (pick one):
    - [ ] Mac
    - [√ ] Windows
    - [ ] Linux

**Comment by eglitise** [comment]
Can you provide the Appium capabilities you are using? It sounds like you are not using the `automationName` parameter.

**Comment by restmine** [comment]
> Can you provide the Appium capabilities you are using? It sounds like you are not using the `appium:automationName` property, which is mandatory for all currently supported drivers. Appium 2 even prevents session creation without it.

Yes，I am using a dcit 
with {"platformName":"Andorid", "devicesName":"nothing"} to start a session without that property as you told.I will try it soon

**Comment by eglitise** [comment]
With Android you need to add either `"appium:automationName":"UiAutomator2"` or `"appium:automationName":"Espresso"`, depending on whether you're using the UiAutomator2 or Espresso driver. If you're not sure, it's likely UiAutomator2.

Also note that `platformName` does not require the `appium:` prefix.

**Comment by tobecrazy** [comment]
same here on mac, 
capability 
`{
  "platformName": "Android",
  "appium:options": {
    "automationName": "UiAutomator2",
    "platformVersion": "11.0",
    "app": "/Users/Downloads/weixin.apk",
    "deviceName": "device1",
    "noReset": true
  }
}`

**Comment by eglitise** [comment]
@tobecrazy that's odd, your capability set looks fine. Are you also seeing this error when opening the element search? Just in case, can you please provide the full Appium log?

**Comment by jlipps** [comment]
pretty sure the Appium Inspector UI doesn't allow you to build nested objects unless you do it in the raw caps editor. Not sure if that could be an issue. Yes, please include a full Appium log for verification

**Comment by eglitise** [comment]
Issue has been fixed in version 2023.6.1.
