### ISSUE TITLE
Failed to create session

### ISSUE THREAD

**Issue by amclaire** [appium/appium-inspector#907]
i get this error each time  i tried to run appium inspector 
[debug] [HTTP] No route found for /wd/hub/session
[HTTP] <-- POST /wd/hub/session 404 428 ms - 211

my appium server is running 
my android studio emulator is also running too 
please how do i fix this

**Comment by eglitise** [comment]
Please provide your Appium server log and the configuration in the Inspector window (screenshot or otherwise).
If you're using Appium 2, ensure that 'Remote Path' is set to the default '/', not '/wd/hub'.

**Comment by amclaire** [comment]
removing /wd/hub. fixed the error thanks
