### ISSUE TITLE
bug: Elements are not recognized for some popups in app

### ISSUE THREAD

**Issue by Dor-bl** [appium/appium-inspector#962]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently when I try to inspect some elements on a popup in the given APP , the appium inspector seems to detect only the elements in the background
![image](https://github.com/appium/appium-inspector/assets/59066376/f046236b-3857-46a6-8351-164047bbe774)

### Expected Behavior

Elements for popups are recognized by the appium inspector 

### Operating System

Windows

### Appium Inspector Version

2023.6.2

### Appium Version

2.0.0-rc/3

**Comment by mykola-mokhnach** [comment]
I assume this is the expected behaviour if the above alert belongs to a different window. You could try to play with either `enableMultiWindows` or `enableTopmostWindowFromActivePackage` settings

**Comment by Dor-bl** [comment]
indeed `enableMultiWindows` worked for the appium inspector. But when I add it to the appium options , I can't find elements with "accessibilityid" .
using `enableTopmostWindowFromActivePackage` don't help.
any other ideas? :)

**Comment by Dor-bl** [comment]
Maybe I need to wrap it with settings[] ?

**Comment by eglitise** [comment]
Hmm, I just set `enableMultiWindows` to `true` and accessibility id search was still working, even inside a webview subtree. Can you provide your Appium log?

**Comment by Dor-bl** [comment]
Actually on the appium inspector it works, seems like something with the server, so I'll open another issue on the main repo.
