### ISSUE TITLE
An error occurred when starting the client software

### ISSUE THREAD

**Issue by Xuzan9396** [appium/appium-inspector#992]
### Current Behavior

![image](https://github.com/appium/appium-inspector/assets/24741439/1ef0ab9c-a44a-48aa-a22e-248318d73820)
<img width="465" alt="image" src="https://github.com/appium/appium-inspector/assets/24741439/19be2d39-577f-4127-9e8d-8cec008c33f6">

### Suggested Solution

May I ask how to solve, is less what dependence？

**Comment by eglitise** [comment]
Your screenshot shows that `Remote Path` is set to the default `/`. You are using Appium 1, so you need to change `Remote Path` to `/wd/hub`.
Please also note that Appium 1 is no longer supported - consider upgrading to Appium 2, where `Remote Path` will not need to be changed.

**Comment by Xuzan9396** [comment]
thank you！
But when I started, the apk installation error, actually my phone has been installed, still can not start


<img width="744" alt="image" src="https://github.com/appium/appium-inspector/assets/24741439/66872047-ae4c-4ec2-ad03-697d91409802">
@eglitise

**Comment by Xuzan9396** [comment]
my phone 
<img width="91" alt="image" src="https://github.com/appium/appium-inspector/assets/24741439/03db61bd-b0ff-4bfa-b6ea-39ce5d7500f2">

<img width="99" alt="image" src="https://github.com/appium/appium-inspector/assets/24741439/d462f25f-24e8-41eb-afb7-4594ba01b207">

**Comment by Xuzan9396** [comment]
<img width="338" alt="image" src="https://github.com/appium/appium-inspector/assets/24741439/d5b04f56-ef71-4966-91ea-73ba57fc382f">

<img width="1088" alt="image" src="https://github.com/appium/appium-inspector/assets/24741439/86894fe2-740c-409e-820e-d007d8318b2b">


 Always pop up asking me to install

**Comment by eglitise** [comment]
I would strongly suggest upgrading to Appium 2 and a newer version of the UiAutomator2 driver. It may include improvements for this issue.
Otherwise try uninstalling the server app and rebooting the phone.
