### ISSUE TITLE
bug: Always pop up asking me to install apk

### ISSUE THREAD

**Issue by Xuzan9396** [appium/appium-inspector#993]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/appium/appium-inspector/assets/24741439/9b5fa28f-cf40-4b67-a109-abefa01b23cd)

我phone
![image](https://github.com/appium/appium-inspector/assets/24741439/2d639f7d-be5b-406e-bfa8-e88ee1f19b83)
![image](https://github.com/appium/appium-inspector/assets/24741439/0a2435fb-f9c8-4fce-abda-498995ee0ee6)

![image](https://github.com/appium/appium-inspector/assets/24741439/e9faaf57-0f12-4203-9a67-d1bc2b47d992)

Can't start, always pop up asking me to install

### Expected Behavior

click start session 

### Operating System

Mac

### Appium Inspector Version

App Version: 2023.7.1

### Further Information

App Version: 2023.7.1
Electron: 13.6.9
Node.js: 14.16.0

**Comment by Xuzan9396** [comment]
<img width="843" alt="image" src="https://github.com/appium/appium-inspector/assets/24741439/441cc267-d7c7-453b-a593-2e83f2d20d3c">

**Comment by Xuzan9396** [comment]
<img width="639" alt="image" src="https://github.com/appium/appium-inspector/assets/24741439/aa8f4e68-3e73-4bc0-af72-d23422b52b4c">

**Comment by Xuzan9396** [comment]
刚刚提示超时， 然后过了几秒，apk就装好了，但我重新又惦记 start session ，又提示我要安装apk,
我重启手机和软件都没用

**Comment by eglitise** [comment]
This is not a problem with the Inspector. As I've mentioned in your other issue, please try upgrading to Appium 2 and a newer UiAutomator2 driver, which may resolve this problem. If it still persists, please create an issue [at the main Appium repo.](https://github.com/appium/appium/issues)

**Comment by Xuzan9396** [comment]
![image](https://github.com/appium/appium-inspector/assets/24741439/9677bfab-58f0-47fb-857b-cc48e73c4766)

<img width="479" alt="image" src="https://github.com/appium/appium-inspector/assets/24741439/e88c2e55-5c32-41a4-8663-ff5a5fe02faf">

Still always times out and then pops up to install apk

**Comment by Xuzan9396** [comment]
@eglitise

**Comment by Xuzan9396** [comment]
<img width="790" alt="image" src="https://github.com/appium/appium-inspector/assets/24741439/f7b432c5-d760-41db-932b-9431bb7cf441">

**Comment by eglitise** [comment]
Please create an issue on the main Appium repo about this.

**Comment by Xuzan9396** [comment]
Mobile phone problem，I use a Huawei phone
